import { Definition, Definitions, FrameDef } from "../../../engine/core.ts";
import { HumanModifiers } from "../../others/constants.ts";

export enum EffectType{
    Buff,
    Debuff,
    Neutral
}
export interface EffectDef extends Definition{
    effect_type:EffectType
    particles?:{
        delay:number
        frame:FrameDef
    }
    assets?:{
        sounds?:{
            when_take?:string
            when_remove?:string
        }
    }
    side_effects:SideEffect[]
}
export enum SideEffectType{
    AddEffect,
    Modify,
    Damage,
    Heal,
    Parachute
}
export type SideEffect=({
    type:SideEffectType.AddEffect
    effect:string
    duration:number
    merge?:boolean
}|{
    type:SideEffectType.Modify,
    modify:Partial<HumanModifiers>
}|{
    type:SideEffectType.Damage
    amount:number
    piercing?:boolean
    obstacle_mult?:number
}|{
    type:SideEffectType.Heal,
    health?:{
        amount:number
        max?:number
    }
    boost?:{
        amount:number
        def:string
        max?:number
    }
    global?:{
        amount:number
        boost?:string
    }
}|{
    type:SideEffectType.Parachute,
})
export const Effects=new Definitions<EffectDef,{}>()

export interface EffectInstance{
    effect:EffectDef
    time:number
    tick_time:number
}
Effects.insert(
    {
        idString:"fire",
        effect_type:EffectType.Debuff,
        side_effects:[
            {
                type:SideEffectType.Damage,
                amount:8,
                piercing:true,
            },
        ],
        particles:{
            delay:0.35,
            frame:{
                scale:1,
                image:"fire_particle"
            },
        },
    },
    {
        idString:"kill_haste",
        effect_type:EffectType.Buff,
        side_effects:[
            {
                type:SideEffectType.Modify,
                modify:{
                    speed:1.5
                }
            },
        ],
        particles:{
            delay:0.2,
            frame:{
                scale:2,
                image:"boost_addiction_particle"
            },
        },
        assets:{
            sounds:{
                when_take:"effect_take_2"
            }
        },
    },
    {
        idString:"nature_help",
        effect_type:EffectType.Buff,
        particles:{
            delay:0.2,
            frame:{
                scale:2,
                image:"leaf_01_particle_1"
            },
        },
        assets:{
            sounds:{
                when_take:"effect_take_1"
            }
        },
        side_effects:[
            {
                type:SideEffectType.Modify,
                modify:{
                    speed:1.4
                }
            },
        ],
    }
)