import { Definition, Definitions } from "../../../engine/core.ts";
import { ItemQuality } from "../../others/item.ts";
import { InventoryItemType } from "../utils.ts";
export interface AmmoDef extends Definition{
    tint:number
    defaultTrail:number
    strongTrail:number
    defaultProj:number
    strongProj:number
    ammoType:string

    liquid?:boolean
    drop_count?:number

    item_type?:InventoryItemType.ammo
    quality:ItemQuality
}
export function Ammos_Default_Init(ammos:Definitions<AmmoDef,{}>){
    ammos.insert(
        //Main
        {
            idString:"12g",
            ammoType:"12g",
            defaultTrail:0xcfada0,
            strongTrail:0xdb2218,
            defaultProj:0xcfada0,
            strongProj:0xdb2218,
            tint:0xff0000,
            drop_count:15,
            quality:ItemQuality.Common
        },
        {
            idString:"762mm",
            ammoType:"762mm",
            defaultTrail:0x779bbd,
            strongTrail:0x0034f2,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x0000ff,
            quality:ItemQuality.Common
        },
        {
            idString:"556mm",
            ammoType:"556mm",
            defaultTrail:0x66ff88,
            strongTrail:0x00a41c,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x00ff00,
            quality:ItemQuality.Common
        },
        {
            idString:"9mm",
            ammoType:"9mm",
            defaultTrail:0xefef9f,
            strongTrail:0xefef33,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0xffff00,
            quality:ItemQuality.Common
        },
        //Modes
        {
            idString:"45acp",
            ammoType:"45acp",
            defaultTrail:0xcea2e0,
            strongTrail:0x791390,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x791390,
            quality:ItemQuality.Common
        },
        {
            idString:"22lr",
            ammoType:"22lr",
            defaultTrail:0xefefef,
            strongTrail:0xefefff,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0xffffff,
            quality:ItemQuality.Common
        },
        {
            idString:"50cal",
            ammoType:"50cal",
            defaultTrail:0x555555,
            strongTrail:0x000000,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x000000,
            quality:ItemQuality.Epic
        },
        //Exotic
        {
            idString:"308sub",
            ammoType:"308sub",
            defaultTrail:0x222835,
            strongTrail:0x0c1420,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x001330,
            drop_count:10,
            quality:ItemQuality.Mythic
        },
        {
            idString:"explosive_ammo",
            ammoType:"explosive_ammo",
            defaultTrail:0x616d61,
            strongTrail:0x2b402b,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x001330,
            quality:ItemQuality.Legendary
        },
        {
            idString:"gasoline",
            ammoType:"gasoline",
            defaultTrail:0xefef33,
            strongTrail:0x889fcb,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            liquid:true,
            tint:0x001330,
            quality:ItemQuality.Mythic
        },
        {
            idString:"mana_mm",
            ammoType:"mana",
            defaultTrail:0x889fcb,
            strongTrail:0x009fcb,
            defaultProj:0xefef9f,
            strongProj:0xefef33,
            tint:0x001330,
            quality:ItemQuality.Legendary
        }
    )
}