import { Definition, Definitions } from "../../../engine/core.ts";
import { ItemRank } from "../../others/item.ts";
import { type GameItemType, type GameObjectDefinitionType } from "../utils.ts";
export interface AmmoDef extends Definition{
    def_type?:GameObjectDefinitionType.item
    item_type?:GameItemType.ammo
    name?:string
    tname?:string
    rank:ItemRank

    description?:string|boolean
    tint:number
    defaultTrail?:number
    strongTrail?:number[]
    ammoType:string

    liquid?:boolean
    drop_count?:number
}
export function Ammos_Default_Init(ammos:Definitions<AmmoDef,{}>){
    ammos.insert(
        //Main
        {
            idString:"12g",
            name:"12G",
            ammoType:"12g",
            description:true,
            defaultTrail:0xcfada0,
            strongTrail:[0xdb2218,0x96231d],
            tint:0xff0000,
            drop_count:15,
            rank:ItemRank.E
        },
        {
            idString:"762mm",
            name:"7.62-MM",
            ammoType:"762mm",
            description:true,
            defaultTrail:0xb8ccde,
            strongTrail:[0x0034f2,0x14319c],
            tint:0x0000ff,
            rank:ItemRank.E
        },
        {
            idString:"556mm",
            name:"5.56-MM",
            ammoType:"556mm",
            description:true,
            defaultTrail:0xa7f2b2,
            strongTrail:[0x27f227,0x00a41c],
            tint:0x00ff00,
            rank:ItemRank.E
        },
        {
            idString:"45acp",
            name:".45-ACP",
            ammoType:"45acp",
            description:true,
            defaultTrail:0xcea2e0,
            strongTrail:[0x791390,0x4a0659],
            tint:0x791390,
            rank:ItemRank.E
        },
        {
            idString:"9mm",
            name:"9-MM",
            ammoType:"9mm",
            description:true,
            defaultTrail:0xefef9f,
            strongTrail:[0xefef33,0x8a7b0e],
            tint:0xffff00,
            rank:ItemRank.E
        },
        {
            idString:"22lr",
            name:"22-LR",
            ammoType:"22lr",
            description:true,
            defaultTrail:0xaaaaaa,
            strongTrail:[0xefefff,0x9c9cb8],
            tint:0xffffff,
            rank:ItemRank.E
        },

        //Exotic
        {
            idString:"50cal",
            name:".50-Cal",
            ammoType:"50cal",
            description:true,
            defaultTrail:0x555555,
            strongTrail:[0x654747,0x653339],
            tint:0x504747,
            rank:ItemRank.B
        },
        {
            idString:"308sub",
            name:".308 Sub-Sonic",
            ammoType:"308sub",
            description:true,
            defaultTrail:0x222835,
            strongTrail:[0x0c1420,0x050d1a],
            tint:0x001330,
            drop_count:10,
            rank:ItemRank.A
        },
        {
            idString:"explosive_ammo",
            ammoType:"explosive_ammo",
            description:true,
            defaultTrail:0x616d61,
            strongTrail:[0x2b402b,0x0e1c0e],
            tint:0x001330,
            rank:ItemRank.S
        },
        {
            idString:"gasoline",
            ammoType:"gasoline",
            description:true,
            defaultTrail:0xefef33,
            strongTrail:[0xefef33,0xefef33],
            liquid:true,
            tint:0x001330,
            rank:ItemRank.A
        },
        {
            idString:"mana_mm",
            ammoType:"mana",
            description:true,
            defaultTrail:0x889fcb,
            strongTrail:[0x009fcb,0x009fcb],
            tint:0x001330,
            rank:ItemRank.S
        }
    )
}