import { AKeyFrame, DeepPartial, Definition, Definitions, mergeDeep, Random1, v2, Vec2 } from "../../../engine/core.ts";
import { DefaultFistRig, ItemRank } from "../../others/item.ts";
import { Boosts, BoostType } from "../player/boosts.ts";
import { SideEffect, SideEffectType } from "../player/effects.ts";
import { InventoryItemType } from "../utils.ts";
export type ConsumingAction={
    type:0,
    use_delay:number
    side_effects:SideEffect[]
    boost_type?:BoostType
    drink?:boolean
    drop?:boolean
    animation?:AKeyFrame[]
}|{
    type:1,
    length:number
    delay:number
    spread?:number
    jitterRadius?:number
    allow_self?:boolean
    synsed_particle?:{
        def:string
        count?:number
        speed?:Random1
        self_speed?:Random1
    }
}
export interface ConsumibleDef extends Definition{
    rank:ItemRank
    consuming:ConsumingAction
    condition?:ConsumibleCondition[]
    allow_merge?:boolean
    assets?:{
        using_particle?:string
        using_sound?:string
        pickup_sound?:string
    }
    item_type?:InventoryItemType.consumible
    description?:string|boolean
}
export enum ConsumibleCondition{
    UnfullHealth,
    UnfullExtra
}
export const ConsumiblesAnimations={
    drinking:(frame:string="yellow_soda",time:number=2,hotspot?:Vec2)=>[
        {
            actions:[
                {
                    type:"sprite",
                    fuser:"weapon",
                    image:frame,
                    visible:true,
                    scale:1.1,
                    rotation:-0.2,
                    hotspot:hotspot??v2(0.5,.5),
                    zIndex:6,
                    position:DefaultFistRig.right!.position
                },
                {
                    ...DefaultFistRig.left!,
                    visible:true,
                    type:"transform",
                    fuser:"left_arm",
                },
                {
                    ...DefaultFistRig.right!,
                    visible:true,
                    type:"transform",
                    fuser:"right_arm",
                },
            ],
            time:0
        },
        {
            actions:[
                {
                    type:"tween",
                    fuser:"weapon",
                    to:{
                        rotation:-1.570796,
                        position:v2(.46,0)
                    }
                },
                {
                    type:"tween",
                    fuser:"right_arm",
                    to:{
                        rotation:DefaultFistRig.right!.rotation-0.4,
                        position:v2(DefaultFistRig.right!.position.x,DefaultFistRig.right!.position.y-0.2)
                    }
                }
            ],
            time:0.5
        }
    ]
}satisfies Record<string,()=>AKeyFrame[]>

export function CreateSoda(color:string,boost_type:BoostType,max?:number,amount:number=25,item:DeepPartial<ConsumibleDef>={}):ConsumibleDef{
    return mergeDeep({
        idString:color+"_soda",
        description:true,
        consuming:{
            type:0,
            side_effects:[
                {
                    type:SideEffectType.Heal,
                    boost:{
                        amount:amount,
                        max,
                        def:Boosts[boost_type]
                    }
                }
            ],
            use_delay:3,
            animation:ConsumiblesAnimations.drinking(color+"_soda",2.5),
            drink:true,
            drop:true,
            boost_type:boost_type,
        },
        condition:[ConsumibleCondition.UnfullExtra],
        rank:ItemRank.D,
        assets:{
            using_sound:"using_soda",
            pickup_sound:"soda_pickup"
        }
    },item)
}
export function CreatePills(color:string,boost_type:BoostType,item:DeepPartial<ConsumibleDef>={}):ConsumibleDef{
    return mergeDeep({
        idString:color+"_pills",
        description:true,
        consuming:{
            type:0,
            side_effects:[
                {
                    type:SideEffectType.Heal,
                    boost:{
                        amount:100,
                        def:Boosts[boost_type]
                    }
                }
            ],
            use_delay:6,
            boost_type:boost_type,
        },
        rank:ItemRank.B,
        condition:[ConsumibleCondition.UnfullExtra],
        assets:{
            using_sound:"using_pills",
            pickup_sound:"pills_pickup",
        },
    },item)
}
export function CreateSpray(color:string,item:DeepPartial<ConsumibleDef>={}):ConsumibleDef{
    return mergeDeep({
        idString:color+"_spray",
        consuming:{
            type:1,
            delay:0.25,
            length:0.5,
            allow_self:true,
            jitterRadius:0.4,
            spread:5,
            synsed_particle:{
                def:"healing_spray_particle",
                speed:6,
                self_speed:2.5,
            }
        },
        rank:ItemRank.B,
        condition:[ConsumibleCondition.UnfullExtra],
        assets:{
            using_sound:"using_pills",
            pickup_sound:"pills_pickup",
        },
    },item)
}
export function Consumibles_Default_Init(consumibles:Definitions<ConsumibleDef,{}>){
    consumibles.insert(
        {
            idString:"bandage",
            consuming:{
                type:0,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        health:{
                            amount:20,
                            max:0.75
                        }
                    }
                ],
                use_delay:3,
            },
            description:true,
            rank:ItemRank.D,
            condition:[ConsumibleCondition.UnfullHealth],
            assets:{
                using_particle:"healing_particle"
            }
        },
        {
            idString:"medikit",
            consuming:{
                type:0,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        health:{
                            amount:100,
                        }
                    }
                ],
                use_delay:5.5,
            },
            rank:ItemRank.D,
            description:true,
            condition:[ConsumibleCondition.UnfullHealth]
        },

        //Adrenaline
        CreateSoda("yellow",BoostType.Adrenaline),
        {
            idString:"inhaler",
            description:true,
            consuming:{
                type:0,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        boost:{
                            amount:50,
                            def:Boosts[BoostType.Adrenaline]
                        }
                    }
                ],
                use_delay:4.5,
                boost_type:BoostType.Adrenaline
            },
            rank:ItemRank.D,
            condition:[ConsumibleCondition.UnfullExtra],
        },
        CreatePills("yellow",BoostType.Adrenaline),

        //Shield
        CreateSoda("blue",BoostType.Shield,0.5),
        {
            idString:"blue_potion",
            consuming:{
                type:0,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        boost:{
                            amount:50,
                            def:Boosts[BoostType.Shield]
                        }
                    }
                ],
                use_delay:4.5,
                drink:true,
                drop:true,
                boost_type:BoostType.Shield,
                animation:ConsumiblesAnimations.drinking("blue_potion",4.5,v2(0.5,0.35)),
            },
            rank:ItemRank.C,
            condition:[ConsumibleCondition.UnfullExtra],
            description:true,
            assets:{
                using_sound:"using_potion"
            },
        },
        CreatePills("blue",BoostType.Shield),
        //Mana
        CreateSoda("purple",BoostType.Mana),
        {
            idString:"purple_potion",
            consuming:{
                type:0,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        boost:{
                            amount:50,
                            def:Boosts[BoostType.Mana]
                        }
                    }
                ],
                use_delay:4.5,
                animation:ConsumiblesAnimations.drinking("purple_potion",4.5,v2(0.5,0.35)),
                drink:true,
                boost_type:BoostType.Mana
            },
            rank:ItemRank.B,
            condition:[ConsumibleCondition.UnfullExtra],
            assets:{
                using_sound:"using_potion"
            },
        },
        CreatePills("purple",BoostType.Mana),
        //Addiction
        CreateSoda("red",BoostType.Addiction,0.5,50),
        {
            idString:"small_red_crystal",
            description:true,
            consuming:{
                type:0,
                use_delay:1.5,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        boost:{
                            amount:25,
                            def:Boosts[BoostType.Addiction]
                        }
                    }
                ],
                animation:ConsumiblesAnimations.drinking("small_red_crystal",1.4),
                boost_type:BoostType.Addiction
            },
            condition:[ConsumibleCondition.UnfullExtra],
            rank:ItemRank.B,
        },
        {
            idString:"red_crystal",
            description:true,
            consuming:{
                type:0,
                use_delay:3,
                side_effects:[
                    {
                        type:SideEffectType.Heal,
                        boost:{
                            amount:50,
                            def:Boosts[BoostType.Addiction]
                        }
                    }
                ],
                boost_type:BoostType.Addiction,
                animation:ConsumiblesAnimations.drinking("red_crystal",2.9),
            },
            condition:[ConsumibleCondition.UnfullExtra],
            rank:ItemRank.B,
        },
        CreatePills("red",BoostType.Addiction),
        //Green Bless
        CreateSoda("green",BoostType.GreenBless,undefined,100),
        //Death
        CreateSoda("black",BoostType.Death,undefined,1),
        //Misc
        /*{
            idString:"pocket_portal",
            consuming:{
                type:0,
                use_delay:1.5,
                side_effects:[
                    {
                        type:SideEffectType.Parachute
                    }
                ],
                boost_type:BoostType.Mana
            },
            rank:ItemRank.A,
        },*/

        CreateSpray("healing")
    )
}