import { InventoryItemType } from "../utils.ts";
import { ItemRank } from "../../others/item.ts";
import { Definition, Definitions, v2, Vec2 } from "../../../engine/core.ts";
import { SideEffectType } from "../player/effects.ts";
import { HumanModifiers } from "../../others/constants.ts";
export interface VestDef extends Definition{
    defence:number
    reduction:number
    health?:number
    level:number
    special?:boolean
    tint:number
    rank:ItemRank
    reflect_bullets?:boolean
    item_type?:InventoryItemType.vest

    property?:string[]
    events?:Record<string,(e:any)=>void>
    modifiers?:Partial<HumanModifiers>
}
export interface HelmetDef extends Definition{
    defence:number
    reduction:number
    health?:number
    health_frames?:{frame:string,health:number}[]
    level:number
    special?:boolean
    position?:Vec2
    rank:ItemRank
    item_type?:InventoryItemType.helmet

    property?:string[]
    events?:Record<string,(e:any)=>void>
    modifiers?:Partial<HumanModifiers>
}
export function Helmets_Default_Init(helmets:Definitions<HelmetDef,{}>){
    helmets.insert(
        {
            idString:"basic_helmet",
            defence:0,
            level:1,
            health:1000,
            reduction:0.1,
            position:v2(0,0),
            rank:ItemRank.E
        },
        {
            idString:"regular_helmet",
            defence:0,
            level:2,
            health:300,
            health_frames:[
                {
                    frame:"regular_helmet_world_1",
                    health:0.6666666
                },
                {
                    frame:"regular_helmet_world_2",
                    health:0.3333333
                }
            ],
            reduction:0.15,
            position:v2(0,0),
            rank:ItemRank.D
        },
        {
            idString:"military_helmet",
            defence:0,
            level:3,
            special:true,
            health:1600,
            reduction:0.2,
            position:v2(0,0),
            rank:ItemRank.C
        },

        {
            idString:"lastman_helmet",
            defence:0,
            level:5,
            special:true,
            reduction:0.3,
            position:v2(0,0),
            rank:ItemRank.S,

            modifiers:{
                health:2
            },
            property:["extended_capacity","infinity_ammo"],
            events:{
                "kill":(e)=>{
                    e.owner.give_boost(25)
                    e.owner.health_data.health+=25
                    e.owner.side_effect({
                        type:SideEffectType.AddEffect,
                        duration:4,
                        effect:"kill_haste"
                    })
                },
                "pickup":(e)=>{
                    e.user.inventory.extended_capacity=e.user.inventory.accessorys.has_property("extended_capacity")
                    e.user.inventory.infinity_ammo=e.user.inventory.accessorys.has_property("infinity_ammo")
                },
                "drop":(e)=>{
                    e.user.inventory.extended_capacity=e.user.inventory.accessorys.has_property("extended_capacity")
                    e.user.inventory.infinity_ammo=e.user.inventory.accessorys.has_property("infinity_ammo")
                },
            }
        },
    )
}
export function Vests_Default_Init(vests:Definitions<VestDef,{}>){
    vests.insert(
        //Normals Vest
        {
            idString:"basic_vest",
            defence:0,
            level:1,
            health:2000,
            reduction:0.1,
            tint:0xffffff,
            rank:ItemRank.E
        },
        {
            idString:"regular_vest",
            defence:0,
            level:2,
            health:2300,
            reduction:0.15,
            tint:0x556655,
            rank:ItemRank.D
        },
        {
            idString:"military_vest",
            defence:0,
            level:3,
            special:true,
            health:2600,
            reduction:0.2,
            tint:0x010011,
            rank:ItemRank.C
        },
        {
            idString:"elite_vest",
            defence:0,
            level:4,
            special:true,
            reflect_bullets:true,
            reduction:0.25,
            tint:0x5C322E,
            rank:ItemRank.A
        },
    )
}