import { InventoryItemType } from "../utils.ts";
import { ItemRank } from "../../others/item.ts";
import { Definition, Definitions, v2, Vec2 } from "../../../engine/core.ts";
import { HumanModifiers } from "../../others/constants.ts";
import { SideEffectType } from "../player/effects.ts";
export interface VestDef extends Definition{
    defence:number
    reduction:number
    health?:number
    level:number
    tint:number
    rank:ItemRank
    reflect_bullets?:boolean
    item_type?:InventoryItemType.vest
}
export interface HelmetDef extends Definition{
    defence:number
    reduction:number
    health?:number
    health_frames?:{frame:string,health:number}[]
    level:number
    position?:Vec2
    rank:ItemRank
    item_type?:InventoryItemType.helmet
}
export interface AccessoryDef extends Definition{
    rank:ItemRank
    modifiers?:Partial<HumanModifiers>
    events?:Record<string,(e:any)=>void>
    item_type?:InventoryItemType.accessory
}
export function Helmets_Default_Init(helmets:Definitions<HelmetDef,{}>){
    helmets.insert(
        {
            idString:"basic_helmet",
            defence:0,
            level:1,
            health:1000,
            reduction:0.1,
            position:v2(0,0),
            rank:ItemRank.E
        },
        {
            idString:"regular_helmet",
            defence:0,
            level:2,
            health:300,
            health_frames:[
                {
                    frame:"regular_helmet_world_1",
                    health:0.6666666
                },
                {
                    frame:"regular_helmet_world_2",
                    health:0.3333333
                }
            ],
            reduction:0.15,
            position:v2(0,0),
            rank:ItemRank.D
        },
        {
            idString:"tactical_helmet",
            defence:0,
            level:3,
            health:1600,
            reduction:0.2,
            position:v2(0,0),
            rank:ItemRank.C
        },
        {
            idString:"lastman_helmet",
            defence:0,
            level:5,
            reduction:0.3,
            position:v2(0,0),
            rank:ItemRank.S
        },
    )
}
export function Vests_Default_Init(vests:Definitions<VestDef,{}>){
    vests.insert(
        //Normals Vest
        {
            idString:"basic_vest",
            defence:0,
            level:1,
            health:2000,
            reduction:0.1,
            tint:0xffffff,
            rank:ItemRank.E
        },
        {
            idString:"regular_vest",
            defence:0,
            level:2,
            health:2300,
            reduction:0.15,
            tint:0x556655,
            rank:ItemRank.D
        },
        {
            idString:"tactical_vest",
            defence:0,
            level:3,
            health:2600,
            reduction:0.2,
            tint:0x010011,
            rank:ItemRank.C
        },
        {
            idString:"elite_vest",
            defence:0,
            level:4,
            reflect_bullets:true,
            reduction:0.25,
            tint:0x5C322E,
            rank:ItemRank.A
        },
    )
}
export function Accessorys_Default_Init(accessorys:Definitions<AccessoryDef,{}>){
    accessorys.insert(
        {
            idString:"bullet_breaker_barrel",
            rank:ItemRank.A,
            events:{
                "gun_shoot":(e)=>{
                    e.bullet.damage*=0.7

                    let b=e.user.game.add_bullet(e.position,e.angle-0.02,e.item.def.bullet.def,e.user,e.item.def.ammoType,e.item.def,e.user.layer)
                    b.damage*=0.22
                    b.modifiers={
                        speed:e.user.modifiers.bullet_speed,
                        size:e.user.modifiers.bullet_size*0.4,
                    }
                    b.set_direction(e.angle-0.02)

                    b=e.user.game.add_bullet(e.position,e.angle+0.02,e.item.def.bullet.def,e.user,e.item.def.ammoType,e.item.def,e.user.layer)
                    b.damage*=0.22
                    b.modifiers={
                        speed:e.user.modifiers.bullet_speed,
                        size:e.user.modifiers.bullet_size*0.4,
                    }
                    b.set_direction(e.angle+0.02)
                }
            },
        },
        {
            idString:"liquid_insanity",
            rank:ItemRank.A,
            events:{
                "kill":(e)=>{
                    e.owner.health_data.health+=20
                    e.owner.side_effect({
                        type:SideEffectType.AddEffect,
                        duration:4,
                        effect:"kill_haste"
                    })
                }
            }
        },
        {
            idString:"nature_leaf",
            rank:ItemRank.A,
            events:{
                "damage":(e)=>{
                    e.player.health_data.health+=20
                    e.player.side_effect({
                        type:SideEffectType.AddEffect,
                        duration:4,
                        effect:"nature_help"
                    })
                }
            }
        },
    )
}