import { Definition, Definitions, FrameDef, MinMax1, v2, Vec2 } from "../../../engine/core.ts";
import { DefaultFistRig, FistRig, ItemRank, WeaponAssets, WeaponRig } from "../../others/item.ts"
import { InventoryItemType } from "../utils.ts";
export type GrenadeDef={
    explosion?:string

    resistance?:{
        push_force?:number
        zindex_set?:boolean
    }
    gravity:number
    radius:number
    zBaseScale:number
    zScaleAdd:number

    decays:{
        ground_speed:number
        ground_rotation:number
    }

    cook?:{
        allow_hand:boolean
        fuse_time?:number
        ground?:boolean
        impact?:boolean
    }
    throw_max_speed?:number

    frames:{
        world:FrameDef
    }
    collision_damage?:number

    speed_mod?:number

    arms?:FistRig
    image?:WeaponRig
    assets?:WeaponAssets

    rank:ItemRank
    item_type?:InventoryItemType.grenade

    call_airdrop?:{
        delay:number
    }
    call_airstrike?:{
        delay:number
        def:string
    }
    particles?:{
        spawn_delay?:number
        spawn:Vec2
        delay:number
        frame:FrameDef
        speed:MinMax1
        lifetime:MinMax1
        tint:number
    }
}&Definition
const GrenadeRig={
    position:v2(0.5,0.18),
    rotation:0.2
}
export function Grenades_Default_Init(grenades:Definitions<GrenadeDef,{}>){
    grenades.insert(
        {
            idString:"frag_grenade",
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.7,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:true,
                fuse_time:6
            },
            throw_max_speed:15,
            explosion:"frag_grenade_explosion",
            frames:{
                world:{
                    image:"proj_frag"
                }
            },
            speed_mod:1,
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.E
        },
        {
            idString:"smoke_grenade",
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.7,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:4
            },
            throw_max_speed:17,
            explosion:"smoke_grenade_explosion",
            frames:{
                world:{
                    image:"proj_smoke"
                }
            },
            speed_mod:1,
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.E
        },
        {
            idString:"molotov",
            gravity:2,
            radius:0.25,
            zBaseScale:0.7,
            zScaleAdd:0.4,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                ground:true
            },
            throw_max_speed:10,
            explosion:"molotov_explosion",
            frames:{
                world:{
                    image:"proj_molotov",
                    hotspot:v2(0.35,0.35)
                }
            },
            speed_mod:1,
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.D,
        },
        //Mirv
        {
            idString:"mirv_grenade",
            gravity:2.5,
            radius:0.25,
            zBaseScale:0.8,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:true,
                fuse_time:6
            },
            explosion:"mirv_grenade_explosion",
            throw_max_speed:15,
            frames:{
                world:{
                    image:"proj_mirv"
                }
            },
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.C
        },
        {
            idString:"submirv_grenade",
            gravity:3,
            radius:0.1,
            zBaseScale:1,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:false,
                fuse_time:2
            },
            explosion:"submirv_grenade_explosion",
            frames:{
                world:{
                    image:"proj_submirv"
                }
            },
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.E
        },
        {
            idString:"blue_flare",
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.6,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:20
            },
            throw_max_speed:20,
            explosion:"blue_flare_explosion",
            frames:{
                world:{
                    image:"proj_blue_flare"
                }
            },
            speed_mod:1,
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.A,
            call_airdrop:{
                delay:9
            },
            particles:{
                spawn_delay:6,
                tint:0x08b0ce,
                delay:0.1,
                spawn:v2(0.3,0),
                lifetime:{
                    min:2,
                    max:5
                },
                speed:{
                    min:0.1,
                    max:0.25
                },
                frame:{
                    image:"gas_particle",
                    scale:0.01
                }
            },
        },
        {
            idString:"red_flare",
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.6,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:9
            },
            throw_max_speed:20,
            explosion:"red_flare_explosion",
            frames:{
                world:{
                    image:"proj_red_flare"
                }
            },
            speed_mod:1,
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.A,
            call_airstrike:{
                delay:3,
                def:"nuke"
            },
            particles:{
                spawn_delay:3,
                tint:0xca0819,
                delay:0.1,
                spawn:v2(0.3,0),
                lifetime:{
                    min:2,
                    max:5
                },
                speed:{
                    min:0.1,
                    max:0.25
                },
                frame:{
                    image:"gas_particle",
                    scale:0.01
                }
            },
        },
        {
            idString:"nuke",
            gravity:0.2,
            radius:0.6,
            zBaseScale:1,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:false,
                ground:true,
            },
            explosion:"nuke_explosion",
            resistance:{
                push_force:0,
                zindex_set:true
            },
            frames:{
                world:{
                    image:"proj_nuke"
                }
            },
            arms:DefaultFistRig,
            image:GrenadeRig,
            rank:ItemRank.S
        },
    )
}