import { Definition, Definitions, FrameDef, FrameTransform, MinMax1, v2, Vec2 } from "../../../engine/core.ts";
import { DefaultFistRig, FistRig, ItemRank, WeaponAssets } from "../../others/item.ts"
import { InventoryItemType } from "../utils.ts";
export type Airstrike={
    count?:number
    delay:number
    delay_gap?:number
    bomb:{
        count?:number
        radius?:number
        def:string
    }
}
export type GrenadeDef={
    rank:ItemRank
    item_type?:InventoryItemType.grenade
    description?:string|boolean

    explosion?:string
    call_airdrop?:{
        delay:number
    }
    call_airstrike?:Airstrike
    particles?:{
        spawn_delay?:number
        spawn:Vec2
        delay:number
        frame:FrameDef
        speed:MinMax1
        lifetime:MinMax1
        tint:number
    }

    push_force_resistence?:number
    zindex_set_resistence?:boolean

    gravity:number
    radius:number
    zBaseScale:number
    zScaleAdd:number

    decays:{
        ground_speed:number
        ground_rotation:number
    }

    cook?:{
        allow_hand:boolean
        fuse_time?:number
        ground?:boolean
        impact?:boolean
    }
    throw_max_speed?:number

    frames:{
        world:FrameDef
    }
    collision_damage?:number

    speed_mod?:number

    rig_arms?:FistRig
    rig_image?:FrameTransform
    assets?:WeaponAssets
}&Definition
const GrenadeRig={
    position:v2(0.6,0.23),
    rotation:-0.5
}
export function Grenades_Default_Init(grenades:Definitions<GrenadeDef,{}>){
    grenades.insert(
        {
            idString:"frag_grenade",
            rank:ItemRank.E,

            explosion:"frag_grenade_explosion",

            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.7,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:true,
                fuse_time:6
            },
            throw_max_speed:15,
            frames:{
                world:{
                    image:"proj_frag"
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"smoke_grenade",
            rank:ItemRank.E,

            explosion:"smoke_grenade_explosion",

            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.7,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:4
            },
            throw_max_speed:17,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
            frames:{
                world:{
                    image:"proj_smoke"
                }
            },
            speed_mod:1,
        },
        {
            idString:"molotov",
            rank:ItemRank.D,

            explosion:"molotov_explosion",

            gravity:2,
            radius:0.25,
            zBaseScale:0.7,
            zScaleAdd:0.4,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                ground:true
            },
            throw_max_speed:10,
            frames:{
                world:{
                    image:"proj_molotov",
                    hotspot:v2(0.35,0.35)
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        //Mirv
        {
            idString:"mirv_grenade",
            rank:ItemRank.C,

            explosion:"mirv_grenade_explosion",

            gravity:2.5,
            radius:0.25,
            zBaseScale:0.8,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:true,
                fuse_time:6
            },
            throw_max_speed:15,
            frames:{
                world:{
                    image:"proj_mirv"
                }
            },
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"submirv_grenade",
            rank:ItemRank.E,

            explosion:"submirv_grenade_explosion",

            gravity:3,
            radius:0.1,
            zBaseScale:1,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:false,
                fuse_time:2
            },
            frames:{
                world:{
                    image:"proj_submirv"
                }
            },
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"blue_flare",
            rank:ItemRank.A,
            description:true,
            explosion:"blue_flare_explosion",
            call_airdrop:{
                delay:9
            },
            particles:{
                spawn_delay:6,
                tint:0x08b0ce,
                delay:0.1,
                spawn:v2(0.3,0),
                lifetime:{
                    min:2,
                    max:5
                },
                speed:{
                    min:0.1,
                    max:0.25
                },
                frame:{
                    image:"gas_particle",
                    scale:0.01
                }
            },
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.6,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:20
            },
            throw_max_speed:20,
            frames:{
                world:{
                    image:"proj_blue_flare"
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"red_flare",
            rank:ItemRank.A,
            description:true,
            explosion:"red_flare_explosion",
            call_airstrike:{
                bomb:{
                    def:"nuke",
                },
                delay:3,

            },
            particles:{
                spawn_delay:0.5,
                tint:0xca0819,
                delay:0.1,
                spawn:v2(0.3,0),
                lifetime:{
                    min:2,
                    max:5
                },
                speed:{
                    min:0.1,
                    max:0.25
                },
                frame:{
                    image:"gas_particle",
                    scale:0.01
                }
            },
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.6,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:4
            },
            throw_max_speed:20,
            frames:{
                world:{
                    image:"proj_red_flare"
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"yellow_flare",
            rank:ItemRank.A,
            description:true,
            explosion:"yellow_flare_explosion",
            call_airstrike:{
                delay:2,
                count:3,
                delay_gap:1,
                bomb:{
                    def:"mini_nuke",
                    count:10,
                    radius:7
                }
            },
            particles:{
                spawn_delay:0.5,
                tint:0xf6dc1b,
                delay:0.1,
                spawn:v2(0.3,0),
                lifetime:{
                    min:2,
                    max:5
                },
                speed:{
                    min:0.1,
                    max:0.25
                },
                frame:{
                    image:"gas_particle",
                    scale:0.01
                }
            },
            gravity:2,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.6,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:false,
                fuse_time:3
            },
            throw_max_speed:20,
            frames:{
                world:{
                    image:"proj_yellow_flare"
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"m79_grenade",
            rank:ItemRank.E,

            explosion:"m79_grenade_explosion",

            gravity:1.6,
            radius:0.25,
            zBaseScale:0.4,
            zScaleAdd:0.7,
            decays:{
                ground_rotation:2,
                ground_speed:2,
            },
            cook:{
                allow_hand:true,
                ground:true,
                impact:true,
            },
            throw_max_speed:11,
            frames:{
                world:{
                    image:"proj_m79"
                }
            },
            speed_mod:1,
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
        },
        {
            idString:"nuke",
            gravity:0.2,
            radius:0.6,
            zBaseScale:1,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:false,
                ground:true,
            },
            explosion:"nuke_explosion",
            push_force_resistence:0,
            zindex_set_resistence:true,
            frames:{
                world:{
                    image:"proj_nuke"
                }
            },
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
            rank:ItemRank.S
        },
        {
            idString:"mini_nuke",
            gravity:1.1,
            radius:0.6,
            zBaseScale:1,
            zScaleAdd:1,
            decays:{
                ground_rotation:2,
                ground_speed:2
            },
            cook:{
                allow_hand:false,
                ground:true,
            },
            explosion:"mini_nuke_explosion",
            zindex_set_resistence:true,
            frames:{
                world:{
                    image:"proj_mini_nuke"
                }
            },
            rig_arms:DefaultFistRig,
            rig_image:GrenadeRig,
            rank:ItemRank.A,
            push_force_resistence:0,
        },
    )
}