import { DeepPartial, Definition, Definitions, mergeDeep, v2, Vec2 } from "../../../engine/core.ts";
import { WeaponsArmRig,WeaponsRig, ItemRank, tracers, FistRig, WeaponRig, WeaponAssets} from "../../others/item.ts";
import { BulletDef, BulletReflection, InventoryItemType } from "../utils.ts";
export type GunDef={
    bullet?:{
        def:BulletDef
        count?:number
    }
    projectile?:{
        def:string
        count?:number
        angular_speed?:number
        speed?:number
    }
    alt_func?:GunAltFunc
    mana_consume?:number
    ammoSpawnAmount?:number
    ammoSpawn?:string
    fireDelay:number
    switchDelay?:number
    spread?:number
    lenght:number
    jitterRadius?:number
    fireMode?:FireMode
    burst?:{
        delay:number
        sequence:number
    }
    speed_mod?:number
    ammoType:string
    class:GunClasses
    rank:ItemRank
    muzzleFlash?:MuzzleFlash
    reload?:{
        capacity:number
        delay:number
        reload_count?:number
        extended_capacity?:number
        reload_alt?:{
            delay:number
            reload_count?:number
        }
        ammo_consume?:number
    }
    recoil?:{
        duration:number
        speed:number
    }
    arms?:FistRig
    image?:WeaponRig
    assets?:WeaponAssets&{
        reload_sound?:string
        reload_sound_alt?:string
    }
    case?:{
        position:Vec2
        at_begin?:boolean
        frame?:string
        sound?:string
    }
    gasParticles?:GasParticle
    dual?:DeepPartial<GunDef>&DualAdditional
    item_type?:InventoryItemType.gun
    supresed?:boolean
}&({
    dual_from?:undefined
}|{
    dual_from:string
    dual_offset:number
})&Definition
export enum FireMode{
    Auto,
    Single,
    Burst
}
export interface DualAdditional{dual_offset:number}
export interface GasParticle{
    count:number
    size:{
        min:number
        max:number
    }
    speed:{
        min:number
        max:number
    }
    life_time:number
    direction_variation:number
}
export enum GunClasses{
    Pistol,
    Shotgun,
    Sniper,
    Assault,
    SMG,
    DMR,
    LMG,
    Miscellaneous,
    Magic,
}
export interface MuzzleFlash{
    sprite:string
}
export const MuzzleFlash={
    normal:{
        sprite:"muzzle_flash_1",
    }
}
export interface GunAltFunc{
    type:0// Shot Projectile
    projectile:string
    speed:number
}
export const GunsConstructors={
    extends(gun:GunDef,variant:DeepPartial<GunDef>):GunDef{
        return mergeDeep({}as GunDef,gun,variant)as GunDef
    },
}

export const GasParticles={
    shotgun:{
        count:7,
        size:{
            min:0.5,
            max:1.2
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.9,
        direction_variation:0.4
    } satisfies GasParticle,
    sniper:{
        count:8,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    dmr:{
        count:3,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    automatic:{
        count:1, 
        size:{
            min:0.8,
            max:1
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle,
    pistols:{
        count:2,
        size:{
            min:0.7,
            max:0.8
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle
}
export function Guns_Default_Init(guns:Definitions<GunDef,{}>){
    guns.insert(
        {
            idString:"m9",
            fireDelay:0.2,
            switchDelay:0.5,
            spread:0.7,
            lenght:0.8,
            ammoType:"9mm",
            fireMode:FireMode.Single,
            class:GunClasses.Pistol,
            rank:ItemRank.E,
            ammoSpawnAmount:45,
            bullet:{
                def:{
                    damage:11,
                    range:90,
                    falloff:0.8,
                    speed:40,
                    obstacleMult:1.2,
                    tracer:tracers.small
                }
            },
            reload:{
                delay:2,
                capacity:15,
                extended_capacity:20,
            },
            recoil:{
                duration:0.34,
                speed:0.8
            },
            speed_mod:0.98,
            arms:WeaponsArmRig[3],
            assets:{
                world:"weapon_small_world",
                world_tint:0xaaaaaa
            },
            gasParticles:GasParticles.pistols,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            image:WeaponsRig[0],
            dual:{
                dual_offset:0.2,
                fireDelay:0.15,
                reload:{
                    capacity:30,
                    delay:3
                }
            }
        },
        {
            idString:"yellow_laser_gun",
            fireDelay:0.2,
            switchDelay:0.5,
            spread:0.7,
            lenght:0.8,
            ammoType:"9mm",
            fireMode:FireMode.Single,
            class:GunClasses.Pistol,
            rank:ItemRank.E,
            ammoSpawnAmount:25,
            bullet:{
                def:{
                    damage:11,
                    range:90,
                    falloff:0.8,
                    speed:40,
                    obstacleMult:1.2,
                    tracer:tracers.small,
                    reflection:BulletReflection.All
                }
            },
            reload:{
                delay:2.5,
                capacity:15,
                extended_capacity:20,
            },
            recoil:{
                duration:0.34,
                speed:0.8
            },
            speed_mod:0.98,
            arms:WeaponsArmRig[3],
            gasParticles:GasParticles.pistols,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.5,0.1)
            },
            image:WeaponsRig[0],
            assets:{
                world:"weapon_small_world",
                world_tint:0xaaaaaa
            },
            dual:{
                dual_offset:0.2,
                fireDelay:0.15,
                reload:{
                    capacity:30,
                    delay:4
                }
            }
        },
        {
            idString:"pfeifer_zeliska",
            fireDelay:1.4,
            switchDelay:0.1,
            spread:0.7,
            lenght:0.8,
            ammoType:"308sub",
            fireMode:FireMode.Single,
            class:GunClasses.Pistol,
            rank:ItemRank.S,
            ammoSpawnAmount:25,
            bullet:{
                def:{
                    damage:55,
                    range:130,
                    falloff:0.7,
                    speed:50,
                    obstacleMult:1.7,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:3.2,
                capacity:5,
                extended_capacity:7,
            },
            recoil:{
                duration:1.45,
                speed:0.25
            },
            speed_mod:0.9,
            arms:WeaponsArmRig[3],
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.5,0.1)
            },
            image:WeaponsRig[0],
            dual:{
                dual_offset:0.2,
                fireDelay:0.8,
                reload:{
                    capacity:10,
                    delay:6
                }
            }
        },
        {
            idString:"ak47",
            fireDelay:0.1,
            switchDelay:0.6,
            spread:4,
            lenght:0.9,
            ammoType:"762mm",
            ammoSpawnAmount:90,
            class:GunClasses.Assault,
            rank:ItemRank.C,
            bullet:{
                def:{
                    damage:8,
                    range:102,
                    speed:41,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2.5,
                capacity:30,
                extended_capacity:45,
            },
            recoil:{
                duration:0.12,
                speed:0.75
            },
            speed_mod:0.97,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"ar15",
            fireDelay:0.05,
            switchDelay:0.9,
            spread:5,
            lenght:0.9,
            ammoType:"556mm",
            ammoSpawnAmount:90,
            class:GunClasses.Assault,
            rank:ItemRank.C,
            bullet:{
                def:{
                    damage:8,
                    range:102,
                    falloff:0.7,
                    speed:41,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2.5,
                capacity:30,
                extended_capacity:45,
            },
            recoil:{
                duration:0.14,
                speed:0.75
            },
            muzzleFlash:MuzzleFlash.normal,
            speed_mod:0.95,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"famas",
            fireDelay:0.4,
            switchDelay:0.7,
            fireMode:FireMode.Burst,
            burst:{
                delay:0.1,
                sequence:3
            },
            spread:1.5,
            lenght:0.9,
            ammoType:"556mm",
            ammoSpawnAmount:90,
            class:GunClasses.Assault,
            rank:ItemRank.B,
            bullet:{
                def:{
                    damage:10,
                    range:102,
                    falloff:0.7,
                    speed:41,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2.5,
                capacity:25,
                extended_capacity:35,
            },
            recoil:{
                duration:0.4,
                speed:0.5
            },
            speed_mod:0.95,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"mp5",
            fireDelay:0.09,
            switchDelay:0.7,
            spread:2,
            lenght:0.87,
            ammoType:"9mm",
            ammoSpawnAmount:96,
            class:GunClasses.Assault,
            rank:ItemRank.D,
            bullet:{
                def:{
                    damage:7,
                    range:95,
                    falloff:0.9,
                    speed:37,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2,
                capacity:32,
                extended_capacity:48,
            },
            recoil:{
                duration:0.11,
                speed:0.8
            },
            speed_mod:1,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            image:{
                position:v2.new(0.5,0.0),
                rotation:0
            },
        },
        {
            idString:"m1a1",
            fireDelay:0.1,
            switchDelay:0.9,
            spread:6,
            lenght:0.9,
            ammoType:"45acp",
            ammoSpawnAmount:80,
            class:GunClasses.Assault,
            rank:ItemRank.B,
            bullet:{
                def:{
                    damage:7.5,
                    range:102,
                    falloff:0.7,
                    speed:41,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2.5,
                capacity:40,
                extended_capacity:50,
            },
            recoil:{
                duration:0.14,
                speed:0.6
            },
            muzzleFlash:MuzzleFlash.normal,
            speed_mod:0.95,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"micro_uzi",
            fireDelay:0.03,
            switchDelay:0.7,
            spread:9,
            lenght:0.7,
            ammoType:"9mm",
            ammoSpawnAmount:96,
            class:GunClasses.SMG,
            rank:ItemRank.D,
            bullet:{
                def:{
                    damage:5,
                    range:38,
                    speed:29,
                    falloff:0.7,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:1.7,
                capacity:32,
                extended_capacity:48,
            },
            recoil:{
                duration:0.07,
                speed:0.77
            },
            speed_mod:1,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_small_world",
                world_tint:0x12111f
            },
            image:{
                position:v2.new(0.6,0.0),
                scale:1.2,
                rotation:0
            },
        },
        {
            idString:"vector",
            fireDelay:0.03,
            switchDelay:0.7,
            spread:2,
            lenght:0.9,
            ammoType:"9mm",
            ammoSpawnAmount:99,
            class:GunClasses.SMG,
            rank:ItemRank.A,
            bullet:{
                def:{
                    damage:5,
                    range:38,
                    speed:29,
                    falloff:0.7,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:1.7,
                capacity:33,
                extended_capacity:44,
            },
            recoil:{
                duration:0.07,
                speed:0.77
            },
            speed_mod:1,
            gasParticles:GasParticles.pistols,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"kar98k",
            fireDelay:1.2,
            switchDelay:0.1,
            spread:0.3,
            lenght:0.9,
            ammoType:"762mm",
            ammoSpawnAmount:20,
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.A,
            bullet:{
                def:{
                    damage:42,
                    range:115,
                    falloff:0.8,
                    criticalMult:1.1,
                    speed:53,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:0.9,
                capacity:5,
                extended_capacity:7,
                reload_count:1,
                reload_alt:{
                    delay:2.7,
                },
            },
            recoil:{
                duration:1.25,
                speed:0.4
            },
            speed_mod:0.95,
            gasParticles:GasParticles.sniper,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.6,0.3)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f,
                cycle_sound:true,
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"awp",
            fireDelay:1.3,
            switchDelay:0.1,
            spread:0.3,
            lenght:0.9,
            ammoType:"762mm",
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.A,
            ammoSpawnAmount:30,
            bullet:{
                def:{
                    damage:45,
                    range:120,
                    falloff:0.7,
                    speed:56,
                    criticalMult:1.1,
                    tracer:tracers.xl,
                    obstacleMult:1.5,
                }
            },
            reload:{
                delay:2.7,
                capacity:8,
                extended_capacity:10,
            },
            recoil:{
                duration:1.37,
                speed:0.65
            },
            speed_mod:0.9,
            arms:WeaponsArmRig[1],
            image:{
                position:v2.new(0.6,0.04),
                rotation:0
            },
            gasParticles:GasParticles.sniper,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.6,0.3)
            },
            assets:{
                cycle_sound:true,
            },
        },
        {
            idString:"awms",
            fireDelay:1.5,
            switchDelay:0.1,
            spread:0.6,
            lenght:1,
            ammoType:"308sub",
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.S,
            ammoSpawnAmount:25,
            bullet:{
                def:{
                    damage:99,
                    range:135,
                    falloff:0.7,
                    speed:45,
                    criticalMult:1.1,
                    obstacleMult:2,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:3.9,
                capacity:5,
                extended_capacity:6,
            },
            recoil:{
                duration:1.45,
                speed:0.25
            },
            speed_mod:0.9,
            arms:WeaponsArmRig[1],
            image:{
                position:v2.new(0.6,0.04),
                rotation:0
            },
            gasParticles:GasParticles.sniper,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.6,0.3)
            },
            assets:{
                cycle_sound:true,
            },
            supresed:true
        },
        {
            idString:"blr81",
            fireDelay:0.9,
            switchDelay:0.1,
            spread:0.3,
            lenght:0.9,
            ammoType:"556mm",
            ammoSpawnAmount:12,
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.B,
            bullet:{
                def:{
                    damage:37,
                    range:110,
                    falloff:0.7,
                    criticalMult:1.1,
                    speed:45,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:2.5,
                capacity:3,
                extended_capacity:4,
            },
            recoil:{
                duration:1,
                speed:0.7
            },
            speed_mod:0.95,
            gasParticles:GasParticles.sniper,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.6,0.3)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f,
                cycle_sound:true,
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"model94",
            fireDelay:0.9,
            switchDelay:0.1,
            spread:0.5,
            lenght:0.9,
            ammoType:"45acp",
            ammoSpawnAmount:16,
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.B,
            bullet:{
                def:{
                    damage:34,
                    range:105,
                    falloff:0.7,
                    criticalMult:1.1,
                    speed:45,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:0.6,
                capacity:8,
                extended_capacity:13,
                reload_count:1,
            },
            recoil:{
                duration:1,
                speed:0.7
            },
            speed_mod:0.95,
            gasParticles:GasParticles.sniper,
            muzzleFlash:MuzzleFlash.normal,
            case:{
                position:v2.new(0.6,0.3)
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f,
                cycle_sound:true,
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"m870",
            fireDelay:1.1,
            switchDelay:0.1,
            spread:4,
            lenght:0.9,
            ammoType:"12g",
            ammoSpawnAmount:10,
            jitterRadius:0.5,
            fireMode:FireMode.Single,
            class:GunClasses.Shotgun,
            rank:ItemRank.C,
            bullet:{
                def:{
                    damage:7,
                    speed:22,
                    range:25,
                    falloff:0.8,
                    criticalMult:1.2,
                    tracer:tracers.small
                },
                count:9
            },
            reload:{
                delay:0.8,
                capacity:5,
                extended_capacity:10,
                reload_count:1,
            },
            recoil:{
                duration:1,
                speed:0.55
            },
            speed_mod:0.95,
            gasParticles:GasParticles.shotgun,
            arms:WeaponsArmRig[0],
            image:{
                position:v2.new(0.5,0),
                rotation:0
            },
            case:{
                position:v2.new(0.8,0.3)
            },
            assets:{
                cycle_sound:true,
            },
            muzzleFlash:MuzzleFlash.normal
        },
        {
            idString:"spas12",
            fireDelay:1.1,
            switchDelay:0.1,
            spread:2.8,
            lenght:1,
            ammoType:"12g",
            ammoSpawnAmount:16,
            jitterRadius:0.2,
            class:GunClasses.Shotgun,
            rank:ItemRank.B,
            fireMode:FireMode.Single,
            bullet:{
                def:{
                    damage:5.25,
                    speed:25,
                    range:45,
                    criticalMult:1.1,
                    falloff:0.65,
                    tracer:tracers.small
                },
                count:9
            },
            reload:{
                delay:0.6,
                capacity:8,
                extended_capacity:11,
                reload_count:1,
            },
            recoil:{
                duration:1,
                speed:0.6
            },
            speed_mod:0.95,
            gasParticles:GasParticles.shotgun,
            arms:WeaponsArmRig[0],
            image:{
                position:v2.new(0.4,0.01),
                rotation:0
            },
            case:{
                position:v2.new(0.6,0.3)
            },
            assets:{
                cycle_sound:true,
            },
            muzzleFlash:MuzzleFlash.normal,
        },
        {
            idString:"hp18",
            fireDelay:0.3,
            switchDelay:0.5,
            spread:7,
            lenght:0.9,
            ammoType:"12g",
            ammoSpawnAmount:15,
            jitterRadius:0.2,
            class:GunClasses.Shotgun,
            rank:ItemRank.D,
            fireMode:FireMode.Auto,
            bullet:{
                def:{
                    damage:4,
                    speed:22,
                    falloff:0.7,
                    range:26,
                    criticalMult:1.2,
                    tracer:tracers.tiny
                },
                count:11
            },
            reload:{
                delay:0.8,
                capacity:5,
                extended_capacity:6,
                reload_count:1,
            },
            recoil:{
                duration:0.4,
                speed:0.75
            },
            speed_mod:1,
            gasParticles:GasParticles.shotgun,
            case:{
                position:v2.new(0.8,0.3)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"sr25",
            fireDelay:0.3,
            fireMode:FireMode.Single,
            switchDelay:0.6,
            spread:1,
            lenght:0.9,
            ammoType:"762mm",
            ammoSpawnAmount:60,
            class:GunClasses.DMR,
            rank:ItemRank.A,
            bullet:{
                def:{
                    damage:23,
                    falloff:0.7,
                    range:100,
                    speed:47,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:2.5,
                capacity:20,
                extended_capacity:25,
            },
            recoil:{
                duration:0.4,
                speed:0.75
            },
            speed_mod:0.97,
            gasParticles:GasParticles.dmr,
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"pkp",
            fireDelay:0.1,
            switchDelay:0.6,
            spread:5.5,
            lenght:0.9,
            ammoType:"762mm",
            ammoSpawnAmount:200,
            class:GunClasses.LMG,
            rank:ItemRank.S,
            bullet:{
                def:{
                    damage:14,
                    obstacleMult:1.5,
                    range:100,
                    speed:47,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:5,
                capacity:200,
                extended_capacity:250,
            },
            recoil:{
                duration:0.12,
                speed:0.4
            },
            speed_mod:0.8,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.8,0.3)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"rpg7",
            fireDelay:1,
            switchDelay:0.1,
            spread:0.2,
            lenght:1,
            ammoType:"explosive_ammo",
            fireMode:FireMode.Single,
            class:GunClasses.Miscellaneous,
            rank:ItemRank.S,
            ammoSpawnAmount:11,
            gasParticles:{
                count:10,
                life_time:1.2,
                speed:{
                    min:1,
                    max:2
                },
                direction_variation:0.4,
                size:{
                    min:0.6,
                    max:2,
                }
            },
            bullet:{
                def:{
                    damage:5,
                    range:80,
                    falloff:0.5,
                    on_hit_explosion:"rocket_explosion",
                    speed:22,
                    criticalMult:1.2,
                    obstacleMult:3,
                    tracer:{
                        height:2,
                        width:2,
                        particles:{
                            frame:1
                        },
                        proj:{
                            img:2,
                            width:4,
                            height:4,
                        },
                    }
                }
            },
            reload:{
                delay:2,
                capacity:1,
            },
            recoil:{
                duration:1.45,
                speed:0.25
            },
            speed_mod:0.5,
        },
        {
            idString:"m2_2",
            fireDelay:0.07,
            switchDelay:1,
            spread:3,
            lenght:1,
            ammoType:"gasoline",
            fireMode:FireMode.Auto,
            class:GunClasses.Miscellaneous,
            rank:ItemRank.A,
            ammoSpawnAmount:15.2,
            bullet:{
                def:{
                    damage:1,
                    effect:[{
                        id:"fire",
                        time:5
                    }],
                    range:28,
                    falloff:0.4,
                    speed:30,
                    criticalMult:4,
                    obstacleMult:5,
                    reflection:BulletReflection.None,
                    tracer:{
                        height:6,
                        width:6,
                        proj:{
                            img:0,
                            height:1,
                            width:1
                        },
                    },
                },
                count:3
            },
            reload:{
                delay:5,
                capacity:7.6,
                ammo_consume:0.03,
            },
            recoil:{
                duration:1.45,
                speed:0.46
            },
            speed_mod:0.6,
        },
        /*{
            idString:"bomb_staff",
            fireDelay:0.9,
            spread:3,
            lenght:0.7,
            size:3.8,
            ammoType:"mana",
            ammoSpawnAmount:2,
            ammoSpawn:"purple_pills",
            mana_consume:20,
            class:GunClasses.Magic,
            rank:ItemRank.S,
            fireMode:FireMode.Single,
            projectile:{
                def:"bomb_staff_projectile",
                angular_speed:0,
                speed:11
            },
            recoil:{
                duration:1,
                speed:0.6
            },
            speed_mod:0.97,
        },
        {
            idString:"fireball_staff",
            fireDelay:0.5,
            spread:4,
            lenght:0.7,
            size:3.7,
            ammoType:"mana",
            ammoSpawnAmount:2,
            ammoSpawn:"purple_pills",
            mana_consume:5,
            class:GunClasses.Magic,
            rank:ItemRank.A,
            fireMode:FireMode.Auto,
            projectile:{
                def:"fireball_projectile",
                angular_speed:0,
                speed:14
            },
            recoil:{
                duration:0.6,
                speed:0.8
            },
            speed_mod:0.97,
        },*/
    )
}
/*Guns.insert(
    GunsConstructors.create_variant(Guns.getFromString("ak47"),ItemRank.D,{
        damage_increment:-0.5
    })
)*/