import { DeepPartial, Definition, Definitions, mergeDeep, Random1, v2, Vec2 } from "../../../engine/core.ts";
import { WeaponsArmRig,WeaponsRig, ItemRank, tracers, FistRig, WeaponRig, WeaponAssets} from "../../others/item.ts";
import { BulletDef, BulletReflection, InventoryItemType } from "../utils.ts";
export type GunDef={
    bullet?:{
        def:BulletDef
        count?:number
    }
    projectile?:{
        def:string
        count?:number
        angular_speed?:number
        speed?:number
    }
    synsed_particle?:{
        def:string
        count?:number
        speed?:Random1
    }
    alt_func?:GunAltFunc
    mana_consume?:number
    ammoSpawnAmount?:number
    ammoSpawn?:string
    fireDelay:number
    switchDelay?:number
    spread?:number
    lenght:number
    barrel_offset?:number
    jitterRadius?:number
    fireMode?:FireMode
    burst?:{
        delay:number
        sequence:number
    }
    speed_mod?:number
    ammoType:string
    class:GunClasses
    rank:ItemRank
    muzzleFlash?:MuzzleFlash
    reload?:{
        capacity:number
        delay:number
        reload_count?:number
        extended_capacity?:number
        reload_alt?:{
            delay:number
            reload_count?:number
        }
        ammo_consume?:number
    }
    recoil?:{
        duration:number
        speed:number
    }
    arms?:FistRig
    image?:WeaponRig
    assets?:WeaponAssets&{
        reload_sound?:string
        reload_sound_alt?:string
    }
    case?:{
        position:Vec2
        at_begin?:boolean
        frame?:string
        sound?:string
    }
    gasParticles?:GasParticle
    dual?:DeepPartial<GunDef>&DualAdditional
    item_type?:InventoryItemType.gun
    supresed?:boolean
}&({
    dual_from?:undefined
}|{
    dual_from:string
    dual_offset:number
})&Definition
export enum FireMode{
    Auto,
    Single,
    Burst
}
export interface DualAdditional{dual_offset:number}
export interface GasParticle{
    count:number
    size:{
        min:number
        max:number
    }
    speed:{
        min:number
        max:number
    }
    life_time:number
    direction_variation:number
}
export enum GunClasses{
    Pistol,
    Shotgun,
    Sniper,
    Assault,
    SMG,
    DMR,
    LMG,
    Miscellaneous,
    Magic,
}
export interface MuzzleFlash{
    sprite:string
}
export const MuzzleFlash={
    normal:{
        sprite:"muzzle_flash_1",
    }
}
export interface GunAltFunc{
    type:0// Shot Projectile
    projectile:string
    speed:number
}
export const GunsConstructors={
    extends(gun:GunDef,variant:DeepPartial<GunDef>):GunDef{
        return mergeDeep({}as GunDef,gun,variant)as GunDef
    },
}

export const GasParticles={
    shotgun:{
        count:7,
        size:{
            min:0.5,
            max:1.2
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.9,
        direction_variation:0.4
    } satisfies GasParticle,
    sniper:{
        count:8,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    dmr:{
        count:3,
        size:{
            min:0.6,
            max:1.4
        },
        speed:{
            min:1,
            max:2
        },
        life_time:1.1,
        direction_variation:0.43
    } satisfies GasParticle,
    automatic:{
        count:1, 
        size:{
            min:0.8,
            max:1
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle,
    pistols:{
        count:2,
        size:{
            min:0.7,
            max:0.8
        },
        speed:{
            min:1,
            max:2
        },
        life_time:0.7,
        direction_variation:0.2
    } satisfies GasParticle
}

export const bullets_factory={
    /*pistol_9mm(extend:DeepPartial<BulletDef>={}):BulletDef{
        return mergeDeep({
            damage:11,
            range:100,
            falloff:0.8,
            speed:40,
            obstacleMult:1.2,
            tracer:tracers.small
        },extend)
    },*/
}
export const guns_factory={
    simple(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            ammoType:ammo,
            class:GunClasses.Pistol,
            rank:ItemRank.E,
            fireDelay:1,
            lenght:0.8,
        },extend)
    },
    pistol(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,

            fireDelay:1,
            switchDelay:0.7,
            lenght:0.8,
            speed_mod:0.98,

            ammoType:ammo,
            class:GunClasses.Pistol,
            rank:ItemRank.E,

            arms:WeaponsArmRig[3],
            assets:{
                world:"weapon_small_world",
                world_tint:0xaaaaaa
            },
            gasParticles:GasParticles.pistols,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            image:WeaponsRig[0],
        },extend??{})
    },
    assault(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            fireDelay:0.1,
            switchDelay:0.7,
            lenght:0.9,
            speed_mod:0.97,

            ammoType:ammo,
            class:GunClasses.Assault,
            rank:ItemRank.C,

            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },extend??{})
    },
    smg(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            fireDelay:0.1,
            switchDelay:0.5,
            lenght:0.9,
            speed_mod:0.98,

            ammoType:ammo,
            class:GunClasses.SMG,
            rank:ItemRank.C,

            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },extend??{})
    },
    dmr(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            fireDelay:0.1,
            switchDelay:0.3,
            lenght:0.9,
            speed_mod:0.95,

            ammoType:ammo,
            fireMode:FireMode.Single,
            class:GunClasses.DMR,
            rank:ItemRank.A,

            gasParticles:GasParticles.dmr,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0,
            },
        },extend??{})
    },
    sniper(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            fireDelay:0.1,
            switchDelay:0.15,
            lenght:0.9,
            speed_mod:0.95,

            ammoType:ammo,
            fireMode:FireMode.Single,
            class:GunClasses.Sniper,
            rank:ItemRank.C,

            gasParticles:GasParticles.sniper,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0,
            },
        },extend??{})
    },
    shotgun(id:string,ammo:string,extend:DeepPartial<GunDef>={}):GunDef{
        return mergeDeep({
            idString:id,
            fireDelay:0.1,
            switchDelay:0.2,
            lenght:0.9,
            speed_mod:0.95,

            ammoType:ammo,
            class:GunClasses.Shotgun,
            rank:ItemRank.C,

            gasParticles:GasParticles.shotgun,
            case:{
                position:v2.new(0.5,0.1)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.0),
                rotation:0,
            },
        },extend??{})
    },
}
export function Guns_Default_Init(guns:Definitions<GunDef,{}>){
    guns.insert(
        guns_factory.pistol("m9","9mm",{
            fireDelay:0.15,
            fireMode:FireMode.Single,
            spread:0.7,

            ammoSpawnAmount:45,

            bullet:{
                def:{
                    damage:11,
                    range:110,
                    falloff:0.8,
                    speed:45,
                    obstacleMult:1.2,
                    tracer:tracers.small
                }
            },
            recoil:{
                duration:0.2,
                speed:0.8
            },
            reload:{
                delay:2,
                capacity:15,
                extended_capacity:20,
            },
            dual:{
                ammoSpawnAmount:90,
                dual_offset:0.2,
                fireDelay:0.1,
                reload:{
                    capacity:30,
                    delay:3
                }
            },
        }),
        guns_factory.pistol("taurustx","22lr",{
            fireDelay:0.4,
            fireMode:FireMode.Burst,
            burst:{
                delay:0.05,
                sequence:4
            },
            spread:2,
            ammoSpawnAmount:60,

            bullet:{
                def:{
                    damage:4.5,
                    range:80,
                    falloff:0.6,
                    speed:35,
                    tracer:tracers.tiny
                }
            },
            recoil:{
                duration:0.2,
                speed:0.8
            },
            reload:{
                delay:2,
                capacity:20,
                extended_capacity:40,
            },
            dual:{
                fireDelay:0.2,
                spread:3.5,
                dual_offset:0.2,

                ammoSpawnAmount:120,
                burst:{
                    delay:0.06,
                    sequence:8
                },
                reload:{
                    capacity:40,
                    extended_capacity:80,
                    delay:3
                }
            },
        }),
        guns_factory.pistol("colt1873","45acp",{
            fireDelay:0.3,
            switchDelay:0.3,
            fireMode:FireMode.Single,
            rank:ItemRank.E,
            spread:1,

            ammoSpawnAmount:25,

            bullet:{
                def:{
                    damage:16,
                    range:110,
                    falloff:0.8,
                    speed:47,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:1,
                speed:0.75
            },
            reload:{
                delay:3,
                capacity:5,
                extended_capacity:10,
            },
            dual:{
                ammoSpawnAmount:50,
                dual_offset:0.2,
                fireDelay:0.2,
                reload:{
                    capacity:10,
                    extended_capacity:20,
                    delay:5
                }
            },
        }),
        guns_factory.pistol("yellow_laser_pistol","9mm",{
            fireDelay:0.15,
            fireMode:FireMode.Single,
            spread:0.7,

            ammoSpawnAmount:45,

            bullet:{
                def:{
                    damage:11,
                    range:110,
                    falloff:0.8,
                    speed:45,
                    obstacleMult:1.2,
                    reflection:BulletReflection.All,
                    tracer:tracers.small
                }
            },
            recoil:{
                duration:0.2,
                speed:0.8
            },
            reload:{
                delay:2,
                capacity:15,
                extended_capacity:20,
            },
            dual:{
                ammoSpawnAmount:90,
                dual_offset:0.2,
                fireDelay:0.1,
                reload:{
                    capacity:30,
                    delay:3
                }
            },
        }),
        guns_factory.pistol("pfeifer_zeliska","308sub",{
            fireDelay:1.4,
            switchDelay:0.1,
            spread:0.7,

            ammoSpawnAmount:25,
            fireMode:FireMode.Single,
            rank:ItemRank.S,

            speed_mod:0.95,
            bullet:{
                def:{
                    damage:55,
                    range:130,
                    falloff:0.7,
                    speed:50,
                    obstacleMult:1.7,
                    tracer:tracers.large
                }
            },
            reload:{
                delay:3.2,
                capacity:5,
                extended_capacity:7,
            },
            recoil:{
                duration:1.45,
                speed:0.25
            },
            dual:{
                dual_offset:0.2,
                fireDelay:0.8,
                reload:{
                    capacity:10,
                    delay:6
                }
            }
        }),
        guns_factory.assault("ak47","762mm",{
            fireDelay:0.1,
            spread:4,

            ammoSpawnAmount:90,
            rank:ItemRank.C,

            reload:{
                delay:2.5,
                capacity:30,
                extended_capacity:45,
            },
            recoil:{
                duration:0.12,
                speed:0.75
            },
            bullet:{
                def:{
                    damage:8,
                    range:110,
                    speed:45,
                    falloff:0.75,
                    tracer:tracers.medium
                }
            },
        }),
        guns_factory.assault("ar15","556mm",{
            fireDelay:0.05,
            spread:5,

            ammoSpawnAmount:90,
            rank:ItemRank.C,

            reload:{
                delay:2.5,
                capacity:30,
                extended_capacity:45,
            },
            recoil:{
                duration:0.1,
                speed:0.75
            },
            bullet:{
                def:{
                    damage:8,
                    range:110,
                    speed:45,
                    falloff:0.75,
                    tracer:tracers.medium
                }
            },
        }),
        guns_factory.assault("mp5","9mm",{
            fireDelay:0.1,
            spread:2,

            ammoSpawnAmount:96,
            rank:ItemRank.D,

            bullet:{
                def:{
                    damage:7,
                    range:90,
                    falloff:0.75,
                    speed:42,
                    tracer:tracers.medium
                }
            },
            reload:{
                delay:2,
                capacity:32,
                extended_capacity:48,
            },
            recoil:{
                duration:0.15,
                speed:0.8
            },
        }),
        guns_factory.assault("m1a1","45acp",{
            fireDelay:0.1,
            spread:6,

            ammoSpawnAmount:90,
            rank:ItemRank.B,

            reload:{
                delay:2.5,
                capacity:40,
                extended_capacity:50,
            },
            recoil:{
                duration:0.12,
                speed:0.75
            },
            bullet:{
                def:{
                    damage:7.5,
                    range:110,
                    speed:45,
                    falloff:0.75,
                    tracer:tracers.medium
                }
            },
        }),
        guns_factory.assault("famas","556mm",{
            fireDelay:0.4,
            spread:1.5,
            fireMode:FireMode.Burst,
            burst:{
                delay:0.1,
                sequence:3
            },

            ammoSpawnAmount:75,
            rank:ItemRank.B,

            reload:{
                delay:2.5,
                capacity:25,
                extended_capacity:30,
            },
            recoil:{
                duration:0.4,
                speed:0.75
            },
            bullet:{
                def:{
                    damage:9,
                    range:110,
                    speed:45,
                    falloff:0.75,
                    tracer:tracers.medium
                }
            },
        }),
        guns_factory.smg("micro_uzi","9mm",{
            fireDelay:0.03,
            spread:9,

            ammoSpawnAmount:96,
            rank:ItemRank.D,

            reload:{
                delay:1.7,
                capacity:32,
                extended_capacity:48,
            },
            recoil:{
                duration:0.07,
                speed:0.77
            },
            bullet:{
                def:{
                    damage:5,
                    range:45,
                    speed:30,
                    falloff:0.7,
                    criticalMult:1.2,
                    tracer:tracers.small
                }
            },
        }),
        guns_factory.smg("vector","9mm",{
            fireDelay:0.03,
            spread:2,

            ammoSpawnAmount:96,
            rank:ItemRank.D,

            reload:{
                delay:1.7,
                capacity:33,
                extended_capacity:44,
            },
            recoil:{
                duration:0.07,
                speed:0.77
            },
            bullet:{
                def:{
                    damage:5,
                    range:45,
                    speed:30,
                    falloff:0.7,
                    criticalMult:1.2,
                    tracer:tracers.small
                }
            },
        }),
        guns_factory.sniper("kar98k","762mm",{
            fireDelay:1.2,
            spread:0.3,

            ammoSpawnAmount:20,
            rank:ItemRank.A,

            reload:{
                delay:0.9,
                capacity:5,
                extended_capacity:7,
                reload_count:1,
                reload_alt:{
                    delay:2.7,
                },
            },
            bullet:{
                def:{
                    damage:42,
                    range:125,
                    falloff:0.75,
                    criticalMult:1.1,
                    obstacleMult:1.25,
                    speed:55,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:1.25,
                speed:0.5
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.sniper("awp","762mm",{
            fireDelay:1.3,
            spread:0.3,

            ammoSpawnAmount:32,
            rank:ItemRank.A,

            reload:{
                delay:2.7,
                capacity:8,
                extended_capacity:10,
            },
            bullet:{
                def:{
                    damage:45,
                    range:130,
                    falloff:0.75,
                    criticalMult:1.1,
                    obstacleMult:1.25,
                    speed:60,
                    tracer:tracers.xl
                }
            },
            recoil:{
                duration:1.35,
                speed:0.6
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.sniper("awms","308sub",{
            fireDelay:1.4,
            spread:0.5,

            ammoSpawnAmount:25,
            rank:ItemRank.S,

            reload:{
                delay:3.9,
                capacity:5,
                extended_capacity:6,
            },
            bullet:{
                def:{
                    damage:105,
                    range:140,
                    falloff:0.7,
                    speed:50,
                    criticalMult:1.1,
                    obstacleMult:2,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:1.45,
                speed:0.3
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.sniper("blr81","556mm",{
            fireDelay:0.8,
            spread:0.3,

            ammoSpawnAmount:12,
            rank:ItemRank.B,

            reload:{
                delay:2.5,
                capacity:3,
                extended_capacity:5
            },
            bullet:{
                def:{
                    damage:40,
                    range:125,
                    falloff:0.75,
                    obstacleMult:1.25,
                    criticalMult:1.1,
                    speed:50,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:0.9,
                speed:0.6
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.sniper("model94","45acp",{
            fireDelay:0.8,
            spread:0.5,

            ammoSpawnAmount:12,
            rank:ItemRank.B,

            reload:{
                delay:0.6,
                capacity:8,
                extended_capacity:13,
                reload_count:1,
            },
            bullet:{
                def:{
                    damage:34,
                    range:120,
                    falloff:0.75,
                    criticalMult:1.1,
                    obstacleMult:1.25,
                    speed:50,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:1,
                speed:0.6
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.shotgun("m870","12g",{
            fireDelay:1,
            spread:5,
            jitterRadius:0.4,

            fireMode:FireMode.Single,
            ammoSpawnAmount:10,
            rank:ItemRank.C,

            reload:{
                delay:0.8,
                capacity:5,
                extended_capacity:10,
                reload_count:1,
            },
            bullet:{
                def:{
                    damage:7,
                    speed:25,
                    range:30,
                    falloff:0.7,
                    criticalMult:1.2,
                    tracer:tracers.small
                },
                count:10
            },
            recoil:{
                duration:1.1,
                speed:0.6
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.shotgun("spas12","12g",{
            fireDelay:1,
            spread:2.5,
            jitterRadius:0.2,

            fireMode:FireMode.Single,
            ammoSpawnAmount:16,
            rank:ItemRank.B,

            reload:{
                delay:0.6,
                capacity:8,
                extended_capacity:11,
                reload_count:1,
            },
            bullet:{
                def:{
                    damage:5.5,
                    speed:30,
                    range:50,
                    falloff:0.7,
                    criticalMult:1.2,
                    tracer:tracers.small
                },
                count:10
            },
            recoil:{
                duration:1.1,
                speed:0.6
            },
            assets:{
                cycle_sound:true
            }
        }),
        guns_factory.shotgun("hp18","12g",{
            fireDelay:0.3,
            spread:6,
            jitterRadius:0.25,

            fireMode:FireMode.Auto,
            ammoSpawnAmount:15,
            rank:ItemRank.D,

            reload:{
                delay:0.7,
                capacity:5,
                extended_capacity:6,
                reload_count:1,
            },
            bullet:{
                def:{
                    damage:4,
                    speed:30,
                    falloff:0.6,
                    range:30,
                    criticalMult:1.2,
                    tracer:tracers.tiny
                },
                count:15
            },
            recoil:{
                duration:0.4,
                speed:0.75
            },
        }),
        guns_factory.sniper("sr25","762mm",{
            fireDelay:0.3,
            spread:1,

            ammoSpawnAmount:60,

            reload:{
                delay:2.5,
                capacity:20,
                extended_capacity:25,
            },
            bullet:{
                def:{
                    damage:23,
                    falloff:0.75,
                    range:110,
                    speed:50,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:0.4,
                speed:0.75
            },
        }),
        {
            idString:"pkp",
            fireDelay:0.1,
            switchDelay:1,
            spread:5,
            lenght:0.9,
            ammoType:"762mm",
            ammoSpawnAmount:200,
            class:GunClasses.LMG,
            rank:ItemRank.S,
            reload:{
                delay:5,
                capacity:200,
                extended_capacity:250,
            },
            bullet:{
                def:{
                    damage:14,
                    obstacleMult:1.5,
                    range:125,
                    speed:50,
                    tracer:tracers.large
                }
            },
            recoil:{
                duration:0.12,
                speed:0.5
            },
            speed_mod:0.8,
            gasParticles:GasParticles.automatic,
            case:{
                position:v2.new(0.8,0.3)
            },
            muzzleFlash:MuzzleFlash.normal,
            arms:WeaponsArmRig[2],
            image:{
                position:v2.new(0.6,0.0),
                rotation:0
            },
        },
        {
            idString:"rpg7",
            fireDelay:1,
            switchDelay:0.3,
            spread:0.2,
            lenght:1,
            ammoType:"explosive_ammo",
            fireMode:FireMode.Single,
            class:GunClasses.Miscellaneous,
            rank:ItemRank.S,
            ammoSpawnAmount:11,
            gasParticles:{
                count:10,
                life_time:1.2,
                speed:{
                    min:1,
                    max:2
                },
                direction_variation:0.4,
                size:{
                    min:0.6,
                    max:2,
                }
            },
            bullet:{
                def:{
                    damage:5,
                    range:80,
                    falloff:0.5,
                    on_hit_explosion:"rocket_explosion",
                    speed:22,
                    criticalMult:1.2,
                    obstacleMult:3,
                    tracer:{
                        height:2,
                        width:2,
                        particles:{
                            frame:1
                        },
                        proj:{
                            img:2,
                            width:4,
                            height:4,
                        },
                    }
                }
            },
            reload:{
                delay:2,
                capacity:1,
            },
            recoil:{
                duration:1.45,
                speed:0.25
            },
            speed_mod:0.5,
        },
        {
            idString:"m79",
            fireDelay:1,
            switchDelay:0.1,
            spread:0.2,
            lenght:1,
            barrel_offset:0.45,
            ammoType:"explosive_ammo",
            ammoSpawnAmount:11,
            fireMode:FireMode.Single,
            class:GunClasses.Miscellaneous,
            rank:ItemRank.A,
            gasParticles:{
                count:10,
                life_time:1.2,
                speed:{
                    min:1,
                    max:2
                },
                direction_variation:0.4,
                size:{
                    min:0.6,
                    max:2,
                }
            },
            projectile:{
                def:"m79_grenade",
            },
            reload:{
                delay:2,
                capacity:1,
            },
            speed_mod:0.75,
            recoil:{
                duration:1,
                speed:0.6
            },
            arms:WeaponsArmRig[2],
            assets:{
                world:"weapon_medium_world",
                world_tint:0x3f3a2f
            },
            image:{
                position:v2.new(0.6,0.45),
                rotation:0
            },
        },
        {
            idString:"m2_2",
            fireDelay:0.1,
            switchDelay:1,
            spread:10,
            lenght:1,
            ammoType:"gasoline",
            fireMode:FireMode.Auto,
            class:GunClasses.Miscellaneous,
            rank:ItemRank.A,
            ammoSpawnAmount:15,
            synsed_particle:{
                count:2,
                def:"m2_2_fire",
                speed:{
                    min:10,
                    max:20
                },
            },
            reload:{
                delay:5,
                capacity:5,
                ammo_consume:0.05,
            },
            recoil:{
                duration:1.45,
                speed:0.46
            },
            speed_mod:0.6,
        },
    )
}