import { AKeyFrame, Angle, CircleHitbox2D, Definition, Definitions, ease, FrameDef, FrameTransform, Hitbox2D, v2, } from "../../../engine/core.ts";
import { DefaultFistRig, FireMode, FistRig, ItemRank, WeaponAssets } from "../../others/item.ts";
import { InventoryItemType } from "../utils.ts";
export interface MeleeDef extends Definition{
    rank:ItemRank
    item_type?:InventoryItemType.melee

    hitbox:Hitbox2D
    damage:number
    resistence_damage?:number
    fire_mode?:FireMode

    attack_delay:number
    switch_delay?:number
    damage_delays:number[]

    speed_mod?:number

    rig_arms?:FistRig
    rig_image?:FrameTransform
    animation?:AKeyFrame[]
    assets?:WeaponAssets&{
        hit_sound?:string
    }
    character_frame?:{
        equipped_frame:FrameDef
        unequipped_frame:FrameDef
    }

    reflective?:{
        frame?:string
        offset:number
    }
}
export function AnimationSwing(time:number):AKeyFrame[]{
    const r=Angle.deg2rad(90)
    return [
        {
            time:0,
            actions:[
            ]
        },
        {
            time:time*0.3,
            actions:[
                {
                    fuser:"weapon",
                    type:"tween",
                    to:{
                        rotation:r+0.4,
                        position:v2.add(DefaultFistRig.left!.position,v2(0,0.1))
                    },
                    ease:ease.quadraticInOut
                },
                {
                    fuser:"left_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.left!.rotation-0.2,
                        position:v2.add(DefaultFistRig.left!.position,v2(0,0.1))
                    },
                    ease:ease.quadraticInOut
                },
                {
                    fuser:"right_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.right!.rotation+0.2,
                        position:v2.add(DefaultFistRig.right!.position,v2(-0.07,0.05))
                    },
                    ease:ease.quadraticInOut
                },
            ]
        },
        {
            time:time*0.15,
            actions:[
                {
                    fuser:"weapon",
                    type:"tween",
                    to:{
                        rotation:r-1,
                        position:v2.add(DefaultFistRig.left!.position,v2(0,0))
                    },
                },
                {
                    fuser:"left_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.left!.rotation+0.1,
                        position:v2.add(DefaultFistRig.left!.position,v2(-0.05,0.1))
                    },
                    ease:ease.quadraticInOut
                },
                {
                    fuser:"right_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.right!.rotation-0.3,
                        position:v2.add(DefaultFistRig.right!.position,v2(0.15,-0.15))
                    },
                    ease:ease.quadraticInOut
                },
            ]
        },
        {
            time:time*0.7,
            actions:[
                {
                    fuser:"weapon",
                    type:"tween",
                    to:{
                        rotation:r,
                        position:DefaultFistRig.left!.position
                    }
                },
                {
                    fuser:"left_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.left!.rotation,
                        position:DefaultFistRig.left!.position
                    },
                    ease:ease.quadraticInOut
                },
                {
                    fuser:"right_arm",
                    type:"tween",
                    to:{
                        rotation:DefaultFistRig.right!.rotation,
                        position:DefaultFistRig.right!.position
                    },
                    ease:ease.quadraticInOut
                },
            ]
        },
    ]
}
export function Melees_Default_Init(melees:Definitions<MeleeDef,{}>){
    melees.insert(
        {
            idString:"survival_knife",
            rank:ItemRank.E,

            hitbox:new CircleHitbox2D(v2.new(0.5,0),0.5),
            damage:15,
            attack_delay:0.25,
            switch_delay:0.5,
            damage_delays:[0.11],

            rig_arms:{
                right:{
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            rig_image:{
                position:DefaultFistRig.right!.position,
                rotation:-0.5,
                zIndex:1,
                hotspot:v2(0.33,0.5)
            },
            animation:[
                {
                    time:0,
                    actions:[
                    ]
                },
                {
                    time:0.06,
                    actions:[
                        {
                            fuser:"weapon",
                            type:"tween",
                            yoyo:true,
                            to:{
                                rotation:DefaultFistRig.right!.rotation-1,
                                position:v2.add(DefaultFistRig.right!.position,v2(0,-0.2))
                            }
                        },
                        {
                            fuser:"right_arm",
                            type:"tween",
                            yoyo:true,
                            to:{
                                rotation:DefaultFistRig.right!.rotation-0.4,
                                position:v2.add(DefaultFistRig.right!.position,v2(0,-0.2))
                            }
                        }
                    ]
                }
            ],
            assets:{
                use_sound:"light_swing",
                hit_sound:"knife_hit",
            }
        },
        {
            idString:"axe",
            rank:ItemRank.D,

            hitbox:new CircleHitbox2D(v2.new(0.6,0),0.5),
            damage:33,
            resistence_damage:1,
            attack_delay:0.4,
            switch_delay:0.5,
            damage_delays:[0.3],

            rig_arms:{
                right:{
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            rig_image:{
                position:DefaultFistRig.left!.position,
                rotation:Angle.deg2rad(90),
                zIndex:1,
                hotspot:v2(0.2,0.4)
            },
            animation:AnimationSwing(0.45),
            assets:{
                use_sound:"heavy_swing",
                hit_sound:"axe_hit",
            }
        },
        {
            idString:"sledgehammer",
            rank:ItemRank.A,

            hitbox:new CircleHitbox2D(v2(0.6,0),0.6),
            damage:49.5,
            resistence_damage:2,
            attack_delay:0.6,
            switch_delay:0.1,
            damage_delays:[0.4],

            rig_arms:{
                right:{ 
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            rig_image:{
                position:DefaultFistRig.left!.position,
                rotation:Angle.deg2rad(90),
                zIndex:1,
                hotspot:v2(0.2,0.3)
            },
            animation:AnimationSwing(0.55),
            assets:{
                use_sound:"heavy_swing",
                hit_sound:"sledgehammer_hit",
            }
        },
        {
            idString:"shovel",
            rank:ItemRank.D,

            hitbox:new CircleHitbox2D(v2(0.6,0),0.6),
            damage:20,
            attack_delay:0.35,
            switch_delay:0.5,
            damage_delays:[0.25],

            rig_arms:{
                right:{
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            rig_image:{
                position:DefaultFistRig.left!.position,
                rotation:Angle.deg2rad(90),
                zIndex:1,
                hotspot:v2(0.2,0.4)
            },
            animation:AnimationSwing(0.3),
            assets:{
                use_sound:"heavy_swing",
                hit_sound:"shovel_hit",
            }
        },
        /*{
            idString:"katana",
            rank:ItemRank.D,

            hitbox:new CircleHitbox2D(v2.new(0.6,0),0.5),
            damage:30,
            resistence_damage:1,
            attack_delay:0.4,
            switch_delay:0.5,
            damage_delays:[0.3],

            rig_arms:{
                right:{
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            rig_image:{
                position:DefaultFistRig.left!.position,
                rotation:Angle.deg2rad(90),
                zIndex:1,
                hotspot:v2(0.2,0.4)
            },
            animation:AnimationSwing(0.45),
            assets:{
                use_sound:"heavy_swing",
                hit_sound:"axe_hit",
                world:"katana_world"
            },
            character_frame:{
                equipped_frame:{
                    image:"katana",
                    position:v2.new(-1.1,0),
                    hotspot:v2(1,0.5),
                    rotation:3.5
                },
                unequipped_frame:{
                    image:"katana_bag",
                    position:v2.new(-1.1,0),
                    hotspot:v2(1,0.5),
                    rotation:3.5
                }
            }
        },*/
        /*{
            idString:"pan",
            damage:20,
            offset:0.6,
            rank:ItemRank.D,
            radius:0.9,
            size:2,
            attack_delay:0.4,
            switchDelay:0.5,
            damage_delays:[0.3],
            arms:{
                right:{
                    position:DefaultFistRig.right!.position,
                    rotation:DefaultFistRig.right!.rotation,
                    zIndex:2,
                },
                left:{
                    position:DefaultFistRig.left!.position,
                    rotation:DefaultFistRig.left!.rotation,
                    zIndex:2,
                }
            },
            image:{
                position:DefaultFistRig.left!.position,
                rotation:Angle.deg2rad(90),
                zIndex:1,
                hotspot:v2(0.2,0.4)
            },
            reflective:{
                frame:"pan_world",
                offset:0.6
            },
            animation:AnimationSwing(0.45),
            assets:{
                use_sound:"heavy_swing",
                hit_sound:"axe_hit",
            }
        },*/
    )
}