import { LootTable } from "../../engine/core.ts";

export const LootTables={
    //Guns Quality
    common_guns:[
        {item:"taurustx",weight:100},
        {item:"m9",weight:100},
        {item:"mp5",weight:90},
        {item:"colt1873",weight:90},
        {item:"micro_uzi",weight:80},
        {item:"hp18",weight:60},
        {item:"ak47",weight:40},
        {item:"ar15",weight:40},
        {item:"m1921",weight:40},
        {item:"m870",weight:39},
        {item:"famas",weight:10},
        {item:"spas12",weight:7},
        {item:"model94",weight:7},
        {item:"blr81",weight:7},
    ],
    mythic_guns:[
        {item:"sr25",weight:13},
        {item:"vss",weight:13},
        {item:"vector",weight:13},
        {item:"kar98k",weight:7},
        {item:"m2_2",weight:5},
        {item:"m79",weight:1},
        {item:"awp",weight:1},
    ],
    legendary_guns:[
        {item:"m1_garand",weight:15},
        {item:"pfeifer_zeliska",weight:10},
        {item:"awms",weight:6},
        {item:"rpg7",weight:1},
    ],
    //Guns Spawn
    guns:[
        {table:"common_guns",weight:150},
        {table:"mythic_guns",weight:15},
        {table:"legendary_guns",weight:1}
    ],
    melees:[
        {item:"survival_knife",weight:15},
        {item:"shovel",weight:15},
        {item:"axe",weight:10},
        {item:"katana",weight:3},
        {item:"sledgehammer",weight:3},
        {item:"bonesaw",weight:3},
    ],
    //Consumibles
    consumibles:[
        {table:"health_consumibles",count:1,weight:10},
        {table:"adrenaline_consumibles",count:1,weight:7},
        {table:"shield_consumibles",count:1,weight:6},
        {table:"addiction_consumibles",count:1,weight:1},
        {table:"green_bless_consumibles",count:1,weight:0.04},
        {table:"death_consumibles",count:1,weight:0.04},
    ],
    health_consumibles:[
        {item:"bandage",count:5,weight:8},
        {item:"medikit",weight:1},
    ],
    adrenaline_consumibles:[
        {item:"yellow_soda",count:1,weight:8},
        {item:"inhaler",count:1,weight:1},
        {item:"yellow_pills",count:1,weight:0.1},
    ],
    shield_consumibles:[
        {item:"blue_soda",count:2,weight:8},
        {item:"blue_potion",count:1,weight:1},
        {item:"blue_pills",count:1,weight:0.1},
    ],
    addiction_consumibles:[
        {item:"red_soda",count:2,weight:5},
        {item:"small_red_crystal",count:4,weight:1},
        {item:"red_crystal",count:2,weight:0.1},
    ],
    mana_consumibles:[
        {item:"purple_soda",count:2,weight:8},
        {item:"purple_potion",count:1,weight:1},
        {item:"purple_pills",count:1,weight:0.1},
    ],
    green_bless_consumibles:[
        {item:"green_soda",count:1,weight:1},
    ],
    death_consumibles:[
        {item:"black_soda",count:1,weight:1},
    ],
    //Ammos
    ammos:[
        {item:"12g",count:10,weight:5},
        {item:"9mm",count:50,weight:5},
        {item:"762mm",count:40,weight:5},
        {item:"556mm",count:40,weight:5},
        {item:"45acp",count:40,weight:5},
        {item:"22lr",count:60,weight:4},
        {item:"50cal",count:20,weight:0.1},
        {item:"308sub",count:5,weight:0.05},
        {item:"gasoline",count:5,weight:0.05},
        {item:"explosive_ammo",count:2,weight:0.05},
    ],
    //Throwables
    throwables:[
        {item:"frag_grenade",count:2,weight:70},
        {item:"smoke_grenade",count:2,weight:70},
        {item:"molotov",count:1,weight:30},
        {item:"mirv_grenade",count:1,weight:20},
        {item:"blue_flare",count:1,weight:1},
        {item:"orange_flare",count:2,weight:1},
        {item:"red_flare",count:1,weight:1},
    ],
    //Scopes
    scopes:[
        {item:"scope_2",count:1,weight:27},
        {item:"scope_3",count:1,weight:10},
        {item:"scope_4",count:1,weight:1.5},
        {item:"scope_5",count:1,weight:0.1},
        {item:"scope_6",count:1,weight:0.01},
        {item:"scope_7",count:1,weight:0.001},
    ],
    //Armors And Backpacks
    helmets:[
        {item:"basic_helmet",weight:8},
        {item:"regular_helmet",weight:1},
        {item:"military_helmet",weight:0.2},
    ],
    vests:[
        {item:"basic_vest",weight:10},
        {item:"regular_vest",weight:1},
        {item:"military_vest",weight:0.1},
    ],
    backpacks:[
        {item:"basic_pack",weight:10},
        {item:"regular_pack",weight:1},
        {item:"military_pack",weight:0.1},
    ],
    armors:[
        {table:"helmets",weight:1},
        {table:"vests",weight:1},
    ],
    equipments:[
        {table:"helmets",weight:1},
        {table:"vests",weight:1},
        {table:"backpacks",weight:1},
    ],
    military_equipments:[
        {item:"military_vest",weight:1},
        {item:"military_helmet",weight:1},
        {item:"military_pack",weight:1},
    ],
    accessorys:[
        {weight:5,item:"lucky_coin"},
        {weight:5,item:"pygmy_necklace"},
        {weight:5,item:"liquid_insanity"},
        {weight:5,item:"ghost_ammo"},
        {weight:5,item:"biggest_magazine"},
        {weight:5,item:"self_revive"},
        {weight:4,item:"nature_leaf"},
        {weight:4,item:"bullet_breaker_barrel"},
        {weight:4,item:"rare_projectile"},
        {weight:4,item:"high_quality_projectiles"},
        {weight:4,item:"good_reflective_bullet"},
    ],
    //Loot Tables
    civil_loot:[
        {weight:1,table:"ammos"},
        {weight:1,table:"consumibles"},
        {weight:0.7,table:"equipments"},
        {weight:0.7,table:"scopes"},
        {weight:0.2,table:"throwables"},
        {weight:0.1,table:"guns"},
        {weight:0.01,table:"melees"},
    ],
    normal_loot:[
        {weight:1,table:"ammos"},
        {weight:1,table:"consumibles"},
        {weight:0.85,table:"guns"},
        {weight:0.6,table:"equipments"},
        {weight:0.6,table:"scopes"},
        {weight:0.55,table:"throwables"},
        {weight:0.05,table:"melees"},
    ],
    loot_drawer:[
        {weight:2,count:2,table:"normal_loot"},
        {weight:1,count:3,table:"normal_loot"},
        {weight:0.5,count:4,table:"normal_loot"},
    ],
    //Crates
    wood_crate:[
        {weight:2,count:1,table:"normal_loot"},
        {weight:1,count:2,table:"normal_loot"},
        {weight:0.5,count:3,table:"normal_loot"},
    ],
    campfire_crate:[
        [{weight:1,table:"ammos"}],
        [{weight:1,table:"consumibles"}],
        [{weight:1,table:"scopes"}],

        [{weight:1,table:"helmets"}],
        [{weight:1,table:"vests"}],
        [{weight:1,table:"backpacks"}],

        [{weight:1,table:"guns",count:2}],
        [{weight:1,table:"melees"}],
    ],
    copper_crate:[
        [{weight:1,table:"civil_loot",count:3}],
        [{weight:1,table:"normal_loot",count:2}],
        [{weight:1,table:"guns"}],
    ],
    iron_crate:[
        [{weight:1,table:"ammos",count:2}],
        [{weight:1,table:"consumibles",count:2}],
        [{weight:1,table:"military_equipments"}],
        [{weight:1,table:"mythic_guns"}],
        [{weight:1,table:"throwables"}],
        [{weight:1,table:"scopes"}],
        [{weight:9,table:""},{weight:1,table:"melees"}],
    ],
    gold_crate:[
        [{weight:1,table:"ammos",count:2}],
        [{weight:1,table:"consumibles",count:2}],
        [{weight:10,table:"military_equipments"},{weight:1,count:2,table:"military_equipments"}],
        [{weight:10,table:"legendary_guns"}],
        [{weight:1,table:"throwables"}],
        [{weight:1,table:"scopes"}],
        [{weight:1,table:""},{weight:4,table:"melees"}],
    ],
    ammo_crate:[
        {weight:1,count:5,table:"ammos"},
    ],
    platinum_crate:[
        [{weight:1,table:"ammos",count:4}],
        [{weight:1,table:"consumibles",count:7}],
        [{weight:1,count:6,table:"military_equipments"}],
        [{weight:1,count:7,table:"mythic_guns"}],
        [{weight:1,count:2,table:"legendary_guns"}],
        [{weight:1,count:2,table:"melees"}],
        [{weight:1,count:5,table:"throwables"}],
        [{weight:1,count:4,table:"scopes"}],
    ],
    //Animals
    animal_medium:[
        [{weight:1,count:1,table:"consumibles"}],
        [{weight:10,count:1,table:""},{weight:1,count:1,table:"ammos"}],
    ],
    golden_rock:[
        [{weight:1,table:"consumibles"}],
        [{weight:1,table:"equipments"}],
        [{weight:1,table:"scopes"}],
        [{weight:1,item:"kar98k"}],
    ],
    platinum_rock:[
        [{weight:1,table:"consumibles"}],
        [{weight:1,table:"equipments"}],
        [{weight:1,table:"scopes"}],
        [{weight:1,item:"awp"}],
    ],
    black_container:[
        [{weight:1,item:"military_helmet"}],
        [{weight:1,table:"mythic_guns"}],
        [
            {item:"scope_5",weight:10},
            {item:"scope_6",weight:5},
            {item:"scope_7",weight:2},
        ]
    ]
} satisfies Record<string,LootTable>