import { DeepPartial, Definition, Definitions, FrameDef, Hitbox2D, HitboxGroup2D, mergeDeep, RectHitbox2D, v2, Vec2, WeightDefinition } from "../../../engine/core.ts";
import { Spawn, SpawnMode } from "../../others/constants.ts";
import { FloorType } from "../../others/terrain.ts";
import { hit_sounds, HitParticlesDef, HitSoundsDef } from "../utils.ts";
//20mm = 0.17619
//2mm  = 0.017619
export type BuildingCeilingDef={
    frame:FrameDef,
    hitbox:Hitbox2D,
    visible_opacity?:number,
    layer?:number,
    connections?:number[],
    destroy?:{
        frame:FrameDef
        sound?:string
        count:number
        particles?:{
            count:number
        }
    }
}
export type BuildingObstacles={
    def:string|((WeightDefinition&{def:string})[])
    id?:number
    position:Vec2
    connections?:number[]
    skin?:number
    variation?:number
    layer?:number
    rotation?:number
    scale?:number
    stairs_dest?:Record<number,number>
}
export type BuildingLoot={
    table:string
    position:Vec2
}
export type BuildingSubBuilding={
    def:string|((WeightDefinition&{def:string})[])
    position:Vec2
    layer?:number
    rotation?:0|1|2|3
}
export interface BuildingDef extends Definition{
    no_collisions?: boolean
    no_bullet_collision?: boolean
    reflect_bullets?:boolean
    content:{
        ceiling?:BuildingCeilingDef[]
        obstacles?:BuildingObstacles[]
        sub_building?:BuildingSubBuilding[]
        loots?:BuildingLoot[]
        floors?:{hitbox:Hitbox2D,type:FloorType,layer?:number}[]
        floor_image?:(FrameDef&{layer?:number})[]
    }
    spawnHitbox?:Hitbox2D
    spawnMode?:SpawnMode
    hitbox?:Hitbox2D
    assets?:{
        sounds?:HitSoundsDef
        particles?:HitParticlesDef
    }
}
export const buildings_factory={
    container:{
        type_1(id:string,tint:number=0xffffff,settings:{
            floor?:string,
            ceiling?:string,
            b?:DeepPartial<BuildingDef>
        }={}){
            const min=v2(-3.05,-1.5)
            const max=v2(3.05,1.5)
            return mergeDeep({
                idString:id,
                reflect_bullets:true,
                hitbox:RectHitbox2D.wall_enabled(min,max,{
                    left:true,
                    bottom:true,
                    right:false,
                    top:true
                },0.5),
                spawnHitbox:new RectHitbox2D(min,max),
                assets:{
                    particles:{
                        particle:"metal_particle",
                        tint:tint
                    },
                    sounds:hit_sounds,
                },
                content:{
                    floor_image:[
                        {
                            image:settings.floor??"container_floor_1",
                            tint:tint
                        }
                    ],
                    ceiling:[
                        {
                            frame:{
                                image:settings.ceiling??"container_ceiling_1",
                                tint:tint
                            },
                            hitbox:new RectHitbox2D(min,max),
                        }
                    ]
                }
            } as BuildingDef,settings.b??{})
        },
        type_2(id:string,tint:number=0xffffff,settings:{
            floor?:string,
            ceiling?:string,
            b?:DeepPartial<BuildingDef>
        }={}){
            const min=v2(-3.05,-1.5)
            const max=v2(3.05,1.5)
            return mergeDeep({
                idString:id,
                reflect_bullets:true,
                hitbox:RectHitbox2D.wall_enabled(min,max,{
                    left:false,
                    bottom:true,
                    right:false,
                    top:true
                },0.5),
                spawnHitbox:new RectHitbox2D(min,max),
                assets:{
                    particles:{
                        particle:"metal_particle",
                        tint:tint
                    },
                    sounds:hit_sounds,
                },
                content:{
                    floor_image:[
                        {
                            image:settings.floor??"container_floor_2",
                            tint:tint
                        }
                    ],
                    ceiling:[
                        {
                            frame:{
                                image:settings.ceiling??"container_ceiling_2",
                                tint:tint
                            },
                            hitbox:new RectHitbox2D(min,max),
                        }
                    ]
                }
            } as BuildingDef,settings.b??{})
        },
        simple(id:string,tint:number):BuildingDef[]{
            const b={
                content:{
                    loots:[
                        {table:"special_loot",position:v2.new(-1,0)},
                        {table:"special_loot",position:v2.new(1,0)}
                    ]
                }
            }
            return [
                this.type_1(id+"_1",tint,{b}),
                this.type_2(id+"_2",tint,{b})
            ]
        }
    },
    stairs(id:string,settings:{
        width?:number
        height?:number
        ceiling?:string
        top?:DeepPartial<BuildingDef>
        bottom?:DeepPartial<BuildingDef>
    }={}):BuildingDef[]{
        const width=settings.width??0.83
        const height=settings.height??0.83
        const ceiling=settings.ceiling??"small_iron_stairs_ceiling_1"
        const hb=new RectHitbox2D(v2(-width,-height),v2(width,height))
        const base={
            no_bullet_collision:true,
            no_collisions:true,
            hitbox:hb,
        }
        return [
            mergeDeep({
                idString:id+"_down",
                content:{
                    ceiling:[{
                        frame:{
                            image:ceiling,
                            position:v2(0,0),
                            hotspot:v2(.5,.5),
                            scale:2,
                        },
                        hitbox:hb,
                    }],
                    obstacles:[
                        {
                            def:id+"_part",
                            position:v2(0,0),
                            rotation:0,
                            stairs_dest:{0:-1},
                        },
                    ],
                }
            },base,settings.bottom??{}),
            mergeDeep({
                idString:id+"_up",
                content:{
                    ceiling:[{
                        frame:{
                            image:ceiling,
                            position:v2(0,0),
                            hotspot:v2(.5,.5),
                            scale:2,
                            rotation:Math.PI
                        },
                        hitbox:hb,
                    }],
                    obstacles:[
                        {
                            def:id+"_part",
                            position:v2(0,0),
                            rotation:0,
                            stairs_dest:{0:1},
                        },
                    ],
                }
            },base,settings.top??{})
        ]
    },
    small_bunker(id:string,settings:{
        top?:DeepPartial<BuildingDef>
        bottom?:DeepPartial<BuildingDef>
        content?:BuildingObstacles[]
    }={}):BuildingDef[]{
        return [
            mergeDeep({
                idString:id,
                content:{
                    sub_building:[
                        {
                            def:"small_iron_stairs_down",
                            position:v2.new(-3.47,0),
                            rotation:0,
                        },
                        {
                            def:id+"_bottom",
                            position:v2.zero(),
                            rotation:0,
                            layer:-1
                        }
                    ],
                },
                no_bullet_collision:true,
                no_collisions:true,
                hitbox:RectHitbox2D.centered(v2(0,0),v2(1,1)),
            },settings.top??{}),
            mergeDeep({
                idString:id+"_bottom",
                reflect_bullets:true,
                content:{
                    sub_building:[
                        {
                            def:"small_iron_stairs_up",
                            position:v2.new(-3.47,0),
                            rotation:2,
                        },
                    ],
                    floor_image:[
                        {
                            image:"small_bunker_floor_1",
                        }
                    ],
                    obstacles:[
                        ...settings.content??[]
                    ],
                },
                assets:{
                    particles:{
                        particle:"metal_particle",
                        tint:0x404143
                    },
                    sounds:hit_sounds,
                },
                hitbox:new HitboxGroup2D(
                    RectHitbox2D.wall_enabled(v2(-2.65,-2.65),v2(2.65,2.65),{
                        bottom:true,
                        top:true,
                        left:false,
                        right:true
                    },0.2),
                    new RectHitbox2D(v2(-2.65,-2.65),v2(-2.45,-0.85)),
                    new RectHitbox2D(v2(-2.65,0.85),v2(-2.45,2.65))
                ),
            },settings.bottom??{})
        ]
    },
    house:{
        shed(id:string,settings:{
            walls_tint?:number
            doors_tint?:number
            b?:DeepPartial<BuildingDef>
            content?:BuildingObstacles[]
        }={}){
            const walls_tint=settings.walls_tint??1
            const doors_tint=settings.doors_tint??walls_tint
            return mergeDeep({
                idString:id,
                no_collisions:true,
                no_bullet_collision:true,
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x656877,
                    }
                },
                content:{
                    obstacles:[
                        {
                            def:"wood_door",
                            position:v2(1.76,0.739998),
                            rotation:3,
                            id:1,
                            variation:doors_tint
                        },
                        {
                            def:"wood_wall_4x1",
                            position:v2(1.76,-1.21),
                            rotation:1,
                            id:10,
                            variation:walls_tint
                        },
                        {
                            def:"wood_wall_4x1",
                            position:v2(1.76,1.21),
                            rotation:1,
                            connections:[1],
                            id:11,
                            variation:walls_tint
                        },
                        {
                            def:"wood_wall_14x1",
                            position:v2(0,-1.57),
                            rotation:0,
                            id:12,
                            variation:walls_tint
                        },
                        {
                            def:"wood_wall_14x1",
                            position:v2(0,1.57),
                            rotation:0,
                            id:13,
                            variation:walls_tint
                        },
                        {
                            def:"wood_wall_14x1",
                            position:v2(-1.76,0),
                            rotation:1,
                            id:14,
                            variation:walls_tint
                        },
                        ...(settings.content??[])
                    ],
                    ceiling:[ 
                        {
                            frame:{
                                image:"shed_ceiling",
                            },
                            connections:[10,11,12,13,14],
                            destroy:{
                                frame:{
                                    image:""
                                },
                                sound:"ceiling_break_1",
                                count:2,
                                particles:{
                                    count:30
                                }
                            },
                            hitbox:RectHitbox2D.centered(v2(0,0),v2(3.5,3.1)),
                        }
                    ],
                    floor_image:[
                        {
                            image:"shed_floor",
                            position:v2(0.21,0)
                        }
                    ],
                },
                hitbox:RectHitbox2D.centered(v2(0,0),v2(3.5,3.1)),
            },settings.b??{})
        },
        small_house_1(id:string,settings:{
            walls_tint?:number
            doors_tint?:number
            column_tint?:number
            b?:DeepPartial<BuildingDef>
        }={}){
            const walls_tint=settings.walls_tint??1
            const doors_tint=settings.doors_tint??walls_tint
            const column_tint=settings.column_tint??walls_tint
            return mergeDeep({
                idString:id,
                spawnHitbox:new RectHitbox2D(v2(-7.7,-7.7),v2(7.7,7.7)),
                content:{
                    obstacles:[
                        {
                            def:"wood_door",
                            position:v2(-7.37,-6.7),
                            rotation:1,
                            variation:doors_tint
                        },

                        {
                            def:"wood_wall_8x1",
                            position:v2(-0.54,-6.3),
                            rotation:1,
                            variation:walls_tint
                        },
                        {
                            def:"wood_door",
                            position:v2(-0.54,-4.03),
                            rotation:3,
                            id:1,
                            variation:doors_tint
                        },
                        {
                            def:"wood_wall_14x1",
                            position:v2(-0.54,-2.4),
                            rotation:1,
                            connections:[1],
                            variation:walls_tint
                        },
                        {
                            def:"wood_column",
                            position:v2(-0.54,-0.59),
                            variation:column_tint,
                        },
                        {
                            def:"wood_wall_28x1",
                            position:v2(-3.85,-0.59),
                            rotation:0,
                            variation:walls_tint,
                        },

                        {
                            def:"wood_wall_10x1",
                            position:v2(2.38,-6.08),
                            rotation:1,
                            connections:[2],
                            variation:walls_tint,
                        },
                        {
                            def:"wood_door",
                            position:v2(2.38,-4.9),
                            rotation:1,
                            id:2,
                            variation:doors_tint,
                        },
                        {
                            def:"wood_wall_16x1",
                            position:v2(2.38,-1.52),
                            rotation:1,
                            variation:walls_tint,
                        },
                        {
                            def:"wood_column",
                            position:v2(2.38,0.5),
                            variation:column_tint,
                        },
                        {
                            def:"wood_wall_20x1",
                            position:v2(4.9,0.5),
                            rotation:0,
                            variation:walls_tint,
                        },

                        //Furnitunes
                        {
                            def:"normal_tv",
                            rotation:3,
                            position:v2(-4,-1.22),
                            id:10,
                        },
                        {
                            def:"large_drawer",
                            rotation:3,
                            position:v2(-4,-1.15),
                            connections:[10]
                        },
                        {
                            def:"couch_3x1",
                            rotation:1,
                            position:v2(-4,-5.5)
                        },

                        {
                            def:"large_drawer",
                            rotation:1,
                            position:v2(-6.1,-0.04),
                        },
                        {
                            def:"small_stove",
                            rotation:3,
                            variation:2,
                            position:v2(-5.5,6.71),
                        },
                        {
                            def:"sink",
                            rotation:3,
                            variation:2,
                            position:v2(-4.4,6.71),
                        },
                        {
                            def:"large_kitchen_drawer",
                            rotation:3,
                            variation:2,
                            position:v2(-2.75,6.71),
                        },

                        {
                            def:"small_bed",
                            rotation:0,
                            position:v2(5.95,-6.2),
                        },
                        {
                            def:"wood_chair",
                            rotation:0,
                            position:v2(2,3),
                        },
                        {
                            def:"wood_table",
                            rotation:1,
                            position:v2(3,3),
                        },
                        {
                            def:"wood_chair",
                            rotation:2,
                            position:v2(4,3),
                        },
                    ],
                    floor_image:[
                        {
                            image:"small_house_1_floor",
                        }
                    ],
                },
                assets:{
                    sounds:hit_sounds.wood
                },
                hitbox:new HitboxGroup2D(
                    new RectHitbox2D(v2(-7.5,-7.5),v2(7.5,-7.25)),
                    new RectHitbox2D(v2(-7.5,-7.5),v2(-7.25,-6.65)),
                    new RectHitbox2D(v2(-7.5,-5.44),v2(-7.25,7.5)),

                    new RectHitbox2D(v2(7.25,-7.5),v2(7.5,7.5)),
                    new RectHitbox2D(v2(-7.5,7.25),v2(7.5,7.5)),
                ),
                spawnMode:Spawn.grass,
            },settings.b??{})
        }
    }
}
export function Buildings_Default_Init(buildings:Definitions<BuildingDef,{}>){
    buildings.insert(
        ...buildings_factory.container.simple("blue_container",0x0c40b1),
        ...buildings_factory.container.simple("yellow_container",0xffd900),
        ...buildings_factory.container.simple("red_container",0xb6071e),
        ...buildings_factory.container.simple("green_container",0x00ff0d),
        /*{
            idString:"watchtower",
            obstacles:[
                {
                    def:"iron_ladder_bottom",
                    position:v2(-7.6,-6.1),
                    rotation:0
                }
            ],
            floor_image:[],
            sub_building:[
                {
                    def:"watchtower_top",
                    position:v2.zero(),
                    layer:1
                }
            ],
            hitbox:RectHitbox2D.centered(v2(0,0),v2(6,6)),
            spawnMode:Spawn.grass,
        },
        {
            idString:"watchtower_top",
            floors:[
                {hitbox:RectHitbox2D.centered(v2(0,0),v2(11,11)),type:FloorType.Metal}
            ],
            obstacles:[
                {
                    def:"iron_ladder_top",
                    position:v2(-7.6,-6.1),
                    rotation:0,
                }
            ],
            floor_image:[
                {
                    image:"watch_tower_floor_1",
                    position:v2(0,0),
                    hotspot:v2(.5,.5),
                    scale:2,
                }
            ],
            hitbox:new HitboxGroup2D(
                new RectHitbox2D(v2(-10,-10),v2(10,-10)),
            ),
            spawnMode:Spawn.grass,
        },*/

        ...buildings_factory.stairs("small_iron_stairs"),
        ...buildings_factory.small_bunker("bunker_1",{
            content:[
                //{def:"md_crate",position:v2.zero},
                {def:"airdrop_locked",position:v2.zero},
                {def:"barrel",position:v2(1.7,1.7)},
            ]
        }),

        buildings_factory.house.shed("shed",{
            walls_tint:2,
            doors_tint:2,
            content:[
                {
                    def:"large_drawer",
                    position:v2(-1.21,0)
                }
            ],
            b:{
                content:{
                    loots:[
                        {table:"special_loot",position:v2.new(0.5,0)},
                    ]
                }
            }
        }),
        buildings_factory.house.small_house_1("small_house_1",{
            walls_tint:7,
            doors_tint:2,
        })
    )
}