import { Definition, Definitions, FrameDef, MinMax1 } from "../../../engine/core.ts";
import { tracers } from "../../others/item.ts";
import { BulletDef } from "../utils.ts";

export type ExplosionDef={
    size:{
        begin:number
        end:number
    }
    tint:string
    damage:number
    push_force?:number
    bullet?:{
        def:BulletDef
        count:number
    },
    assets:{
        sound:string
    },
    projectiles?:{
        def:string
        count:number
        speed:number
        angSpeed:number
        randomAng:number
    }
    particles?:{
        count:number
        frame:FrameDef
        speed:MinMax1
        lifetime:MinMax1
    }[]
    synced_particles?:{
        def:string
        count:number
    }
}&Definition

export function Explosions_Default_Init(explosions:Definitions<ExplosionDef,{}>){
    explosions.insert(
        {
            idString:"barrel_explosion",
            tint:"#445",
            size:{
                begin:2,
                end:5
            },
            damage:115,
            bullet:{
                def:{
                    damage:7,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"frag_grenade_explosion",
            tint:"#355",
            size:{
                begin:2,
                end:5
            },
            damage:115,
            bullet:{
                def:{
                    damage:7,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"smoke_grenade_explosion",
            tint:"#355",
            size:{
                begin:0,
                end:1
            },
            damage:0,
            push_force:0,
            assets:{
                sound:"explosion_4"
            },
            synced_particles:{
                count:11,
                def:"smoke"
            }
        },
        {
            idString:"molotov_explosion",
            tint:"#ff7b00",
            size:{
                begin:1,
                end:5
            },
            damage:5,
            assets:{
                sound:"explosion_6"
            },
            synced_particles:{
                count:15,
                def:"molotov_fire"
            }
        },
        {
            idString:"mirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:2,
                end:5
            },
            damage:120,
            bullet:{
                def:{
                    damage:7,
                    speed:12,
                    range:10,
                    tracer:tracers.mirv
                },
                count:5
            },
            projectiles:{
                count:6,
                def:"submirv_grenade",
                speed:1,
                angSpeed:15,
                randomAng:3
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"submirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:1,
                end:4
            },
            damage:30,
            bullet:{
                def:{
                    damage:7,
                    speed:18,
                    range:10,
                    tracer:tracers.mirv
                },
                count:5
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:3,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"blue_flare_explosion",
            tint:"#08b0ce",
            push_force:0,
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_3"
            },
        },
        {
            idString:"red_flare_explosion",
            tint:"#ca0819",
            push_force:0,
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_3"
            },
        },
        {
            idString:"nuke_explosion",
            tint:"#445",
            size:{
                begin:5,
                end:25
            },
            damage:500,
            bullet:{
                def:{
                    damage:30,
                    speed:20,
                    range:25,
                    tracer:tracers.black_projectile
                },
                count:40
            },
            assets:{
                sound:"explosion_2"
            },
        },
        {
            idString:"rocket_explosion",
            tint:"#445",
            size:{
                begin:2,
                end:4
            },
            damage:60,
            bullet:{
                def:{
                    damage:4,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"m79_grenade_explosion",
            tint:"#355",
            size:{
                begin:3,
                end:5
            },
            damage:60,
            bullet:{
                def:{
                    damage:4,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
    )
}