import { Definition, Definitions, FrameDef, MinMax1 } from "../../../engine/core.ts";
import { tracers } from "../../others/item.ts";
import { BulletDef } from "../utils.ts";

export type ExplosionDef={
    size:{
        begin:number
        end:number
    }
    tint:string
    damage:number
    bullet?:{
        def:BulletDef
        count:number
    },
    assets:{
        sound:string
    },
    projectiles?:{
        def:string
        count:number
        speed:number
        angSpeed:number
        randomAng:number
    }
    particles?:{
        count:number
        frame:FrameDef
        speed:MinMax1
        lifetime:MinMax1
    }[]
    synced_particles?:{
        def:string
        count:number
    }
}&Definition

export function Explosions_Default_Init(explosions:Definitions<ExplosionDef,{}>){
    explosions.insert(
        {
            idString:"barrel_explosion",
            tint:"#445",
            size:{
                begin:2,
                end:3
            },
            damage:105,
            bullet:{
                def:{
                    damage:7,
                    radius:0.02,
                    speed:20,
                    range:25,
                    tracer:tracers.black_projectile
                },
                count:6
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"rocket_explosion",
            tint:"#445",
            size:{
                begin:1,
                end:2
            },
            damage:80,
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"frag_grenade_explosion",
            tint:"#355",
            size:{
                begin:1.5,
                end:2
            },
            damage:105,
            bullet:{
                def:{
                    damage:7,
                    radius:0.0125,
                    speed:18,
                    range:8,
                    tracer:tracers.medium
                },
                count:5
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"smoke_grenade_explosion",
            tint:"#355",
            size:{
                begin:0.3,
                end:0.5
            },
            damage:0,
            assets:{
                sound:"explosion_1"
            },
            synced_particles:{
                count:10,
                def:"smoke"
            }
        },
        {
            idString:"mirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:1.6,
                end:2.2
            },
            damage:110,
            bullet:{
                def:{
                    damage:7,
                    radius:0.0125,
                    speed:18,
                    range:8,
                    tracer:tracers.mirv
                },
                count:5
            },
            projectiles:{
                count:6,
                def:"submirv_grenade",
                speed:2,
                angSpeed:15,
                randomAng:1
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"submirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:0.5,
                end:1
            },
            damage:15,
            bullet:{
                def:{
                    damage:7,
                    radius:0.0125,
                    speed:18,
                    range:8,
                    tracer:tracers.mirv
                },
                count:5
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:3,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ]
        },
        {
            idString:"blue_flare_explosion",
            tint:"#08b0ce",
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_1"
            },
        },
        {
            idString:"red_flare_explosion",
            tint:"#ca0819",
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_1"
            },
        },
        {
            idString:"nuke_explosion",
            tint:"#445",
            size:{
                begin:5,
                end:10
            },
            damage:1000,
            bullet:{
                def:{
                    damage:30,
                    radius:0.02,
                    speed:20,
                    range:50,
                    tracer:tracers.black_projectile
                },
                count:100
            },
            assets:{
                sound:"explosion_2"
            },
        },
    )
}