import { Definition, Definitions, FrameDef, MinMax1 } from "../../../engine/core.ts";
import { tracers } from "../../others/item.ts";
import { BulletDef } from "../utils.ts";
import { DecalInstanceDef } from "./decals.ts";
export interface CamShake{
    duration:number
    intensity:number
    distance?:number
}
export type ExplosionDef={
    size:{
        begin:number
        end:number
    }
    tint:string
    damage:number
    push_force?:number
    bullet?:{
        def:BulletDef
        count:number
    },
    assets:{
        sound:string
    },
    projectiles?:{
        def:string
        count:number
        speed:number
        angSpeed:number
        randomAng:number
    }
    particles?:{
        count:number
        frame:FrameDef
        speed:MinMax1
        lifetime:MinMax1
    }[]
    synced_particles?:{
        def:string
        count:number
    }
    decal?:DecalInstanceDef
    cam_shake?:CamShake
}&Definition
export const explosion_cam_shakes={
    big:{
        duration:3,
        intensity:5,
    },
    normal:{
        duration:0.25,
        intensity:1,
    },
    small:{
        duration:0.25,
        intensity:0.4,
    }
} satisfies Record<string,CamShake>
export const explosions_decals={
    big:{
        def:"explosion_decal",
        scale:6,
        tint:{
            color:0x000000,
            alpha:200,
        },
    },
    normal:{
        def:"explosion_decal",
        scale:1,
        tint:{
            color:0x000000,
            alpha:150,
        },
    },
    small:{
        def:"explosion_decal",
        scale:0.5,
        tint:{
            color:0x000000,
            alpha:150,
        },
    }
} satisfies Record<string,DecalInstanceDef>
export function Explosions_Default_Init(explosions:Definitions<ExplosionDef,{}>){
    explosions.insert(
        {
            idString:"barrel_explosion",
            tint:"#445",
            size:{
                begin:2,
                end:4.5
            },
            damage:115,
            bullet:{
                def:{
                    damage:7,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.normal,
            cam_shake:explosion_cam_shakes.normal
        },
        {
            idString:"frag_grenade_explosion",
            tint:"#355",
            size:{
                begin:2,
                end:4.5
            },
            damage:115,
            bullet:{
                def:{
                    damage:7,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.normal,
            cam_shake:explosion_cam_shakes.normal
        },
        {
            idString:"smoke_grenade_explosion",
            tint:"#355",
            size:{
                begin:0,
                end:1
            },
            damage:0,
            push_force:0,
            assets:{
                sound:"explosion_4"
            },
            synced_particles:{
                count:11,
                def:"smoke"
            },
            decal:explosions_decals.small,
            cam_shake:explosion_cam_shakes.small
        },
        {
            idString:"molotov_explosion",
            tint:"#ff7b00",
            size:{
                begin:1,
                end:5
            },
            damage:5,
            assets:{
                sound:"explosion_6"
            },
            synced_particles:{
                count:15,
                def:"molotov_fire"
            },
            cam_shake:explosion_cam_shakes.normal,
        },
        {
            idString:"mirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:2,
                end:4.5
            },
            damage:120,
            bullet:{
                def:{
                    damage:7,
                    speed:12,
                    range:10,
                    tracer:tracers.mirv
                },
                count:5
            },
            projectiles:{
                count:6,
                def:"submirv_grenade",
                speed:1,
                angSpeed:15,
                randomAng:3
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.normal,
            cam_shake:explosion_cam_shakes.normal,
        },
        {
            idString:"submirv_grenade_explosion",
            tint:"#09e",
            size:{
                begin:1,
                end:4
            },
            damage:30,
            bullet:{
                def:{
                    damage:7,
                    speed:18,
                    range:10,
                    tracer:tracers.mirv
                },
                count:5
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:3,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.small,
            cam_shake:explosion_cam_shakes.normal,
        },
        {
            idString:"blue_flare_explosion",
            tint:"#08b0ce",
            push_force:0,
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_3"
            },
            decal:explosions_decals.small,
            cam_shake:explosion_cam_shakes.small,
        },
        {
            idString:"red_flare_explosion",
            tint:"#ca0819",
            push_force:0,
            size:{
                begin:0.5,
                end:1
            },
            damage:0,
            assets:{
                sound:"explosion_3"
            },
            decal:explosions_decals.small,
            cam_shake:{
                duration:0.25,
                intensity:1,
            }
        },
        {
            idString:"nuke_explosion",
            tint:"#445",
            size:{
                begin:5,
                end:25
            },
            damage:500,
            bullet:{
                def:{
                    damage:30,
                    speed:20,
                    range:25,
                    tracer:tracers.black_projectile
                },
                count:40
            },
            assets:{
                sound:"explosion_2"
            },
            decal:explosions_decals.big,
            cam_shake:explosion_cam_shakes.big,
        },
        {
            idString:"rocket_explosion",
            tint:"#445",
            size:{
                begin:2,
                end:4
            },
            damage:60,
            bullet:{
                def:{
                    damage:4,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.normal,
            cam_shake:explosion_cam_shakes.normal,
        },
        {
            idString:"m79_grenade_explosion",
            tint:"#355",
            size:{
                begin:2,
                end:4.5
            },
            damage:60,
            bullet:{
                def:{
                    damage:4,
                    speed:20,
                    range:10,
                    tracer:tracers.black_projectile
                },
                count:10
            },
            assets:{
                sound:"explosion_1"
            },
            particles:[
                {
                    count:10,
                    lifetime:{
                        min:1,
                        max:1.5
                    },
                    speed:{
                        min:1,
                        max:3
                    },
                    frame:{
                        image:"gas_smoke_particle",
                        scale:0.01
                    }
                }
            ],
            decal:explosions_decals.normal,
            cam_shake:explosion_cam_shakes.normal,
        },
    )
}