import { CircleHitbox2D, DeepPartial, Definition, Definitions, FrameDef, FrameTransform, Hitbox2D, LootTable, mergeDeep, model2d, type Model2D, RectHitbox2D, RotationMode, v2, Vec2, WeightDefinition } from "../../../engine/core.ts";
import { Spawn, SpawnMode, zIndexes } from "../../others/constants.ts";
import { type GunDef } from "../items/guns.ts";
import { hit_sounds, HitParticlesDef, HitSoundsDef } from "../utils.ts";
import { DecalInstanceDef } from "./decals.ts";
export interface ObstacleBehaviorDoor{
    type:0,
    open_delay?:number
    cant_close?:boolean
    open_duration:number
    offset:number

    open_sound?:string
    close_sound?:string
}
export interface ObstacleDoorData{
    open:-1|0|1
    hitboxes:Record<number,Hitbox2D>
    locked:boolean
    opening:boolean
}
export interface ObstacleBehaviorPlaySound{
    type:1
    duration:number
    click_sound:string
    delay:number
}
export interface ObstacleBehaviorScalable{
    type:2
    floor_walk:number
    action_time:number
    interact_side:{pos:Vec2,rot?:number,dest_rot?:number,dest_pos?:Vec2}[]
}
export interface ObstacleBehaviorTransformInto{
    type:3,
    obstacles:(WeightDefinition&{id:string})[]
    sprites?:Record<number,FrameDef>
    first_particles?:{
        frame:FrameDef
        delay:number
        count:number
    }[]
    transform_particles?:{
        frame:FrameDef
        delay:number
        count:number
    }[]
    delay:number
    sound?:string
}
export interface ObstacleDef extends Definition{
    // Life
    health?:number
    imortal?:boolean
    resistence?:number

    //Collisions
    hitbox?:Hitbox2D
    spawnHitbox?:Hitbox2D
    below?:{
        hitbox?:Hitbox2D
        duration?:number
        alpha:number
    }
    no_collision?:boolean
    passable_by_bullets?:boolean
    no_bullets_collision?:boolean

    invisible_on_map?:boolean
    scale?:{
        min?:number
        max?:number
        destroy?:number
    }
    world_shadow?:{
        model:Model2D
    }

    assets?:{
        aditional_sprites?:FrameDef[]
        frame?:{
            base?:string
            dead?:string
            transform?:FrameTransform
            dead_transform?:FrameTransform
            variations?:number
            tint_variations?:number[]
            sprite_variations?:boolean
            biome_skins?:string[]
        }
        sounds?:HitSoundsDef
        particles?:HitParticlesDef
    }
    zIndex?:{
        base?:number
        dead?:number
    }
    rotation_mode?:number

    onDestroyExplosion?:string

    decal?:DecalInstanceDef
    lootTable?:LootTable

    interactDestroy?:boolean
    reflect_bullets?:boolean

    spawnMode?:SpawnMode

    height?:0|1|2 // 0 = Invisible | 1 = Mayble | 2 = All

    expanded_behavior?:(
        ObstacleBehaviorDoor|ObstacleBehaviorPlaySound|ObstacleBehaviorScalable|ObstacleBehaviorTransformInto
    )
    stair_data?:{
        hitbox:Hitbox2D
    }[]
}
export const obstacles_factory={
    gun_mount(gun:GunDef,settings:{
        o?:DeepPartial<ObstacleDef>
        id?:string
    }){
        return mergeDeep({idString:settings.id??(gun.idString+"_mount")},{
            health:65,
            height:1,
            hitbox:new RectHitbox2D(v2(-0.7,-0.2),v2(0.7,0.2)),
            scale:{
                destroy:0.8
            },
            assets:{
                frame:{
                    base:"gun_mount",
                    transform:{
                        tint:0x583b08
                    }
                },
                aditional_sprites:[{
                    ...gun.rig_image,
                    image:gun.assets?.world??gun.idString+"_world",
                    tint:gun.assets?.world_tint,
                    hotspot:v2.half_one,
                    scale:2,
                    zIndex:1,
                    position:v2.zero()
                }],
                sounds:hit_sounds.wood
            },
            rotation_mode:RotationMode.limited,
            lootTable:[{
                weight:1,
                item:gun.idString
            }],
        },settings.o??{})
    },
    rock(id:string,settings:{
        tint?:number,
        hitbox?:Hitbox2D,
        spawn_hitbox?:Hitbox2D,
        o?:DeepPartial<ObstacleDef>
    }={}):ObstacleDef{
        return mergeDeep({idString:id},{
            health:190,
            hitbox:settings.hitbox??new CircleHitbox2D(v2(0,0),0.82),
            spawnHitbox:settings.spawn_hitbox,
            scale:{
                destroy:0.7,
            },
            assets:{
                particles:{
                    particle:"rock_particle",
                    tint:settings.tint,
                    variations:2,
                },
                frame:{
                    base:"rock",
                    dead:"rock_dead",
                    transform:{
                        tint:settings.tint,
                    },
                    variations:2
                },
                sounds:hit_sounds.rock
            },
            rotation_mode:RotationMode.full,
            spawnMode:Spawn.grass,
            height:1,
        },settings.o??{})
    },
    bush(id:string,settings:{
        tint?:number,
        hitbox?:Hitbox2D,
        o?:DeepPartial<ObstacleDef>
    }={}):ObstacleDef{
        return mergeDeep({idString:id},{
            health:70,
            hitbox:settings.hitbox??new CircleHitbox2D(v2(0,0),0.8),
            no_collision:true,
            passable_by_bullets:true,
            scale:{
                min:1,
                max:1.2,
            },
            assets:{
                particles:{
                    particle:"leaf_1_particle",
                    tint:0x0e5c00,
                    variations:1
                },
                sounds:hit_sounds.bush
            },
            zIndex:{
                base:zIndexes.Obstacles3
            },
            rotation_mode:RotationMode.full,
            spawnMode:Spawn.grass,
            below:{
                alpha:60
            },
            height:2
        },settings.o??{})
    },
    box(id:string,settings:{
        o?:DeepPartial<ObstacleDef>,
    }={}):ObstacleDef{
        return mergeDeep({idString:id},{
            health:35,
            hitbox:new RectHitbox2D(v2(-0.35,-0.35),v2(0.35,0.35)),
            scale:{
                destroy:0.8,
            },
            rotation_mode:RotationMode.null,
            lootTable:id,
            height:1,
            assets:{
                frame:{
                    dead:"box_dead",
                },
                particles:{
                    particle:"tissue_particle",
                    tint:0xda946d,
                },
                sounds:hit_sounds.tissue
            }
        },settings.o??{})
    },
    crate(id:string,settings:{
        o?:DeepPartial<ObstacleDef>,
    }={}):ObstacleDef{
        return mergeDeep({idString:id},{
            health:65,
            hitbox:new RectHitbox2D(v2(-0.71,-0.71),v2(0.71,0.71)),
            scale:{
                destroy:0.7,
            },
            rotation_mode:RotationMode.null,
            lootTable:id,
            height:1,
            assets:{
                frame:{
                    dead:"wood_residue_1x1",
                    dead_transform:{
                        tint:0x5f3d07,
                        scale:2.3,
                    }
                }
            }
        },settings.o??{})
    },
    chest(id:string,settings:{
        o?:DeepPartial<ObstacleDef>,
    }={}):ObstacleDef{
        return mergeDeep({idString:id},{
            health:65,
            hitbox:new RectHitbox2D(v2(-0.71,-1),v2(0.71,1)),
            scale:{
                destroy:0.75,
            },
            rotation_mode:RotationMode.limited,
            lootTable:id,
            height:1,
        },settings.o??{})
    },
    walls:{
        door(id:string,tint:number|(number[]),settings:{
            particle?:string,
            sounds?:string,
            open_duration?:number
            o?:DeepPartial<ObstacleDef>
        }={}):ObstacleDef{
            const sounds=settings.sounds??"wood_door"
            return mergeDeep({
                idString:id,
                hitbox:new RectHitbox2D(v2(0,-0.15),v2(1.479996,0.15)),
                assets:{
                    particles:{
                        particle:settings.particle??"plank_particle",
                        tint:tint,
                    },
                    frame:{
                        base:"door",
                        transform:{
                            hotspot:v2(0,0.5),
                            tint:typeof tint==="number"?tint:undefined
                        },
                        tint_variations:typeof tint==="number"?undefined:tint,
                        variations:typeof tint==="number"?undefined:tint.length,
                        sprite_variations:false
                    },
                },
                rotation_mode:RotationMode.limited,
                expanded_behavior:{
                    type:0,
                    open_duration:settings.open_duration??0.15,
                    offset:0,
                    open_sound:sounds+"_open",
                    close_sound:sounds+"_close"
                }
            },settings.o??{})
        },
        wall(id:string,frame:string,tint:number|(number[]),health:number=200,width:number=0.2466,height:number=0.1233,particle:string="plank_particle",o:DeepPartial<ObstacleDef>={}):ObstacleDef{
            return mergeDeep({
                health:health,
                idString:id,
                hitbox:new RectHitbox2D(v2(-width,-height),v2(width,height)),
                assets:{
                    particles:{
                        particle:particle,
                        tint:tint,
                    },
                    frame:{
                        base:frame,
                        transform:{
                            tint:typeof tint==="number"?tint:undefined
                        },
                        tint_variations:typeof tint==="number"?undefined:tint,
                        variations:typeof tint==="number"?undefined:tint.length,
                        sprite_variations:false
                    }
                },
                rotation_mode:RotationMode.limited,
                spawnMode:Spawn.grass,
            },o)
        },
        column_1(id:string,tint:number|(number[]),particle:string="plank_particle",o:DeepPartial<ObstacleDef>={}):ObstacleDef{
            return mergeDeep({
                imortal:true,
                health:1,
                idString:id,
                hitbox:new RectHitbox2D(v2(-0.21,-0.21),v2(0.21,0.21)),
                assets:{
                    particles:{
                        particle:particle,
                        tint:tint,
                    },
                    frame:{
                        base:"column_1",
                        transform:{
                            tint:typeof tint==="number"?tint:undefined
                        },
                        tint_variations:typeof tint==="number"?undefined:tint,
                        variations:typeof tint==="number"?undefined:tint.length,
                        sprite_variations:false
                    }
                },
                rotation_mode:RotationMode.null,
                spawnMode:Spawn.grass,
            },o)
        },
        group(id:string,tint:number|(number[]),settings:{
            health?:number
            particle?:string
            o?:DeepPartial<ObstacleDef>
        }={}):ObstacleDef[]{
            const health=settings.health??40
            return [
                this.column_1(id+"_column",tint,settings.particle,settings.o),

                this.wall(id+"_wall_2x1","wall_size_2x1",tint,health*(1+(2-1)*0.2),undefined,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_4x1","wall_size_4x1",tint,health*(1+(4-1)*0.2),0.4933,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_6x1","wall_size_6x1",tint,health*(1+(6-1)*0.2),0.739998,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_8x1","wall_size_8x1",tint,health*(1+(8-1)*0.2),0.986664,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_10x1","wall_size_10x1",tint,health*(1+(10-1)*0.2),1.23333,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_12x1","wall_size_12x1",tint,health*(1+(12-1)*0.2),1.47999,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_14x1","wall_size_14x1",tint,health*(1+(14-1)*0.2),1.72666,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_16x1","wall_size_16x1",tint,health*(1+(16-1)*0.2),1.97332,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_18x1","wall_size_18x1",tint,health*(1+(18-1)*0.2),2.21992,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_20x1","wall_size_20x1",tint,health*(1+(20-1)*0.2),2.46666,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_24x1","wall_size_24x1",tint,health*(1+(24-1)*0.2),2.95999,undefined,settings.particle,settings.o),
                this.wall(id+"_wall_28x1","wall_size_28x1",tint,health*(1+(28-1)*0.2),3.45332,undefined,settings.particle,settings.o),
            ]
        }
    }
}
export const WallColors=[0xffffff,0x583b08,0xffd92b,0x468edb,0xb6071e,0x42a64a,0x4e4f50]
export function Obstacles_Default_Init(obstacles:Definitions<ObstacleDef,{}>,guns:Definitions<GunDef,{}>){
    obstacles.insert(
        {
            idString:"barrel",
            health:110,
            height:1,
            hitbox:new CircleHitbox2D(v2(0,0),0.65),
            scale:{
                destroy:0.5
            },
            assets:{
                particles:{
                    particle:"metal_particle",
                    tint:0x484848
                },
                frame:{
                    dead:"metal_residue_1x1",
                    dead_transform:{
                        tint:0x484848,
                    }
                },
                sounds:hit_sounds.heavy_metal
            },
            rotation_mode:RotationMode.full,
            onDestroyExplosion:"barrel_explosion",
            reflect_bullets:true,
            spawnMode:Spawn.grass,
        },
        obstacles_factory.rock("rock",{tint:0x4e4f50}),
        obstacles_factory.rock("giant_rock",{
            tint:0x4e4f50,
            spawn_hitbox:new CircleHitbox2D(v2.zero,5),
            o:{
                scale:{
                    min:2.9,
                    max:3
                },
                health:400,
            },
        }),
        obstacles_factory.rock("river_rock",{
            spawn_hitbox:new CircleHitbox2D(v2.zero,1.2),
            o:{
                scale:{
                    min:1.5,
                    max:2
                },
                health:300,
                spawnMode:Spawn.river_water
            },
            tint:0x353638,
        }),
        obstacles_factory.rock("golden_rock",{tint:0xffd92b,o:{
            lootTable:"golden_rock",
            health:200,
        }}),
        obstacles_factory.rock("platinum_rock",{tint:0x468edb,o:{
            lootTable:"platinum_rock",
            health:230,
        }}),
        {
            idString:"sillo",
            health:1,
            imortal:true,
            hitbox:new CircleHitbox2D(v2(0,0),3),
            onDestroyExplosion:"barrel_explosion",
            assets:{
                particles:{
                    particle:"metal_particle",
                    tint:0x484848
                },
                sounds:hit_sounds.heavy_metal
            },
            rotation_mode:RotationMode.full,
            reflect_bullets:true,
            spawnMode:Spawn.grass,
        },
        {
            idString:"oak_tree",
            health:110,
            hitbox:new CircleHitbox2D(v2(0,0),0.4),
            spawnHitbox:new CircleHitbox2D(v2(0,0),1.5),
            scale:{
                min:1,
                max:1.2,
                destroy:0.75,
            },
            assets:{
                particles:{},
                frame:{
                    biome_skins:["snow","fall_1","fall_2"],
                },
                sounds:hit_sounds.tree
            },
            zIndex:{
                base:zIndexes.Obstacles4
            },
            rotation_mode:RotationMode.full,
            below:{
                hitbox:new CircleHitbox2D(v2(0,0),2.2),
                alpha:60
            },
            spawnMode:Spawn.grass,
        },
        {
            idString:"pine_tree",
            health:180,
            hitbox:new CircleHitbox2D(v2(0,0),0.5),
            spawnHitbox:new CircleHitbox2D(v2(0,0),1.8),
            scale:{
                min:1,
                max:1.2,
                destroy:0.75,
            },
            assets:{
                particles:{
                    particle:"oak_tree_particle"
                },
                frame:{
                    dead:"oak_tree_dead",
                    biome_skins:["snow","fall_1","fall_2"],
                },
                sounds:hit_sounds.tree
            },
            zIndex:{
                base:zIndexes.Obstacles5
            },
            rotation_mode:RotationMode.full,
            below:{
                hitbox:new CircleHitbox2D(v2(0,0),2.5),
                alpha:60
            },
            spawnMode:Spawn.grass,
        },
        obstacles_factory.bush("bush",{
            o:{
                assets:{
                    frame:{
                        biome_skins:["snow","fall_1","fall_2"],
                    },
                }
            }
        }),
        obstacles_factory.bush("squared_bush",{
            hitbox:new RectHitbox2D(v2.new(-1.1,-1.1),v2.new(1.1,1.1)),
            o:{
                health:130,
                scale:{
                    min:1,
                    max:1.1,
                },
                assets:{
                    frame:{
                        biome_skins:["snow","fall_1","fall_2"],
                        dead:"bush_dead",
                    },
                }
            }
        }),
        obstacles_factory.box("box",{
            o:{
                lootTable:"normal_loot",
                assets:{
                    frame:{
                        variations:2
                    }
                }
            }
        }),
        obstacles_factory.crate("wood_crate",{
            o:{
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x583b08
                    },
                    sounds:hit_sounds.wood,
                    frame:{
                        biome_skins:["snow"],
                    }
                },
                interactDestroy:true,
            }
        }),
        obstacles_factory.crate("campfire_crate",{
            o:{
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x0a753d
                    },
                    frame:{
                        dead_transform:{
                            tint:0x0a753d,
                        },
                        biome_skins:["snow"],
                    },
                    sounds:hit_sounds.wood
                },
                invisible_on_map:true,
                interactDestroy:true,
            }
        }),
        obstacles_factory.crate("md_crate",{
            o:{
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x7021d3
                    },
                    frame:{
                        dead_transform:{
                            tint:0x7021d3,
                        },
                        biome_skins:["snow"],
                    },
                    sounds:hit_sounds.wood
                },
                invisible_on_map:true,
                interactDestroy:true,
            }
        }),
        obstacles_factory.crate("copper_crate",{
            o:{
                health:130,
                assets:{
                    frame:{
                        dead:"metal_residue_1x1",
                        dead_transform:{
                            tint:0xcc742d,
                            scale:2.3
                        },
                        biome_skins:["snow"],
                    },
                    particles:{
                        particle:"metal_particle",
                        tint:0xcc742d,
                    },
                    sounds:hit_sounds.light_metal
                },
                invisible_on_map:true,
                reflect_bullets:true,
            }
        }),
        obstacles_factory.crate("iron_crate",{
            o:{
                health:180,
                assets:{
                    frame:{
                        dead:"metal_residue_1x1",
                        dead_transform:{
                            tint:0x656877,
                            scale:2.3
                        },
                        biome_skins:["snow"],
                    },
                    particles:{
                        particle:"metal_particle",
                        tint:0x656877,
                    },
                    sounds:hit_sounds.light_metal
                },
                invisible_on_map:true,
                reflect_bullets:true,
                hitbox:new RectHitbox2D(v2(-0.8,-0.8),v2(0.8,0.8)),
            }
        }),
        obstacles_factory.crate("gold_crate",{
            o:{
                health:180,
                assets:{
                    frame:{
                        dead:"metal_residue_1x1",
                        dead_transform:{
                            tint:0xffd92b,
                            scale:2.3
                        },
                        biome_skins:["snow"],
                    },
                    particles:{
                        particle:"metal_particle",
                        tint:0xffd92b,
                    },
                    sounds:hit_sounds.light_metal
                },
                invisible_on_map:true,
                reflect_bullets:true,
                hitbox:new RectHitbox2D(v2(-0.8,-0.8),v2(0.8,0.8)),
            }
        }),
        obstacles_factory.crate("ammo_crate",{
            o:{
                health:200,
                resistence:1,
                assets:{
                    particles:{
                        particle:"metal_particle",
                        tint:0x0a753d
                    },
                    sounds:hit_sounds.metal,
                    frame:{
                        dead:"metal_residue_1x1",
                        dead_transform:{
                            tint:0x0a753d
                        }
                    }
                },
                decal:{
                    def:"wood_pallet",
                    scale:1.6
                },
                lootTable:"ammo_crate",
            }
        }),

        {
            idString:"airdrop_locked",
            imortal:true,
            health:1,
            hitbox:new RectHitbox2D(v2(-0.88,-0.88),v2(0.88,0.88)),
            assets:{
                particles:{
                    particle:"metal_particle",
                    tint:0x656877,
                },
                sounds:hit_sounds.heavy_metal,
            },
            rotation_mode:RotationMode.null,
            height:1,
            reflect_bullets:true,
            expanded_behavior:{
                type:3,
                delay:2.8,
                sound:"airdrop_unlocking_1",
                obstacles:[
                    {id:"iron_crate",weight:10},
                    {id:"gold_crate",weight:1},
                ],
                sprites:{
                    0:{image:"airdrop_locked_1"},
                    1:{image:"airdrop_locked_2"},
                },
                first_particles:[
                    {
                        frame:{
                            image:"airdrop_particle_1",
                            scale:2,
                            zIndex:zIndexes.Particles
                        },
                        count:1,
                        delay:0
                    }
                ],
                transform_particles:[
                    {
                        frame:{
                            image:"airdrop_particle_2",
                            scale:2,
                            zIndex:zIndexes.Particles
                        },
                        count:10,
                        delay:0
                    }
                ]
            }
        },

        obstacles_factory.chest("military_chest",{
            o:{
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x628254
                    },
                    sounds:hit_sounds.wood
                },
                invisible_on_map:true,
            }
        }),
        obstacles_factory.chest("md_chest",{
            o:{
                assets:{
                    particles:{
                        particle:"plank_particle",
                        tint:0x161616
                    },
                    frame:{
                        dead:"wood_residue_1x21",
                    },
                    sounds:hit_sounds.wood
                },
                invisible_on_map:true,
            }
        }),
        
        obstacles_factory.walls.door("wood_door",WallColors,{
            o:{
                health:60,
                assets:{
                    sounds:hit_sounds.wood
                }
            }
        }),
        obstacles_factory.walls.door("metal_door",WallColors,{
            sounds:"metal_door",
            particle:"metal_particle",
            o:{
                imortal:true,
                reflect_bullets:true,
                assets:{
                    sounds:hit_sounds.light_metal
                }
            }
        }),
        ...obstacles_factory.walls.group("wood",WallColors,{
            o:{
                assets:{
                    sounds:hit_sounds.wood
                }
            }
        }),
        ...obstacles_factory.walls.group("stone",WallColors,{
            o:{
                assets:{
                    sounds:hit_sounds.rock,
                    particles:{
                        variations:2,
                    }
                },
            },
            particle:"rock_particle",
            health:80,
        }),
        {
            idString:"iron_ladder_bottom",
            hitbox:new RectHitbox2D(v2(-0.15,-0.5),v2(0.15,0.5)),
            imortal:true,
            assets:{
                sounds:hit_sounds.heavy_metal,
                particles:{
                    particle:"metal_particle",
                    tint:0x656877,
                },
            },
            reflect_bullets:true,
            rotation_mode:RotationMode.limited,
            expanded_behavior:{
                type:2,
                action_time:1,
                interact_side:[{
                    pos:v2(-0.7,0),
                    rot:0,
                    dest_pos:v2(0.7,0)
                }],
                floor_walk:1,
            }
        },
        {
            idString:"iron_ladder_top",
            imortal:true,
            hitbox:new RectHitbox2D(v2(-0.15,-0.5),v2(0.15,0.5)),

            assets:{
                sounds:hit_sounds.heavy_metal,
                particles:{
                    particle:"metal_particle",
                    tint:0x656877,
                },
            },

            reflect_bullets:true,
            rotation_mode:RotationMode.limited,

            expanded_behavior:{
                type:2,
                action_time:1,
                interact_side:[{
                    pos:v2(0.8,0),
                    rot:180,
                    dest_pos:v2(-0.7,0)
                }],
                floor_walk:-1,
            }
        },
        /*
        obstacles_factory.crate("platinum_crate",0x468edb,{
            health:500,
            material:"iron",
            reflect_bullets:true,
            scale:{
                destroy:0.75,
            },
            hitbox:RectHitbox2D.centered(v2.zero(),v2(3,3)),
            height:0,
            invisible_on_map:true,
        }),
        */

        //Furnitunes
        {
            idString:"normal_tv",
            health:150,
            hitbox:new RectHitbox2D(v2(-0.4,-0.4),v2(0.4,0.4)),
            reflect_bullets:true,
            assets:{
                frame:{
                    dead:"metal_residue_1x1",
                    dead_transform:{
                        tint:0x484848,
                        scale:0.85
                    }
                },
                particles:{
                    particle:"metal_particle",
                    tint:0x484848,
                },
                sounds:hit_sounds.light_metal,
            },
            rotation_mode:RotationMode.limited,
            zIndex:{
                base:zIndexes.Obstacles2
            },
        },
        {
            idString:"couch_3x1",
            health:100,
            hitbox:new RectHitbox2D(v2(-0.55,-1.4),v2(0.55,1.4)),
            scale:{
                destroy:0.8
            },
            assets:{
                sounds:hit_sounds.tissue,
                particles:{
                    particle:"tissue_particle",
                    tint:0xdfe1e4
                },
            },
            rotation_mode:RotationMode.limited,
            height:1,
        },
        {
            idString:"large_drawer",
            health:65,
            hitbox:new RectHitbox2D(v2(-0.475,-1.15),v2(0.475,1.15)),
            scale:{
                destroy:0.75
            },
            assets:{
                frame:{
                    transform:{
                        hotspot:v2(0.445,0.5)
                    },
                    dead:"wood_residue_1x2",
                    dead_transform:{
                        tint:0x5f3d07,
                    }
                },
                particles:{
                    particle:"plank_particle",
                    tint:0x583b08
                },
                sounds:hit_sounds.wood
            },
            rotation_mode:RotationMode.limited,
            lootTable:"wood_crate",
            height:1,
        },
        {
            idString:"small_stove",
            health:85,
            hitbox:new RectHitbox2D(v2(-0.56,-0.56),v2(0.56,0.56)),
            scale:{
                destroy:0.9
            },
            assets:{
                frame:{
                    variations:2,
                    transform:{
                        hotspot:v2(0.4495,0.5)
                    },
                    dead:"metal_residue_1x1",
                    dead_transform:{
                        tint:0x484848,
                    }
                },
                particles:{
                    particle:"metal_particle",
                    tint:0x484848
                },
                sounds:hit_sounds.heavy_metal,
            },
            rotation_mode:RotationMode.limited,
            onDestroyExplosion:"barrel_explosion",
            reflect_bullets:true,
            height:1,
        },
        {
            idString:"sink",
            health:85,
            hitbox:new RectHitbox2D(v2(-0.56,-0.56),v2(0.56,0.56)),
            scale:{
                destroy:0.9
            },
            assets:{
                frame:{
                    variations:2,
                    dead:"metal_residue_1x1",
                    dead_transform:{
                        tint:0x484848,
                    }
                },
                particles:{
                    particle:"metal_particle",
                    tint:0x484848
                },
                sounds:hit_sounds.heavy_metal,
            },
            rotation_mode:RotationMode.limited,
            reflect_bullets:true,
            height:1,
        },
        {
            idString:"large_kitchen_drawer",
            health:70,
            hitbox:new RectHitbox2D(v2(-0.56,-1.12),v2(0.56,1.12)),
            scale:{
                destroy:0.9
            },
            assets:{
                frame:{
                    variations:2,
                    transform:{
                        hotspot:v2(0.4495,0.5)
                    },
                    dead:"wood_residue_1x2",
                    dead_transform:{
                        tint:0x5f3d07,
                    },
                },
                particles:{
                    particle:"plank_particle",
                    tint:0x583b08
                },
                sounds:hit_sounds.wood,
            },
            rotation_mode:RotationMode.limited,
            lootTable:"wood_crate",
            height:1,
        },

        {
            idString:"wood_table",
            health:100,
            no_collision:true,
            passable_by_bullets:true,
            hitbox:new RectHitbox2D(v2(-0.75,-1.12),v2(0.75,1.12)),
            scale:{
                destroy:0.9
            },
            assets:{
                frame:{
                    dead:"wood_residue_1x2",
                    dead_transform:{
                        tint:0x5f3d07,
                    }
                },
                particles:{
                    particle:"plank_particle",
                    tint:0x583b08
                },
                sounds:hit_sounds.wood,
            },
            zIndex:{
                base:zIndexes.Obstacles3
            },
            rotation_mode:RotationMode.limited,
        },
        {
            idString:"wood_chair",
            health:65,
            hitbox:new RectHitbox2D(v2(-0.49,-0.47),v2(0.49,0.47)),
            scale:{
                destroy:0.9
            },
            assets:{
                frame:{
                    dead:"wood_residue_1x1",
                    dead_transform:{
                        tint:0x5f3d07,
                    },
                },
                particles:{
                    particle:"plank_particle",
                    tint:0x583b08
                },
                sounds:hit_sounds.wood,
            },
            rotation_mode:RotationMode.limited,
            height:1,
        },
        {
            idString:"small_bed",
            health:100,
            hitbox:new RectHitbox2D(v2(-0.77,-1.28),v2(0.77,1.28)),
            scale:{
                destroy:0.8
            },
            assets:{
                frame:{
                    variations:2,
                    dead:"wood_residue_1x2",
                    dead_transform:{
                        tint:0x5f3d07,
                        scale:2.3
                    },
                },
                particles:{
                    particle:"tissue_particle",
                    tint:[0xdfe1e4,0x3f4658]
                },
                sounds:hit_sounds.tissue
            },
            rotation_mode:RotationMode.limited,
            lootTable:"wood_crate",
            height:1,
        },
        obstacles_factory.gun_mount(guns.getFromString("model94"),{}),
        obstacles_factory.gun_mount(guns.getFromString("blr81"),{}),
        obstacles_factory.gun_mount(guns.getFromString("kar98k"),{}),
        obstacles_factory.gun_mount(guns.getFromString("rifle_cbc"),{}),
        obstacles_factory.gun_mount(guns.getFromString("vss"),{}),
        obstacles_factory.gun_mount(guns.getFromString("awp"),{}),
    )
}