import { CircleHitbox2D, Definition, Definitions, FrameDef, Hitbox2D, mergeDeep, v2 } from "../../../engine/core.ts";
import { zIndexes } from "../../others/constants.ts";
import { SideEffect, SideEffectType } from "../player/effects.ts";
export interface SyncedParticleDef extends Definition{
    frame:FrameDef
    lifetime:number
    action_time?:number
    side_effect?:SideEffect[]
    no_hit_owner?:boolean
    hitbox?:Hitbox2D
    movement?:({
        type:"walk"
        velocity:{
            min:number
            max:number
            decay?:number
        }
    }|{
        type:"direction"
        velocity:{
            decay?:number
        }
    })&{
        angular?:{
            min:number
            max:number
        }
    }
    animation?:{
        spawn?:{
            scale?:{
                to:number
                duration:number
            }
            alpha?:{
                from:number
                to:number
                duration:number
            }
        }
        destroy?:{
            time:number
            scale?:{
                to:number
                duration:number
            }
            alpha?:{
                to:number
                duration:number
            }
        }
    }
}
export const synsed_particle_factory={
    spray(id:string,tint:number,side_effect:SideEffect[]=[]):SyncedParticleDef{
        return mergeDeep({
            idString:id,
            lifetime:1,
            no_hit_owner:true,
            hitbox:new CircleHitbox2D(v2.zero,0.5),
            side_effect:side_effect,
            frame:{
                image:"firing_particle",
                scale:0.01,
                tint:tint
            },
            movement:{
                type:"direction",
                velocity:{
                    decay:1.5
                },
                angular:{
                    min:5,
                    max:10
                },
            },
            animation:{
                spawn:{
                    alpha:{
                        from:0,
                        to:0.7,
                        duration:0.2,
                    },
                    scale:{
                        to:0.6,
                        duration:0.5,
                    }
                },
                destroy:{
                    time:1,
                    alpha:{
                        to:0,
                        duration:0.3,
                    },
                }
            }
        })
    }
}
export function SyncedParticle_Default_Init(synced_particles:Definitions<SyncedParticleDef,{}>){
    synced_particles.insert(
        {
            idString:"smoke",
            lifetime:33,
            frame:{
                image:"smoke_particle",
                scale:0.01
            },
            movement:{
                type:"walk",
                velocity:{
                    min:0,
                    max:1.7,
                    decay:0.66
                },
                angular:{
                    min:0.6,
                    max:2
                },
            },
            animation:{
                spawn:{
                    alpha:{
                        from:0,
                        to:0.92,
                        duration:2,
                    },
                    scale:{
                        to:2,
                        duration:0.5,
                    }
                },
                destroy:{
                    time:1,
                    alpha:{
                        to:0,
                        duration:0.5,
                    },
                }
            }
        },
        {
            idString:"airdrop_smoke",
            lifetime:1,
            frame:{
                image:"smoke_particle",
                scale:1.25,
                alpha:0.92
            },
            movement:{
                type:"walk",
                velocity:{
                    min:1,
                    max:3,
                    decay:1.7
                },
                angular:{
                    min:0.6,
                    max:2
                },
            },
            animation:{
                destroy:{
                    time:1,
                    alpha:{
                        to:0,
                        duration:1,
                    },
                }
            }
        },

        {
            idString:"m2_2_fire",
            lifetime:1.5,
            no_hit_owner:true,
            hitbox:new CircleHitbox2D(v2.zero,0.5),
            side_effect:[
                {
                    type:SideEffectType.AddEffect,
                    duration:5,
                    effect:"fire"
                },
                {
                    type:SideEffectType.Damage,
                    amount:1.5,
                    obstacle_mult:1.5
                }
            ],
            frame:{
                image:"firing_particle",
                scale:0.01,
                tint:0xe68302
            },
            movement:{
                type:"direction",
                velocity:{
                    decay:1.5
                },
                angular:{
                    min:5,
                    max:10
                },
            },
            animation:{
                spawn:{
                    alpha:{
                        from:0,
                        to:0.7,
                        duration:0.2,
                    },
                    scale:{
                        to:1,
                        duration:0.5,
                    }
                },
                destroy:{
                    time:1,
                    alpha:{
                        to:0,
                        duration:0.3,
                    },
                }
            }
        },
        {
            idString:"molotov_fire",
            lifetime:33,
            hitbox:new CircleHitbox2D(v2.zero,0.5),
            side_effect:[
                {
                    type:SideEffectType.AddEffect,
                    duration:5,
                    effect:"fire"
                },
                {
                    type:SideEffectType.Damage,
                    amount:0.5,
                    obstacle_mult:1
                }
            ],
            frame:{
                image:"firing_particle",
                scale:0.01,
                zIndex:zIndexes.Decals,
                tint:0xe68302
            },
            movement:{
                type:"walk",
                velocity:{
                    min:0.7,
                    max:4,
                    decay:2
                },
                angular:{
                    min:1,
                    max:4
                },
            },
            animation:{
                spawn:{
                    alpha:{
                        from:0,
                        to:0.5,
                        duration:0.2,
                    },
                    scale:{
                        to:1,
                        duration:0.2,
                    }
                },
                destroy:{
                    time:1,
                    alpha:{
                        to:0,
                        duration:0.2,
                    },
                }
            }
        },
        synsed_particle_factory.spray("healing_spray_particle",0x33ff55,[
            {
                type:SideEffectType.Heal,
                health:{
                    amount:0.5,
                }
            }
        ])
    )
}