import { DeepPartial, Definition, Definitions, mergeDeep, v2, Vec2 } from "../../../engine/core.ts";
import { zIndexes } from "../../others/constants.ts";

export interface VehicleDef extends Definition{
    frame:{
        base?:string
        base_scale?:number
        zindex?:number
    }
    center:Vec2
    movimentation:{
        acceleration:number
        angle_acceleration:number
        final_speed:number
        back_walk_mult:number
        desacceleration:number
    }
    pillot_seat?:{
        position:Vec2
        leave:Vec2
        doors:Vec2[]
    }
    seats?:{
        position:Vec2
        leave:Vec2
        doors:Vec2[]
    }[]
    wheels:{
        defs:{
            movable:boolean
            position:Vec2
            scale:number
        }[]
        frame?:string
    }
    infinity_walk?:boolean
    battle_plane?:{
        main_seat:Vec2
        leave_position:Vec2
        seats_count:number
    }
}


export const VehicleTemplates={
    bike:(id:string,...merge:DeepPartial<VehicleDef>[])=>mergeDeep({
        idString:id,
        frame:{
            base_scale:2.5
        },
        center:v2(0,0),
        movimentation:{
            acceleration:0.5,
            angle_acceleration:8,
            final_speed:20,
            back_walk_mult:0.2,
            desacceleration:0.5
        },
        pillot_seat:{
            position:v2(0,0),
            leave:v2(0,1),
            doors:[v2(0,0.5),v2(0,-0.5)]
        },
        wheels:{
            defs:[
                {
                    movable:true,
                    position:v2(.5,0),
                    scale:2.5
                }
            ]
        }
    },...merge),
    jeep:(id:string,...merge:DeepPartial<VehicleDef>[])=>mergeDeep({
        idString:id,
         frame:{
            base_scale:4
        },
        center:v2(2,3),
        movimentation:{
            acceleration:0.5,
            angle_acceleration:3,
            final_speed:12,
            back_walk_mult:0.5,
            desacceleration:0.8
        },
        pillot_seat:{
            position:v2(0,-0.7),
            leave:v2(0,-1.5),
            doors:[v2(0,-1.5)]
        },
        seats:[
            {position:v2(0,0.7),leave:v2(0,2),doors:[v2(0,1.5)]}
        ],
        wheels:{
            defs:[
                {
                    movable:true,
                    position:v2(.4,-1.4),
                    scale:2.5
                },
                {
                    movable:true,
                    position:v2(.4,1.4),
                    scale:2.5
                },
                {
                    movable:false,
                    position:v2(-1.5,-1.4),
                    scale:2.5
                },
                {
                    movable:false,
                    position:v2(-1.5,1.4),
                    scale:2.5
                }
            ]
        }
    },...merge),
}satisfies Record<string,(id:string,...merge:DeepPartial<VehicleDef>[])=>VehicleDef>
export function Vehicles_Default_Init(vehicles:Definitions<VehicleDef,{}>){
    vehicles.insert(
        VehicleTemplates.bike("bike"),
        VehicleTemplates.jeep("jeep"),
        /*{
            idString:"battle_plane",
            center:v2.zero(),
            frame:{
                base_scale:13,
                zindex:zIndexes.Planes
            },
            movimentation:{
                acceleration:0,
                angle_acceleration:0,
                final_speed:20,
                back_walk_mult:0,
                desacceleration:0
            },
            battle_plane:{
                main_seat:v2(0,0),
                leave_position:v2(0,0),
                seats_count:100,
            },
            wheels:{
                defs:[]
            }
        },*/
    )
}