export function main(ctx){
    return {
        definitions:{
            items:{
                guns:[
                    {
                        idString:"example_ak47",
                        fireDelay:0.1,
                        switchDelay:0.6,
                        spread:5,
                        lenght:1.2,
                        ammoType:"22lr",
                        ammoSpawnAmount:90,
                        class:ctx.globals.GunClasses.Assault,
                        quality:ctx.globals.ItemQuality.Rare,
                        assets:{
                            item:"ak47",
                            world:"ak47_world",
                            use_sound:"ak47_fire",
                            reload_sound:"ak47_reload",
                        },
                        bullet:{
                            def:{
                                damage:7,
                                radius:0.014,
                                range:170,
                                speed:40,
                                tracer:ctx.globals.tracers.medium
                            }
                        },
                        reload:{
                            delay:2.5,
                            capacity:30
                        },
                        recoil:{
                            duration:0.12,
                            speed:0.75
                        },
                        speed_mod:0.97,
                        gasParticles:ctx.globals.GasParticles.automatic,
                        muzzleFlash:ctx.globals.MuzzleFlash.normal,
                        arms:ctx.globals.WeaponsArmRig[0],
                        image:ctx.globals.WeaponsRig[0]
                    },
                    {
                        idString:"example_m9",
                        fireDelay:0.2,
                        spread:0.7,
                        lenght:0.8,
                        ammoType:"22lr",
                        fireMode:ctx.globals.FireMode.Single,
                        class:ctx.globals.GunClasses.Pistol,
                        quality:ctx.globals.ItemQuality.Common,
                        ammoSpawnAmount:45,
                        bullet:{
                            def:{
                                damage:11,
                                radius:0.02,
                                range:100,
                                falloff:0.8,
                                speed:31,
                                obstacleMult:1.2,
                                tracer:ctx.globals.tracers.small
                            }
                        },
                        reload:{
                            delay:2,
                            capacity:15,
                        },
                        recoil:{
                            duration:0.34,
                            speed:0.8
                        },
                        speed_mod:0.98,
                        arms:ctx.globals.WeaponsArmRig[3],
                        assets:{
                            item:"m9",
                            use_sound:"m9_fire",
                            reload_sound:"m9_reload",
                            world:"weapon_small_world",
                            world_tint:0xaaaaaa
                        },
                        gasParticles:ctx.globals.GasParticles.pistols,
                        muzzleFlash:ctx.globals.MuzzleFlash.normal,
                        image:ctx.globals.WeaponsRig[0],
                        dual:{
                            assets:{
                                item:"m9_dual",
                                reload_sound:"m9_dual_reload",
                            },
                            dual_offset:0.2,
                            fireDelay:0.15,
                            reload:{
                                capacity:30,
                                delay:3
                            }
                        }
                    },
                ]
            }
        }
    }
}