import { Definition, Definitions, v2, Vec2 } from "../../../engine/core.ts";
import { ItemRank } from "../../others/item.ts";

export enum LoadoutItemKind{
    Body,
    Hair,
    Eyes,
    Shirt
}
export interface LoadoutBodyDef extends Definition{
    item:LoadoutItemKind.Body
    frame?:{
        base?:string
        hand?:string
    }
    mounth:{
        position:Vec2
        normal:string
        open:string
    }
    rank:ItemRank,
}
export interface LoadoutHairDef extends Definition{
    item:LoadoutItemKind.Hair
    position:Vec2
    frame?:{
        base?:string
    }
    rank:ItemRank,
}
export interface LoadoutEyesDef extends Definition{
    item:LoadoutItemKind.Eyes
    position:Vec2
    frame?:{
        base?:string
        blink?:string
    }
    rank:ItemRank,
}
export interface LoadoutShirtDef extends Definition{
    item:LoadoutItemKind.Shirt
    frame?:{
        arm?:string
        arm_tint?:number
        chest?:string
        chest_tint?:number
    }
    rank:ItemRank,
}
export type LoadoutItemDef=LoadoutBodyDef|LoadoutHairDef|LoadoutEyesDef|LoadoutShirtDef
export function Loadout_Default_Init(loadout:Definitions<LoadoutItemDef,{}>){
    loadout.insert(
        {
            item:LoadoutItemKind.Body,
            idString:"body_1",
            rank:ItemRank.E,
            frame:{
                hand:"human_hand_1"
            },
            mounth:{
                position:v2(0.3,0),
                normal:"human_mounth_1_1",
                open:"human_mounth_1_2"
            }
        },
        //Hairs
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_1",
            rank:ItemRank.E,
            position:v2(-0.17,0)
        },
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_2",
            rank:ItemRank.C,
            position:v2(-0.15,0)
        },
        //Eyes
        {
            item:LoadoutItemKind.Eyes,
            position:v2(0.2,0),
            idString:"eyes_1",
            rank:ItemRank.E,
        },
        //Shirt
        {
            item:LoadoutItemKind.Shirt,
            idString:"white_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:"human_shirt_1_chest",
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"blue_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:"human_shirt_1_chest",
                arm_tint:0x0066ff
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"black_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:"human_shirt_1_chest",
                arm_tint:0x222222
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"yellow_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:"human_shirt_1_chest",
                arm_tint:0xe5ce0c
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"red_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:"human_shirt_1_chest",
                arm_tint:0xf01041
            }
        },
    )
}