import { Definition, Definitions, FrameDef, v2, Vec2 } from "../../../engine/core.ts";
import { ItemRank } from "../../others/item.ts";

export enum LoadoutItemKind{
    Body,
    Hair,
    Eyes,
    Shirt,
    Leg,
    Foot,
    Accessory
}
export interface LoadoutBodyDef extends Definition{
    item:LoadoutItemKind.Body
    frame?:{
        base?:string
        hand?:string
    }
    mounth?:{
        position:Vec2
        normal:string
        open:string
    }
    rank:ItemRank
}
export interface LoadoutHairDef extends Definition{
    item:LoadoutItemKind.Hair
    frame?:{
        front?:FrameDef
        back?:FrameDef
    }
    rank:ItemRank
}
export interface LoadoutEyesDef extends Definition{
    item:LoadoutItemKind.Eyes
    position:Vec2
    frame?:{
        base?:string
        blink?:string
    }
    rank:ItemRank
}
export interface LoadoutShirtDef extends Definition{
    item:LoadoutItemKind.Shirt
    frame?:{
        arm?:string
        arm_tint?:number
        chest?:FrameDef
    }
    rank:ItemRank
}
export interface LoadoutLegDef extends Definition{
    item:LoadoutItemKind.Leg
    frame?:FrameDef
    rank:ItemRank
}
export interface LoadoutFootDef extends Definition{
    item:LoadoutItemKind.Foot
    frame?:FrameDef
    downed_frame?:FrameDef
    rank:ItemRank
}
export interface LoadoutAccessoryDef extends Definition{
    item:LoadoutItemKind.Accessory
    frame?:FrameDef
    hide_helmet?:boolean
    rank:ItemRank
}
export type LoadoutItemDef=LoadoutBodyDef|LoadoutHairDef|LoadoutEyesDef|LoadoutShirtDef|LoadoutLegDef|LoadoutFootDef|LoadoutAccessoryDef
export function Loadout_Default_Init(loadout:Definitions<LoadoutItemDef,{}>){
    loadout.insert(
        {
            item:LoadoutItemKind.Body,
            idString:"body_1",
            rank:ItemRank.E,
            frame:{
                hand:"human_hand_1",
            },
            mounth:{
                position:v2(0.33,0),
                normal:"human_mounth_1_1",
                open:"human_mounth_1_2"
            }
        },
        //Hairs
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_1",
            rank:ItemRank.E,
            frame:{
                front:{
                    position:v2(-0.15,0)
                }
            },
        },
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_2",
            rank:ItemRank.E,
            frame:{
                front:{
                    position:v2(-0.22,0)
                }
            }
        },
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_3",
            rank:ItemRank.E,
            frame:{
                front:{
                    position:v2(-0.12,0)
                }
            }
        },
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_4",
            rank:ItemRank.E,
            frame:{
                front:{
                    position:v2(-0.15,0)
                }
            }
        },
        {
            item:LoadoutItemKind.Hair,
            idString:"hair_5",
            rank:ItemRank.E,
            frame:{
                front:{
                    position:v2(-0.1,0)
                }
            }
        },
        //Eyes
        {
            item:LoadoutItemKind.Eyes,
            position:v2(0.2,0),
            idString:"eyes_1",
            rank:ItemRank.E,
        },
        {
            item:LoadoutItemKind.Eyes,
            position:v2(0.2,0),
            idString:"eyes_2",
            rank:ItemRank.E,
        },
        //Shirt
        {
            item:LoadoutItemKind.Shirt,
            idString:"white_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                },
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"blue_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                    tint:0x0066ff
                },
                arm_tint:0x0066ff
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"black_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                    tint:0x222222
                },
                arm_tint:0x222222
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"yellow_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                    tint:0xe5ce0c
                },
                arm_tint:0xe5ce0c
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"red_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                    tint:0xf01041
                },
                arm_tint:0xf01041
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"black_shirt",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_shirt_1_chest",
                    tint:0x26262b
                },
                arm_tint:0x26262b
            }
        },

        {
            item:LoadoutItemKind.Shirt,
            idString:"white_dress",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_dress_1_chest",
                    hotspot:v2.new(0.7,0.5),
                    tint:0xffffff
                },
                arm_tint:0xffffff
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"blue_dress",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_dress_1_chest",
                    hotspot:v2.new(0.7,0.5),
                    tint:0x0066ff
                },
                arm_tint:0x0066ff
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"yellow_dress",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_dress_1_chest",
                    hotspot:v2.new(0.7,0.5),
                    tint:0x0066ff
                },
                arm_tint:0x0066ff
            }
        },
        {
            item:LoadoutItemKind.Shirt,
            idString:"red_dress",
            rank:ItemRank.E,
            frame:{
                arm:"human_shirt_1_arm",
                chest:{
                    image:"human_dress_1_chest",
                    hotspot:v2.new(0.7,0.5),
                    tint:0xe5ce0c
                },
                arm_tint:0xe5ce0c
            }
        },
        //Legs
        {
            item:LoadoutItemKind.Leg,
            idString:"blue_jeans_pants",
            rank:ItemRank.E,
            frame:{
                image:"human_leg_1_1",
                tint:0x233537
            }
        },
        {
            item:LoadoutItemKind.Leg,
            idString:"grey_jeans_pants",
            rank:ItemRank.E,
            frame:{
                image:"human_leg_1_1",
                tint:0x2f2f2f
            }
        },
        {
            item:LoadoutItemKind.Leg,
            idString:"green_grey_jeans_pants",
            rank:ItemRank.E,
            frame:{
                image:"human_leg_1_1",
                tint:0x3c4c42
            }
        },
        // Foot
        {
            item:LoadoutItemKind.Foot,
            idString:"black_shoes",
            rank:ItemRank.D,
            frame:{
                image:"human_foot_1_2",
                tint:0x222233,
                zIndex:0
            },
            downed_frame:{
                image:"human_foot_1_3",
                tint:0x7e7e7e,
                zIndex:2,
            },
        },
        {
            item:LoadoutItemKind.Foot,
            idString:"blue_shoes",
            rank:ItemRank.D,
            frame:{
                image:"human_foot_1_2",
                tint:0x213258,
                zIndex:0,
            },
            downed_frame:{
                image:"human_foot_1_3",
                tint:0x667db0,
                zIndex:2,
            },
        },
        {
            item:LoadoutItemKind.Foot,
            idString:"gray_shoes",
            rank:ItemRank.D,
            frame:{
                image:"human_foot_1_2",
                tint:0x2f4338,
                zIndex:0,
            },
            downed_frame:{
                image:"human_foot_1_3",
                tint:0x878787,
                zIndex:2,
            },
        },
        // Accessorys
        {
            item:LoadoutItemKind.Accessory,
            idString:"white_hair_bow",
            rank:ItemRank.E,
            frame:{
                image:"hair_bow",
                position:v2(-0.1,-0.26),
                rotation:-0.4,
                zIndex:9 
            }
        },
    )
}