import { RectHitbox2D, v2 } from "../../../engine/core.ts";
import { FloorType } from "../../others/terrain.ts";
import { LootTables } from "../loot_tables.ts";
import { building_to_json, buildings_factory } from "../objects/buildings_base.ts";
import { BiomeDef, CounterMapDef, type MapDef } from "./base.ts";
export const NormalBiome:BiomeDef={
    floors:{

    },
    assets:[
        "normal"
    ],
    ambient:{
        particles:["leaf_1_particle_1"],
        particles_tint:0x2b7317,
        rain:true,
    },
    musics:[
        "/sounds/musics/online/game_normal_music_1.mp3",
        "/sounds/musics/online/game_normal_music_2.mp3",
        "/sounds/musics/online/game_normal_music_3.mp3",
    ]
}
export const map_spawns={
    containers:[
        {def:"blue_container_1",weight:10},
        {def:"blue_container_2",weight:10},
        {def:"red_container_1",weight:10},
        {def:"red_container_2",weight:10},
        {def:"yellow_container_1",weight:10},
        {def:"yellow_container_2",weight:10},
        {def:"green_container_1",weight:10},
        {def:"green_container_2",weight:10},
        {def:"black_container",weight:0.1},
    ],
    crates:[
        {def:"wood_crate",weight:1000},
        {def:"copper_crate",weight:100},
        {def:"campfire_crate",weight:20},
        {def:"iron_crate",weight:1},
        {def:"gold_crate",weight:0.05},
    ],
    rocks:[
        {def:"rock",weight:150},
        {def:"golden_rock",weight:1},
        {def:"platinum_rock",weight:0.01},
    ]
}
export const NormalMap:MapDef={
    loot_tables:LootTables,
    biome:NormalBiome,
    buildings:[
        building_to_json(buildings_factory.house.small_house_1("small_house_1",{
            walls_tint:7,
            doors_tint:2,
        }))
    ],
    generation:{
        island:{
            size:v2(500,500),
            spawn:[
                //{def:"small_house_1",count:5},
                {def:"bunker_1",count:3},
                {def:"shed",count:20},
                {def:map_spawns.containers,count:20},

                {def:"jeep",count:5},
                {def:"bike",count:5},

                {def:"sillo",count:10},

                {def:map_spawns.crates,count:500},
                {def:"oak_tree",count:1000},
                {def:map_spawns.rocks,count:500},
                {def:"bush",count:200},
                {def:"barrel",count:100},

                {def:"normal_loot",count:50}
            ],
            terrain:{
                base:FloorType.Water,
                radius:230,
                passes:3,
                points:5,
                variation:50,
                rivers:{
                    divisions:50,
                    spawn_floor:1,
                    expansion:32,
                    defs:[
                        {
                            rivers:[
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:9,width_variation:2},
                                {width:9,width_variation:2},
                            ],
                            weight:1
                        },
                        {
                            rivers:[
                                {width:25,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                            ],
                            weight:1
                        },
                        {
                            rivers:[
                                {width:25,width_variation:2},
                                {width:25,width_variation:2},
                                {width:25,width_variation:2},
                            ],
                            weight:1
                        },
                    ]
                },
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:3,
                    }
                ]
            }
        }
    },
}
export const NormalLobby:MapDef={
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(100,100),
            spawn:[
                {def:map_spawns.containers,count:2},

                {def:"sillo",count:2},

                {def:"jeep",count:1},
                {def:"bike",count:1},

                {def:"oak_tree",count:80},
                {def:"stone",count:50},
                {def:"bush",count:30},

                {def:"wood_crate",count:30},
                {def:"copper_crate",count:6},
                {def:"barrel",count:13},
                {def:"normal_loot",count:20},
            ],
            terrain:{
                base:FloorType.Water,
                radius:50,
                passes:1,
                points:5,
                variation:1,
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:1,
                        variation:1,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:1,
                        variation:1,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const NormalCounterMD:CounterMapDef={
    spawn:[
        RectHitbox2D.centered(v2(15,45),v2(1,6)),
        RectHitbox2D.centered(v2(75,45),v2(1,6))
    ],
    seed:1000,
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(90,90),
            spawn:[
                {def:"sillo",count:2},

                {def:"oak_tree",count:80},
                {def:"stone",count:60},
                {def:"bush",count:40},

                {def:"barrel",count:10},
            ],
            terrain:{
                base:FloorType.Water,
                radius:50,
                passes:1,
                points:5,
                variation:1,
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:1,
                        variation:1,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:1,
                        variation:1,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const SnowBiome:BiomeDef={
    floors:{
        [FloorType.Sand]:{
            color:0x8a979e
        }
    },
    biome_skin:"snow",
    assets:["normal","christmas"],
    ambient:{
        particles:[],
        rain:false,
        snow:true,
        sound:"snowstorm_ambience"
    }
}