import { RectHitbox2D, v2 } from "../../../engine/core.ts";
import { FloorType } from "../../others/terrain.ts";
import { BiomeDef, CounterMapDef, type MapDef } from "./base.ts";
export const NormalBiome:BiomeDef={
    floors:{

    },
    assets:[
        "normal"
    ],
    ambient:{
        particles:[],
        //particles:["leaf_01_particle_1"],
        rain:true,
    },
    musics:[
        "game_normal_music_1",
        "game_normal_music_2",
        "game_normal_music_3",
    ]
}
export const map_spawns={
    containers:[
        {def:"blue_container_1",weight:10},
        {def:"blue_container_2",weight:10},
        {def:"red_container_1",weight:10},
        {def:"red_container_2",weight:10},
        {def:"yellow_container_1",weight:10},
        {def:"yellow_container_2",weight:10},
        {def:"green_container_1",weight:10},
        {def:"green_container_2",weight:10},
    ]
}
export const NormalMap:MapDef={
    loot_tables:{
        //Guns Quality
        "common_guns":[
            {item:"m9",weight:15},
            {item:"taurustx",weight:12},
            {item:"micro_uzi",weight:3},
        ],
        "uncommon_guns":[
            {item:"mp5",weight:1.4},
            {item:"hp18",weight:1},
        ],
        "rare_guns":[
            {item:"ak47",weight:3},
            {item:"ar15",weight:2},
            {item:"m870",weight:2},
        ],
        "epic_guns":[
            {item:"famas",weight:6},
            {item:"m1a1",weight:3},
            {item:"spas12",weight:1},
            {item:"model94",weight:1},
            {item:"blr81",weight:0.7},
        ],
        "mythic_guns":[
            {item:"sr25",weight:15},
            {item:"vector",weight:15},
            {item:"kar98k",weight:7},
            {item:"m2_2",weight:5},
            {item:"m79",weight:1},
            {item:"awp",weight:1},
        ],
        "legendary_guns":[
            {item:"pfeifer_zeliska",weight:10},
            {item:"awms",weight:6},
            {item:"rpg7",weight:0.8},
        ],
        //Guns Spawn
        "guns":[
            {table:"common_guns",weight:21},
            {table:"uncommon_guns",weight:20},
            {table:"rare_guns",weight:17},
            {table:"epic_guns",weight:1},
            {table:"mythic_guns",weight:0.1},
            {table:"legendary_guns",weight:0.01}
        ],
        "special_guns":[
            {table:"uncommon_guns",weight:21},
            {table:"rare_guns",weight:20},
            {table:"common_guns",weight:15},
            {table:"epic_guns",weight:3},
            {table:"mythic_guns",weight:0.7},
            {table:"legendary_guns",weight:0.3}
        ],
        "melees":[
            {item:"axe",weight:10},
            {item:"sledgehammer",weight:1},
        ],
        //Consumibles
        "consumibles":[
            {table:"health_consumibles",count:1,weight:10},
            {table:"adrenaline_consumibles",count:1,weight:7},
            {table:"shield_consumibles",count:1,weight:6},
            {table:"addiction_consumibles",count:1,weight:1},
            {table:"green_bless_consumibles",count:1,weight:0.1},
            {table:"death_consumibles",count:1,weight:0.1},
        ],
        "health_consumibles":[
            {item:"bandage",count:5,weight:8},
            {item:"medikit",count:5,weight:1},
        ],
        "adrenaline_consumibles":[
            {item:"yellow_soda",count:2,weight:8},
            {item:"inhaler",count:1,weight:1},
            {item:"yellow_pills",count:1,weight:0.1},
        ],
        "shield_consumibles":[
            {item:"blue_soda",count:2,weight:8},
            {item:"blue_potion",count:1,weight:1},
            {item:"blue_pills",count:1,weight:0.1},
        ],
        "addiction_consumibles":[
            {item:"red_soda",count:2,weight:5},
            {item:"small_red_crystal",count:4,weight:1},
            {item:"red_crystal",count:2,weight:0.1},
        ],
        "mana_consumibles":[
            {item:"purple_soda",count:2,weight:8},
            {item:"purple_potion",count:1,weight:1},
            {item:"purple_pills",count:1,weight:0.1},
        ],
        "green_bless_consumibles":[
            {item:"green_soda",count:1,weight:1},
        ],
        "death_consumibles":[
            {item:"black_soda",count:1,weight:1},
        ],
        //Ammos
        "ammos":[
            {item:"12g",count:5,weight:5},
            {item:"9mm",count:40,weight:5},
            {item:"762mm",count:40,weight:5},
            {item:"556mm",count:40,weight:5},
            {item:"45acp",count:40,weight:5},
            {item:"22lr",count:60,weight:4},
            {item:"50cal",count:20,weight:0.1},
            {item:"308sub",count:5,weight:0.05},
            {item:"gasoline",count:5,weight:0.05},
            {item:"explosive_ammo",count:2,weight:0.05},
        ],
        "special_ammos":[
            {item:"12g",count:10,weight:6},
            {item:"9mm",count:80,weight:6},
            {item:"762mm",count:80,weight:6},
            {item:"556mm",count:80,weight:6},
            {item:"45acp",count:80,weight:6},
            {item:"22lr",count:100,weight:4},
            {item:"50cal",count:40,weight:0.3},
            {item:"308sub",count:10,weight:0.2},
            {item:"gasoline",count:10,weight:0.2},
            {item:"explosive_ammo",count:4,weight:0.2},
        ],
        //Throwables
        "throwables":[
            {item:"frag_grenade",count:2,weight:70},
            {item:"smoke_grenade",count:2,weight:70},
            {item:"molotov",count:1,weight:30},
            {item:"mirv_grenade",count:1,weight:20},
            {item:"blue_flare",count:1,weight:1},
            {item:"red_flare",count:1,weight:1},
        ],
        //Scopes
        "scopes":[
            {item:"scope_2",count:1,weight:130},
            {item:"scope_3",count:1,weight:60},
            {item:"scope_4",count:1,weight:30},
            {item:"scope_5",count:1,weight:1.5},
            {item:"scope_6",count:1,weight:0.1},
            {item:"scope_7",count:1,weight:0.005},
        ],
        "special_scopes":[
            {item:"scope_2",count:1,weight:130},
            {item:"scope_3",count:1,weight:60},
            {item:"scope_4",count:1,weight:20},
            {item:"scope_5",count:1,weight:2},
            {item:"scope_6",count:1,weight:0.2},
            {item:"scope_7",count:1,weight:0.01},
        ],
        //Armors And Backpacks
        "helmets":[
            {item:"basic_helmet",weight:8},
            {item:"regular_helmet",weight:1},
            {item:"tactical_helmet",weight:0.2},
        ],
        "vests":[
            {item:"basic_vest",weight:8},
            {item:"regular_vest",weight:1},
            {item:"tactical_vest",weight:0.2},
        ],
        "backpacks":[
            {item:"basic_pack",weight:8},
            {item:"regular_pack",weight:1},
            {item:"tactical_pack",weight:0.2},
        ],
        "armors":[
            {table:"helmets",weight:1},
            {table:"vests",weight:1},
        ],
        "equipments":[
            {table:"helmets",weight:1},
            {table:"vests",weight:1},
            {table:"backpacks",weight:1},
        ],
        "special_equipments":[
            {item:"basic_vest",weight:8},
            {item:"regular_vest",weight:3},
            {item:"tactical_vest",weight:0.15},

            {item:"basic_helmet",weight:8},
            {item:"regular_helmet",weight:1},
            {item:"tactical_helmet",weight:0.15},

            {item:"basic_pack",weight:8},
            {item:"regular_pack",weight:1},
            {item:"tactical_pack",weight:0.15},
        ],
        "tactical_equipments":[
            {item:"tactical_vest",weight:1},
            {item:"tactical_helmet",weight:1},
            {item:"tactical_pack",weight:0.8},
        ],
        "accessorys":[
            {weight:5,item:"lucky_coin"},
            {weight:5,item:"pygmy_necklace"},
            {weight:5,item:"liquid_insanity"},
            {weight:5,item:"ghost_ammo"},
            {weight:5,item:"biggest_magazine"},
            {weight:5,item:"self_revive"},
            {weight:4,item:"nature_leaf"},
            {weight:4,item:"bullet_breaker_barrel"},
            {weight:4,item:"rare_projectile"},
            {weight:4,item:"high_quality_projectiles"},
        ],
        //Loot Tables
        "normal_loot":[
            {weight:1,table:"ammos"},
            {weight:1,table:"consumibles"},
            {weight:0.85,table:"guns"},
            {weight:0.6,table:"equipments"},
            {weight:0.4,table:"scopes"},
            {weight:0.25,table:"throwables"},
            {weight:0.01,table:"melees"},
        ],
        "special_loot":[
            {weight:1,table:"special_ammos"},
            {weight:1,table:"consumibles"},
            {weight:0.85,table:"special_guns"},
            {weight:0.6,table:"special_equipments"},
            {weight:0.4,table:"special_scopes"},
            {weight:0.25,table:"throwables"},
            {weight:0.03,table:"melees"},
        ],
        "loot_drawer":[
            {weight:2,count:1,table:"normal_loot"},
            {weight:1,count:2,table:"normal_loot"},
            {weight:0.5,count:3,table:"normal_loot"},
        ],
        //Crates
        "wood_crate":[
            {weight:2,count:1,table:"normal_loot"},
            {weight:1,count:2,table:"normal_loot"},
            {weight:0.5,count:3,table:"normal_loot"},
        ],
        "campfire_crate":[
            [{weight:1,table:"ammos"}],
            [{weight:1,table:"consumibles"}],
            [{weight:1,table:"scopes"}],

            [{weight:1,table:"helmets"}],
            [{weight:1,table:"vests"}],
            [{weight:1,table:"backpacks"}],

            [{weight:1,table:"special_guns",count:2}],
            [{weight:10,table:""},{weight:1,table:"melees"}],
        ],
        "md_crate":[
            [{weight:1,table:"ammos",count:4}],
            [{weight:1,table:"consumibles",count:4}],
            [{weight:1,table:"special_scopes",count:4}],

            [{weight:1,table:"helmets",count:4}],
            [{weight:1,table:"vests",count:4}],
            [{weight:1,table:"backpacks",count:4}],

            [{weight:1,table:"special_guns",count:4}],
            [{weight:1,table:"melees",count:4}],
        ],
        "copper_crate":[
            {weight:1,count:2,table:"special_loot"},
            {weight:0.5,count:3,table:"special_loot"},
            {weight:0.25,count:4,table:"special_loot"},
        ],
        "iron_crate":[
            [{weight:1,table:"special_ammos",count:2}],
            [{weight:1,table:"consumibles",count:2}],
            [{weight:1,table:"tactical_equipments"}],
            [{weight:1,table:"mythic_guns"}],
            [{weight:1,table:"throwables"}],
            [{weight:1,table:"special_scopes"}],
            [{weight:10,table:""},{weight:1,table:"melees"}],
        ],
        "gold_crate":[
            [{weight:1,table:"special_ammos",count:2}],
            [{weight:1,table:"consumibles",count:2}],
            [{weight:10,table:"tactical_equipments"},{weight:1,count:2,table:"tactical_equipments"}],
            [{weight:10,table:"legendary_guns"}],
            [{weight:1,table:"throwables"}],
            [{weight:1,table:"special_scopes"}],
            [{weight:1,table:""},{weight:4,table:"melees"}],
        ],
        "platinum_crate":[
            [{weight:1,table:"special_ammos",count:4}],
            [{weight:1,table:"consumibles",count:7}],
            [{weight:1,count:6,table:"tactical_equipments"}],
            [{weight:1,count:7,table:"mythic_guns"}],
            [{weight:1,count:2,table:"legendary_guns"}],
            [{weight:1,count:2,table:"melees"}],
            [{weight:1,count:5,table:"throwables"}],
            [{weight:1,count:4,table:"special_scopes"}],
        ],
        //Animals
        "animal_medium":[
            [{weight:1,count:1,table:"consumibles"}],
            [{weight:10,count:1,table:""},{weight:1,count:1,table:"ammos"}],
        ]
    },
    biome:NormalBiome,
    generation:{
        island:{
            size:v2(480,480),
            spawn:[
                [
                    //{def:"watchtower",count:5},

                    {def:"bunker_1",count:3},
                    {def:"shed",count:20},
                    {def:map_spawns.containers,count:20},

                    {def:"jeep",count:5},
                    {def:"bike",count:5},

                    {def:"sillo",count:10},

                    {def:"campfire_crate",count:10},
                    {def:"copper_crate",count:20},
                    {def:"wood_crate",count:700},

                    {def:"oak_tree",count:1500},
                    {def:"stone",count:900},
                    {def:"bush",count:1000},
                    {def:"barrel",count:200},

                    {def:"normal_loot",count:50}
                ]
            ],
            terrain:{
                base:FloorType.Water,
                rivers:{
                    divisions:50,
                    spawn_floor:1,
                    expansion:32,
                    defs:[
                        {
                            rivers:[
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:9,width_variation:2},
                                {width:9,width_variation:2},
                            ],
                            weight:1
                        },
                    ]
                },
                floors:[
                    {
                        padding:30,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:14,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:3,
                    }
                ]
            }
        }
    },
}
export const NormalLobby:MapDef={
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(100,100),
            spawn:[
                [
                    //{def:"watchtower",count:1},
                    {def:map_spawns.containers,count:2},

                    //{def:"recorded_tape",count:1},
                    {def:"sillo",count:2},

                    {def:"jeep",count:1},
                    {def:"bike",count:1},

                    {def:"oak_tree",count:80},
                    {def:"stone",count:50},
                    {def:"bush",count:30},

                    {def:"wood_crate",count:30},
                    {def:"copper_crate",count:6},
                    {def:"barrel",count:13},
                    {def:"normal_loot",count:20},

                    /*{def:"pig",count:5},
                    {def:"chicken",count:5}*/
                ]
            ],
            terrain:{
                base:FloorType.Water,
                /*rivers:{
                    divisions:30,
                    spawn_floor:1,
                    expansion:12,
                    defs:[
                        {
                            rivers:[
                                {sub_river_width:2,width:2,width_variation:1,sub_river_chance:0.5},
                                {sub_river_width:1,width:3,width_variation:1,sub_river_chance:0.1},
                            ],
                            weight:10
                        },
                        {
                            rivers:[
                                {sub_river_width:3,width:4,width_variation:1,sub_river_chance:0.9},
                            ],
                            weight:1
                        }
                    ]
                },*/
                floors:[
                    {
                        padding:3,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:1.3,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:1.3,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const NormalCounterMD:CounterMapDef={
    spawn:[
        RectHitbox2D.centered(v2(15,45),v2(1,6)),
        RectHitbox2D.centered(v2(75,45),v2(1,6))
    ],
    seed:1000,
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(90,90),
            spawn:[
                [
                    {def:"sillo",count:2},

                    {def:"oak_tree",count:80},
                    {def:"stone",count:60},
                    {def:"bush",count:40},

                    {def:"barrel",count:10},
                ]
            ],
            terrain:{
                base:FloorType.Water,
                floors:[
                    {
                        padding:13,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:1.3,
                    },
                    {
                        padding:8,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:1.3,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const SnowBiome:BiomeDef={
    floors:{
        [FloorType.Sand]:{
            color:0x8a979e
        }
    },
    biome_skin:"snow",
    assets:["normal","christmas"],
    ambient:{
        particles:[],
        rain:false,
        snow:true,
        sound:"snowstorm_ambience"
    }
}