import { RectHitbox2D, v2 } from "../../../engine/core.ts";
import { Spawn } from "../../others/constants.ts";
import { FloorType, RiverLayerDef } from "../../others/terrain.ts";
import { LootTables } from "../loot_tables.ts";
import { MapBiomeDef, CounterMapDef, type MapDef } from "./base.ts";
export const NormalBiome:MapBiomeDef={
    floors:{

    },
    textures:[
        "normal"
    ],
    particles:["leaf_1_particle_1"],
    particles_tint:0x2b7317,
    musics:[
        "/sounds/musics/online/game_normal_music_1.mp3",
        "/sounds/musics/online/game_normal_music_2.mp3",
        "/sounds/musics/online/game_normal_music_3.mp3",
        "/sounds/musics/online/game_normal_music_4.mp3",
    ]
}
export const map_spawns={
    containers:[
        {def:"blue_container_1",weight:10},
        {def:"blue_container_2",weight:10},
        {def:"blue_container_3",weight:10},
        {def:"blue_container_4",weight:10},
        {def:"red_container_1",weight:10},
        {def:"red_container_2",weight:10},
        {def:"red_container_3",weight:10},
        {def:"red_container_4",weight:10},
        {def:"yellow_container_1",weight:10},
        {def:"yellow_container_2",weight:10},
        {def:"yellow_container_3",weight:10},
        {def:"yellow_container_4",weight:10},
        {def:"green_container_1",weight:10},
        {def:"green_container_2",weight:10},
        {def:"green_container_3",weight:10},
        {def:"green_container_4",weight:10},
        {def:"black_container",weight:1},
    ],
    crates:[
        {def:"wood_crate",weight:1000},
        {def:"copper_crate",weight:100},
        {def:"campfire_crate",weight:10},
        {def:"iron_crate",weight:1},
        {def:"gold_crate",weight:0.05},
    ],
    rocks:[
        {def:"rock",weight:200},
        {def:"golden_rock",weight:1},
        {def:"platinum_rock",weight:0.01},
    ]
}
export const NormalMap:MapDef={
    loot_tables:LootTables,
    biome:NormalBiome,
    /*buildings:[
        building_to_json(buildings_factory.house.small_house_1("small_house_1",{
            walls_tint:7,
            doors_tint:2,
        }))
    ],*/
    generation:{
        island:{
            size:v2(600,600),
            spawn:[
                {def:"small_house_1",count:4},
                {def:"storehouse_1",count:4},
                {def:"bunker_1",count:2},
                {def:"shed",count:20},
                {def:map_spawns.containers,count:20},

                {def:"golden_stone",count:1},

                {def:"sillo",count:10},
                {def:map_spawns.crates,count:450},
                {def:"oak_tree",count:900},
                {def:"river_rock",count:50},
                {def:map_spawns.rocks,count:500},
                {def:"bush",count:300},
                {def:"barrel",count:150},

                {def:"normal_loot",count:100},
                {def:"jeep",count:5},
                {def:"bike",count:5},
                {def:"boat",count:5},
            ],
            structures:[
                {
                    floors:[],
                    radius:60,
                    variation:15,
                    passes:1,
                    points:10,
                    spawn:[
                        {def:"bunker_1",count:1},
                        {def:"oak_tree",count:400,spawn:Spawn.grass_only},
                    ],
                    region:{
                        name:"Soul Forest",
                        position:v2(0,0)
                    }
                },
                {
                    floors:[
                        {
                            type:FloorType.Water,
                            padding:0,
                            spacing:2,
                            variation:2,
                        },
                        {
                            type:FloorType.Sand,
                            padding:10,
                            spacing:2,
                            variation:2,
                        },
                        {
                            type:FloorType.Grass,
                            padding:15,
                            spacing:2,
                            variation:2,
                        },
                    ],
                    radius:100,
                    variation:15,
                    passes:1,
                    points:10,
                    region:{
                        name:"Sub Island",
                        position:v2(0,0)
                    }
                },
            ],
            terrain:{
                base:FloorType.Water,
                radius:265,
                passes:3,
                points:6,
                variation:60,
                rivers:{
                    divisions:50,
                    spawn_floor:1,
                    expansion:32,
                    defs:[
                        {
                            rivers:[
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:9,width_variation:2},
                                {width:9,width_variation:2},
                            ],
                            weight:1
                        },
                        {
                            rivers:[
                                {width:25,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                                {width:15,width_variation:2},
                            ],
                            weight:1
                        },
                        {
                            rivers:[
                                {width:25,width_variation:2},
                                {width:25,width_variation:2},
                                {width:25,width_variation:2},
                            ],
                            weight:1
                        },
                    ]
                },
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:3,
                        variation:3,
                    },
                ]
            }
        }
    },
}
export const NormalLobby:MapDef={
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(100,100),
            spawn:[
                {def:map_spawns.containers,count:2},

                {def:"sillo",count:2},

                {def:"jeep",count:1},
                {def:"bike",count:1},

                {def:"oak_tree",count:80},
                {def:"stone",count:50},
                {def:"bush",count:30},

                {def:"wood_crate",count:30},
                {def:"copper_crate",count:6},
                {def:"barrel",count:13},
                {def:"normal_loot",count:20},
            ],
            terrain:{
                base:FloorType.Water,
                radius:50,
                passes:1,
                points:5,
                variation:1,
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:1,
                        variation:1,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:1,
                        variation:1,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const NormalCounterMD:CounterMapDef={
    spawn:[
        RectHitbox2D.centered(v2(15,45),v2(1,6)),
        RectHitbox2D.centered(v2(75,45),v2(1,6))
    ],
    seed:1000,
    loot_tables:NormalMap.loot_tables,
    generation:{
        island:{
            size:v2(90,90),
            spawn:[
                {def:"sillo",count:2},

                {def:"oak_tree",count:80},
                {def:"stone",count:60},
                {def:"bush",count:40},

                {def:"barrel",count:10},
            ],
            terrain:{
                base:FloorType.Water,
                radius:50,
                passes:1,
                points:5,
                variation:1,
                floors:[
                    {
                        padding:0,
                        type:FloorType.Sand,
                        spacing:1,
                        variation:1,
                    },
                    {
                        padding:10,
                        type:FloorType.Grass,
                        spacing:1,
                        variation:1,
                    }
                ]
            }
        },
    },
    biome:NormalBiome,
}
export const SnowBiome:MapBiomeDef={
    floors:{
        [FloorType.Sand]:0x505659
    },
    skin:"snow",
    textures:["normal"],
    ambient_sound:"snowstorm_ambience",
    musics:[],
    particles:[],
    particles_tint:0
}
export const DesertBiome:MapBiomeDef={
    floors:{
        [FloorType.Sand]:0xa1761a
    },
    textures:["normal"],
    musics:[],
    particles:[],
}
export const river_layers={
    ice:[
        {
            floor:FloorType.Ice,
            push:false,
        }
    ]
} satisfies Record<string,RiverLayerDef[]>