import { v2 } from "../../../engine/core.ts";
import { FloorType } from "../../others/terrain.ts";
import { type BiomeDef, type MapDef } from "./base.ts";
import { map_spawns, NormalMap } from "./normal.ts";

export const TundraBiome:BiomeDef={
    floors:{
        [FloorType.Sand]:{
            color:0x8a979e,
        },
        [FloorType.Water]:{
            color:0x274763,
        }
    },
    biome_skin:"snow",
    assets:["normal"],
    musics:[
        "/sounds/musics/online/game_tundra_music_1.mp3",
        "/sounds/musics/online/game_tundra_music_2.mp3",
        "/sounds/musics/online/game_tundra_music_3.mp3",
    ],
    ambient:{
        particles:[],
        rain:false,
        snow:true,
        sound:"snowstorm_ambience"
    }
}
// No Shotguns And Pistols
export const TundraMap:MapDef={
    loot_tables:{...NormalMap.loot_tables,
        "ammos":[
            {item:"9mm",count:40,weight:6},
            {item:"762mm",count:40,weight:6},
            {item:"556mm",count:40,weight:6},
            {item:"45acp",count:40,weight:6},
            {item:"22lr",count:60,weight:5},
            {item:"50cal",count:20,weight:0.1},
            {item:"308sub",count:5,weight:0.05},
            {item:"gasoline",count:5,weight:0.05},
            {item:"explosive_ammo",count:2,weight:0.05},
        ],
        "special_ammos":[
            {item:"9mm",count:80,weight:5},
            {item:"762mm",count:80,weight:5},
            {item:"556mm",count:80,weight:5},
            {item:"45acp",count:80,weight:5},
            {item:"22lr",count:100,weight:4},
            {item:"50cal",count:40,weight:0.3},
            {item:"308sub",count:10,weight:0.2},
            {item:"gasoline",count:10,weight:0.2},
            {item:"explosive_ammo",count:4,weight:0.2},
        ],
        "scopes":[
            {item:"scope_3",count:1,weight:10},
            {item:"scope_4",count:1,weight:1.7},
            {item:"scope_2",count:1,weight:0.4},
            {item:"scope_5",count:1,weight:0.1},
            {item:"scope_6",count:1,weight:0.01},
            {item:"scope_7",count:1,weight:0.001},
        ],
        "special_scopes":[
            {item:"scope_3",count:1,weight:10},
            {item:"scope_4",count:1,weight:1.7},
            {item:"scope_2",count:1,weight:0.4},
            {item:"scope_5",count:1,weight:0.1},
            {item:"scope_6",count:1,weight:0.01},
            {item:"scope_7",count:1,weight:0.001},
        ],
        "guns":[
            {item:"sr25",weight:21},
            {item:"model94",weight:21},
            {item:"m1921",weight:16.5},
            {item:"blr81",weight:16.5},
            {item:"colt1873",weight:15},
            {item:"ar15",weight:15},
            {item:"m9",weight:15},
            {item:"mp5",weight:15},
            {item:"ak47",weight:15},
            {item:"famas",weight:15},
            {item:"kar98k",weight:9},
            {item:"m79",weight:5},
            {item:"awp",weight:1},
            {item:"pfeifer_zeliska",weight:0.05},
            {item:"awms",weight:0.04},
            {item:"rpg7",weight:0.01},
        ],
        "tundra_crate":[
            [
                {item:"model94",weight:20},
                {item:"sr25",weight:20},
                {item:"blr81",weight:15},
                {item:"kar98k",weight:10},
                {item:"awp",weight:1},
                {item:"pfeifer_zeliska",weight:0.05},
                {item:"awms",weight:0.04},
            ],
            [
                {weight:1,count:2,table:"normal_loot"},
                {weight:0.5,count:3,table:"normal_loot"},
            ],
            [
                {weight:10,count:1,table:"accessorys"},
                {weight:2,count:2,table:"accessorys"},
                {weight:0.5,count:3,table:"accessorys"},
            ],
            [{weight:1,table:"special_scopes"}],
        ],
        "wood_crate":[
            {weight:2,count:3,table:"normal_loot"},
            {weight:1,count:4,table:"normal_loot"},
            {weight:0.5,count:5,table:"normal_loot"},
        ],
        "copper_crate":[
            {weight:1,count:4,table:"special_loot"},
            {weight:0.5,count:5,table:"special_loot"},
            {weight:0.25,count:6,table:"special_loot"},
        ],
    },
    default_floor:FloorType.Water,
    biome:TundraBiome,
    generation:{
        island:{
            size:v2(480,480),
            spawn:[
                [
                    {def:map_spawns.containers,count:20},

                    {def:"bunker_1",count:1},
                    {def:"shed",count:5},
                    {def:"sillo",count:3},

                    {def:"tundra_crate",count:10},
                    {def:map_spawns.crates,count:190},

                    {def:"oak_tree",count:200},
                    {def:map_spawns.rocks,count:150},
                    {def:"bush",count:100},
                    {def:"barrel",count:50},

                    {def:"normal_loot",count:100}
                ]
            ],
            terrain:{
                base:FloorType.Water,
                rivers:{
                    divisions:100,
                    spawn_floor:1,
                    expansion:32,
                    defs:[
                        {
                            rivers:[
                                {width:10,width_variation:2},
                                {width:10,width_variation:2},
                                {width:10,width_variation:2},
                                {width:5,width_variation:2},
                                {width:5,width_variation:2},
                            ],
                            weight:1
                        },
                    ]
                },
                floors:[
                    {
                        padding:30,
                        type:FloorType.Sand,
                        spacing:3,
                        variation:3,
                    },
                    {
                        padding:14,
                        type:FloorType.Snow,
                        spacing:3,
                        variation:3,
                    }
                ]
            }
        }
    },
}