import { v2, Vec2 } from "../../engine/core.ts";

export enum ItemRank{
    E,
    D,
    C,
    B,
    A,
    S,
    Developer
}
export enum FireMode{
    Auto,
    Single,
    Burst
}
export interface FistRig{
    left?:{
        position:Vec2
        rotation:number
        zIndex?:number
        visible?:boolean
    }
    right?:{
        position:Vec2
        rotation:number
        zIndex?:number
        visible?:boolean
    }
}
export interface WeaponAssets{
    item?:string
    item_tint?:number
    world?:string
    world_tint?:number
    switch_sound?:string
    cycle_sound?:string|boolean
    use_sound?:string
}
export const DefaultFistRig:FistRig={
    left:{
        position:v2(0.37,-0.25),
        rotation:0,
    },
    right:{
        position:v2(0.37,0.25),
        rotation:0,
    }
}
export const DefaultDownedWalkFistRig:FistRig={
    left:{
        position:v2(0.52,-0.22),
        rotation:0.05,
    },
    right:{
        position:v2(0.52,0.22),
        rotation:-0.05,
    }
}
export const WeaponsArmRig={
    0:{
        left:{
            position:v2(0.7,-0.05),
            rotation:0.35,
        },
        right:{
            position:v2(0.53,0.07),
            rotation:-0.3,
        }
    },
    1:{
        left:{
            position:v2(0.7,-0.035),
            rotation:0.35,
        },
        right:{
            position:v2(0.5,0.05),
            rotation:-0.3,
        }
    },
    2:{
        left:{
            position:v2(0.85,-0.05),
            rotation:0.2,
        },
        right:{
            position:v2(0.5,0.04),
            rotation:-0.3,
        }
    },
    3:{
        right:{
            position:v2(0.55,0),
            rotation:-0.45,
        }
    },
}
export const WeaponsRig={
    0:{
        position:v2(0.6,0),
        rotation:0
    },
}
export const tracers={
    tiny:{
        width:3,
        height:0.7,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    small:{
        width:5,
        height:0.8,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    medium:{
        width:7,
        height:1,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    large:{
        width:9,
        height:1.3,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    xl:{
        width:11,
        height:1.6,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    mirv:{
        height:1.3,
        width:2,
        color:0x0044aa,
        proj:{
            img:0,
            width:1,
            height:1
        }
    },
    black_projectile:{
        height:1,
        width:2,
        color:0x334455,
        proj:{
            img:0,
            width:1,
            height:1
        }
    }
}